.github/workflows/test_backend.yml, generate_latest_report_redirect.sh, generate_report_details.sh, register_report.sh, tests/govtool-backend/.gitignore, tests/govtool-backend/requirements.txt, tests/govtool-backend/test_cases/test_ada_holder.py, tests/govtool-backend/test_cases/test_drep.py, tests/govtool-backend/test_cases/test_proposal.py
- Add allure-pytest plugin for test report generation
=> Add allure reporting support in backend test

.github/workflows/test_integration_playwright.yml, generate_latest_report_redirect.sh, generate_report_details.sh, register_report.sh, tests/govtool-frontend/playwright/.gitignore, tests/govtool-frontend/playwright/.prettierignore, tests/govtool-frontend/playwright/package-lock.json, tests/govtool-frontend/playwright/package.json, tests/govtool-frontend/playwright/playwright.config.ts, tests/govtool-frontend/playwright/tests/example.spec.ts, tests/govtool-frontend/playwright/tsconfig.json
- Generates playwright test reports and publishes them to gh-pages
=> Add allure-report generation for playwright tests

scripts/govtool/Makefile
Closes #714.
This pull request aims to update the Cardano DB Sync component on SanchoNet from version "sancho-4.1.0" to "sancho-4.2.0" by modifying the image tag in the Makefile. By making this change, the DB Sync element will be effectively updated to the new version, ensuring that the network remains current and operates efficiently.
=> [#714] Updating and restarting Cardano infrastructure on SanchoNet

scripts/govtool/Makefile
The PR updates the Cardano DB Sync component in the Makefile by changing the image tag from "sancho-4-2-0" to "sancho-4-2-1." This adjustment ensures that the DB Sync is now set to the correct version, addressing any previously encountered issues and guaranteeing the proper functioning of the network on SanchoNet.
This was necesary since there was an issue with the previous build with non parsing configuration.
=> [#714] Update Cardano DB Sync with fixed configuration files

CHANGELOG.md, govtool/backend/src/VVA/API.hs, govtool/backend/src/VVA/API/Types.hs
- Add
- add pagination to drep/list
- [related issue](https://github.com/IntersectMBO/govtool/issues/756)
=> [#756] add pagination to drep/list

govtool/metadata-validation/Makefile, govtool/status-service/Makefile, infra/terraform/main.tf, scripts/govtool/Makefile, scripts/govtool/config/templates/docker-compose.yml.tpl, scripts/govtool/info.mk, scripts/govtool/utils.mk
Closes #742.
In response to the issue of failed deployments to the Dev environment due to missing context for the status-service, this pull request aims to address this by creating a status-service AWS registry. The goal is to ensure a successful deployment by providing the necessary context for the status-service. The changes are focused on integrating the status-service docker image utilization into the deploy stack, enabling a smooth deployment process to the Dev environment. Adjustments have been made in various files, such as `Makefile`, in `scripts/govtool/Makefile`, and `docker-compose.yml.tpl`, to incorporate the status-service registry details for optimized deployment functionality.
=> [#742] Missing context for the status service fails deploy to dev

CHANGELOG.md, govtool/backend/sql/list-dreps.sql
fix
- fix drep/list sql query
- [related issue](https://github.com/IntersectMBO/govtool/issues/826)
=> [#826] fix drep/list sql

govtool/frontend/src/components/molecules/CenteredBoxPageWrapper.tsx, govtool/frontend/src/components/organisms/DashboardTopNav.tsx, govtool/frontend/src/components/organisms/Footer.tsx, govtool/frontend/src/pages/ChooseStakeKey.tsx, govtool/frontend/src/pages/CreateGovernanceAction.tsx, govtool/frontend/src/pages/DRepDirectory.tsx, govtool/frontend/src/pages/Dashboard.tsx, govtool/frontend/src/pages/EditDRepMetadata.tsx, govtool/frontend/src/pages/GovernanceActionDetails.tsx, govtool/frontend/src/pages/GovernanceActions.tsx, govtool/frontend/src/pages/GovernanceActionsCategory.tsx, govtool/frontend/src/pages/Home.tsx, govtool/frontend/src/pages/RegisterAsdRep.tsx, govtool/frontend/src/pages/RetireAsDrep.tsx
- add workaround box filling the area above the footer. Have in my mind that it can't be the final solution. We need to relayout the pages (that will be done with the composing architecture implementation). As current Footer is wrongly reused on multiple pages. That should not be needed.
=> fix: fix footer alignment across pages

govtool/frontend/src/components/organisms/DashboardCards/DelegateDashboardCard.tsx, govtool/frontend/src/components/organisms/Modal/StatusModal.tsx
- Fixed: 
Status modal error message overflow
DelegateDashboardCard transactionId
=> fix: Status modal error message overflow & DelegateDashboardCard transactionId

scripts/govtool/analytics-dashboard.mk
The PR modifies the script `analytics-dashboard.mk` in the `govtool` directory to address the issue of building the analytics image for multiple environments. Previously, the image tag was being generated based on the latest commit hash for the `analytics-dashboard`, which was not sufficient for distinguishing between different environments. To solve this, the script now appends the `$(env)` variable to the image tag, allowing for unique identification of images across various environments.
This addesses the CORS issue on test env.
=> Fix building analytics image for multiple environments

govtool/frontend/src/context/pendingTransaction/usePendingTransaction.ts, govtool/frontend/src/context/pendingTransaction/utils.tsx, govtool/frontend/src/hooks/useDelegateToDrep.ts
`usePendingTransaction behavior for delegation and Direct Voter registration/retirement fixed.
Unnecessary delegation success snackbar removed.
- [related issue](https://github.com/IntersectMBO/govtool/issues/897)
=> [#897] Slow delegation issue // usePendingTransaction fixes

.github/workflows/build-and-deploy-beta.yml, .github/workflows/build-and-deploy-dev.yml, .github/workflows/build-and-deploy-staging.yml, .github/workflows/build-and-deploy-test.yml, govtool/analytics-dashboard/Dockerfile, scripts/govtool/config/templates/docker-compose.yml.tpl
The purpose of this pull request is to adjust the configuration of the participation.sanchogov.tools domain so that it exclusively directs traffic to the dev service. This change has implications on various environments such as beta, staging, and test, as well as on the Dockerfile and Docker Compose configuration related to the analytics dashboard.
These modifications result in a setup where requests made to the participation.sanchogov.tools domain are routed solely to the dev service. This enhances the manageability and separation of development and production environments, ensuring that the dev service receives all relevant traffic directed to this domain. Additionally, it streamlines the development process by focusing traffic for testing and development purposes. …
=> Set participation.sanchogov.tools domain to dev service only

govtool/frontend/src/components/organisms/DRepCard.tsx, govtool/frontend/src/components/organisms/DashboardCards/DRepDashboardCard.tsx, govtool/frontend/src/components/organisms/DashboardCards/DelegateDashboardCard.tsx, govtool/frontend/src/i18n/locales/en.ts, govtool/frontend/src/pages/DRepDetails.tsx
- DRep details page Back button fix (bug 2 from [920](https://github.com/IntersectMBO/govtool/issues/920) - others done in different PRs)
- [related issue](https://github.com/IntersectMBO/govtool/issues/920)
=> [#920 - bug 2] DRep details page Back button fix

govtool/frontend/src/components/organisms/DRepCard.tsx, govtool/frontend/src/i18n/locales/en.ts, govtool/frontend/src/models/api.ts, govtool/frontend/src/pages/DRepDirectoryContent.tsx, govtool/frontend/src/utils/tests/dRep.test.ts
- Possibility to manually delegate to "self" DRep added
- [related issue](https://github.com/IntersectMBO/govtool/issues/904)
=> [#904] No option to delegate to myself as a drep

govtool/frontend/src/pages/DRepDirectoryContent.tsx
- DRep yourself card moved to the top of the list in DRep Directory
- [related issue](https://github.com/IntersectMBO/govtool/issues/907)
=> [#907] Move DRep yourself card to top in DRep Directory

CHANGELOG.md, govtool/backend/app/Main.hs, govtool/backend/example-config.json, govtool/backend/src/VVA/API.hs, govtool/backend/src/VVA/API/Types.hs, govtool/backend/src/VVA/Config.hs, govtool/backend/src/VVA/Metadata.hs, govtool/backend/src/VVA/Types.hs, govtool/backend/vva-be.cabal, govtool/frontend/src/models/metadataValidation.ts, govtool/frontend/src/services/API.ts, govtool/frontend/src/services/requests/metadataValidation/postValidate.ts, govtool/frontend/src/utils/tests/validateMetadataHash.test.ts, govtool/frontend/src/utils/validateMetadataHash.ts, govtool/metadata-validation/src/main.ts
a/validate endpoint
Added
- `metadata/validate` endpoint (which under the hood calls /validate endpoint of metadata validation service)
- all endpoint's returning proposals now return additional field "metadataStatus"
=> [#876] add metadata/validate endpoint

tests/test-infrastructure/docker-compose-govtool.yml
Frontend's use of  VITE_BASE_URL has changed, and existing `/api` prefix was removed.
To fix Test deployment, `VITE_BASE_URL=/api` is set in docker-compose file.
=> Reflect VITE_BASE_URL change in test deployment

scripts/govtool/config/templates/docker-compose.yml.tpl
In order to facilitate the metadata validation on backend service we set the POST method to be allowed in CORS.
=> Allow backend to receive POST mehod

govtool/frontend/src/components/molecules/Card.tsx, govtool/frontend/src/components/molecules/DelegationAction.tsx, govtool/frontend/src/components/molecules/types.ts, govtool/frontend/src/components/organisms/DashboardCards/DelegateDashboardCard.tsx
- DRep Id panel on dashboard delegation card is now clickable
- [related issue](https://github.com/IntersectMBO/govtool/issues/926)
=> [#926] DRep panel needs to be clickable

govtool/frontend/src/components/organisms/AutomatedVotingOptions.tsx, govtool/frontend/src/consts/queryKeys.ts, govtool/frontend/src/hooks/queries/index.ts, govtool/frontend/src/hooks/queries/useGetNetworkMetrics.ts, govtool/frontend/src/services/requests/getNetworkMetrics.ts, govtool/frontend/src/services/requests/index.ts
- Automated voting options voting power fix - now voting power in automated voting options shows summed up `abstain` or `no confidence` voting powers from whole network.
- [related issue](https://github.com/IntersectMBO/govtool/issues/932)
=> [#932] Automated voting options voting power fix

scripts/govtool/config/templates/backend-config.json.tpl
This is a hotfix that solves problem with wrong request configuration to metadata-validation service.
=> Update backend config with metadata-validation service address

CHANGELOG.md, govtool/frontend/src/consts/dRepDirectory/filters.test.ts, govtool/frontend/src/consts/dRepDirectory/filters.ts
- Filter `yourself` was incorrectly appended. This PR filters it out making the DRep directory filter match the requirements.
- [related issue](https://github.com/IntersectMBO/govtool/issues/1028)
=> [#1028] fix: remove incorrectly appended filter yourself to drep directory

CHANGELOG.md, govtool/backend/sql/list-dreps.sql, govtool/backend/src/VVA/DRep.hs
- Fix
fix wrong drep type in drep/list 
- [related issue](https://github.com/IntersectMBO/govtool/issues/957)
=> [#957] drep/list drep type fix

govtool/frontend/src/components/molecules/GovernanceActionDetailsCardLinks.tsx, govtool/frontend/src/components/organisms/GovernanceActionDetailsCard.tsx, govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx, govtool/frontend/src/types/global.d.ts
- GA link type has been updated and the code accordingly as well.
=> [#1031] Update GA links type

.github/workflows/test_integration_playwright.yml, tests/govtool-frontend/playwright/.gitignore, tests/govtool-frontend/playwright/lib/helpers/allure.ts, tests/govtool-frontend/playwright/lib/pages/dRepRegistrationPage.ts, tests/govtool-frontend/playwright/playwright.config.ts, tests/govtool-frontend/playwright/tests/1-wallet-connect/walletConnect.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/1-wallet-connect/walletConnect.spec.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegation.drep.spec.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegation.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegation.spec.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegationFunctionality.delegation.spec.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/dRepRegistration.dRep.spec.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/dRepRegistration.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/dRepRegistration.spec.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.spec.ts, tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.dRep.spec.ts, tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/6-miscellaneous/miscellaneous.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/6-miscellaneous/miscellaneous.spec.ts, tests/govtool-frontend/playwright/tests/auth.setup.ts, tests/govtool-frontend/playwright/tests/delegation.teardown.ts, tests/govtool-frontend/playwright/tests/faucet.setup.ts, tests/govtool-frontend/playwright/tests/wallet.bootstrap.ts
- Enhanced allure report visibility
=> Enhance allure dashboard visibility

scripts/govtool/config.mk
In this pull request, the authentication logic for staging environments has been adjusted to enhance flexibility and customization. The script in `scripts/govtool/config.mk` has been modified to consider the environment variable 'env' instead of the domain name when configuring authentication settings for staging environments. This change allows for a more adaptable authentication process tailored to the specific requirements of different staging environments. By updating the authentication configuration based on the 'env' variable, the overall security and functionality of the application is improved, ensuring that the authentication setup is aligned with the precise needs of each staging environment, ultimately enhancing security and user experience.
=> Fix staging basic auth

tests/govtool-frontend/playwright/lib/_mock/index.ts, tests/govtool-frontend/playwright/lib/datafactory/createAuth.ts, tests/govtool-frontend/playwright/lib/helpers/exceptionHandler.ts, tests/govtool-frontend/playwright/lib/pages/proposalSubmissionPage.ts, tests/govtool-frontend/playwright/lib/types.ts, tests/govtool-frontend/playwright/playwright.config.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.spec.ts, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmissionFunctionality.tx.spec.ts, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmissionVisibility.spec.ts, tests/govtool-frontend/playwright/tests/faucet.setup.ts
- Added tests for governance action submission
List of tests are included [here](https://github.com/orgs/IntersectMBO/projects/30/views/12?pane=issue&itemId=62677528)
=> test: Government action proposal submissions

.github/workflows/test_integration_playwright.yml
- Ensured mock directory creation for generating static wallets.
=> fix: ensure directory creation with mkdir -p

scripts/govtool/Makefile, scripts/govtool/docker-compose.node+dbsync.yml
Closes #1035.
This pull request addresses user story #1035 by bumping the versions of cardano-node and cardano dbsync to 8.11.0-sancho and sancho-4-3-0-docker respectively. The Makefile and docker-compose files were updated to reflect these changes. By ensuring that cardano-node is now at the correct version specified in the user story, the infrastructure configuration was also updated accordingly. This aligns with the pre-release version specified in the user story instructions. The changes made in this pull request fulfill the requirement to maintain consistency in versions and configurations for the specified components.
=> [#1035] Bump cardano-node and cardano dbsync

tests/govtool-frontend/playwright/lib/constants/environments.ts
- Resolved the metadata bucket URL issue
Link to the [report](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/3/#behaviors/f7eea6c55a554c79a959f2fe9524fccc/c60d6fcadf7483fc/)
=>  fix: Default cardano_api_metadata host url

CHANGELOG.md, README.md, govtool/backend/src/VVA/API.hs, govtool/backend/src/VVA/API/Types.hs, govtool/frontend/src/components/molecules/GovernanceActionCardElement.tsx, govtool/frontend/src/components/organisms/DashboardCards.tsx, govtool/frontend/src/components/organisms/DashboardCards/DelegateDashboardCard.tsx, govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx, govtool/frontend/src/i18n/locales/en.ts, govtool/frontend/src/pages/DRepDetails.tsx
Add:
add posibility to copy address from Treasury GA
Fix:
[#1073] fix proposal/list 500 error on HardFork proposal
fix lint
fix/1095-do-not-display-direct-voter-card
fix/911-registed-as-a-drep-direct-voter-card
fix/987-my-drep-detail-page-chips-description
fix/649-design-bug-payment-block-delegation-card
Change:
change myDrep chips description
change register as direct voter card description
change direct voter card description
block delegation card when iam direct voter
delete consolelog
Merge Pull Requests:
Merge pull request #1094 from IntersectMBO/1073-bug-internal-server-e…
Merge pull request #1067 from IntersectMBO/chore/code-quality-metrics
Merge pull request #1101 from IntersectMBO/fix/1095-do-not-display-di…
Merge pull request #1100 from IntersectMBO/fix/911-registed-as-a-drep… …
=> Cardano Stack: Address Copying Added, HardFork Proposal Error Fixed, UI Enhancements, and Merged Pull Requests

govtool/metadata-validation/src/dto/validateMetadata.dto.ts, govtool/metadata-validation/src/main.ts, govtool/metadata-validation/src/schemas/cipStandardSchema.ts, govtool/metadata-validation/src/types/validateMetadata.ts, govtool/metadata-validation/src/utils/parseMetadata.ts
- add optional support for CIP-119
- fix error handling for metadata service
=> fix: fix error handling for metadata service; add optional support for CIP-119

tests/govtool-frontend/playwright/global-setup.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegationFunctionality.delegation.spec.ts
- Added retries to overcome flakiness
- Removed DRep ID check in dashboard upon registering as sole voter
- [related issue](https://github.com/IntersectMBO/govtool/issues/1088)
=> Add retry and Add assertion for continue-button

govtool/frontend/src/App.tsx, govtool/frontend/src/consts/navItems.tsx, govtool/frontend/src/utils/index.ts, govtool/frontend/src/utils/isDevEnv.ts
- For all the envs except dev & local pdf is being disabled.
=> chore: disable pdf for the envs other than develop

scripts/govtool/Makefile
Closes #1195.
The PR optimizes the workflow by eliminating redundant steps, specifically related to the deployment config for the toggle-maintenance target. This adjustment simplifies the process, making it more straightforward and less prone to errors caused by unnecessary dependencies.
=> [#1195] Remove unnecessary deployment config dependancy

govtool/frontend/src/components/organisms/VoteContext/VoteContextStoringInformation.tsx, govtool/frontend/src/consts/governanceAction/fields.ts, govtool/frontend/src/hooks/forms/useVoteContextForm.tsx, govtool/frontend/src/i18n/locales/en.ts, govtool/frontend/src/models/metadataValidation.ts, govtool/frontend/src/utils/jsonUtils.ts, govtool/metadata-validation/src/app.service.ts, govtool/metadata-validation/src/dto/validateMetadata.dto.ts
- fix vote context metadata creation to not generate jsonld and cip context, as there is not cip for the vote context
- [related issue](https://github.com/IntersectMBO/govtool/issues/1142)
=> fix: fix vote context metadata creation

.github/workflows/build-and-deploy-beta.yml, .github/workflows/build-and-deploy-staging.yml, .github/workflows/build-and-deploy-test.yml
- set defaults for PDF in yml deploy workflows
- These defaults are passed as build arguments to frontend dockerfile. Having them set makes the deployment available
=> chore: set defaults for PDF in yml deploy workflows

govtool/frontend/src/components/organisms/CreateGovernanceActionSteps/StorageInformation.tsx, govtool/frontend/src/components/organisms/EditDRepInfoSteps/EditDRepStorageInformation.tsx
- Add trim func to file lenght for edit drep data and creat GA forms
- [related issue](https://github.com/IntersectMBO/govtool/issues/1210)
=> 1210-drep-registration-json-file-name-beyond-view-when-drep-title-is-long

govtool/metadata-validation/src/schemas/cipStandardSchema.ts
- fix empty strings drep data validation in validation service
=> fix: fix empty strings drep data validation

.github/workflows/build-and-deploy-beta.yml, .github/workflows/build-and-deploy-staging.yml, .github/workflows/build-and-deploy-test.yml, govtool/frontend/src/components/organisms/DashboardTopNav.tsx, govtool/frontend/src/components/organisms/PDFWrapper.tsx
- add pdf enable toggle to every deployment workflow
- add lazy loading of a pdf pillar
- hide voting power chip for the pdf pillar
=> chore: add pdf enable toggle to every deployment workflow

CHANGELOG.md, govtool/metadata-validation/src/schemas/cipStandardSchema.ts
- fix uri validation of metadatas
Now it should allow urls without a protocol.
- [related issue](https://github.com/IntersectMBO/govtool/issues/1011)
=> fix: fix uri validation of metadatas

tests/govtool-frontend/playwright/lib/constants/staticWallets.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegationFunctionality.delegation.spec.ts, tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.dRep.spec.ts, tests/govtool-frontend/playwright/tests/dRep.setup.ts
- Adjusted temporary wallets count
- Removed retries for 2E, 2S and Added timeout to ensure wallet-connection modal not interfere with interactions.
=> Adjust temporary wallet counts

govtool/frontend/.storybook/preview.tsx, govtool/frontend/.storybook/test-runner-jest.js, govtool/frontend/src/stories/ActionsBar.stories.ts, govtool/frontend/src/stories/Button.stories.ts, govtool/frontend/src/stories/Card.stories.tsx, govtool/frontend/src/stories/Checkbox.stories.tsx, govtool/frontend/src/stories/DashboardCard.stories.ts, govtool/frontend/src/stories/DashboardTopNav.stories.ts, govtool/frontend/src/stories/DelegateActionRadio.stories.ts, govtool/frontend/src/stories/Drawer.stories.ts, govtool/frontend/src/stories/Footer.stories.ts, govtool/frontend/src/stories/GovernanceAction.stories.ts, govtool/frontend/src/stories/GovernanceActionDetailsCard.stories.ts, govtool/frontend/src/stories/Input.stories.tsx, govtool/frontend/src/stories/LinkWithIcon.stories.tsx, govtool/frontend/src/stories/Slider.stories.tsx, govtool/frontend/src/stories/StatusPill.stories.ts, govtool/frontend/src/stories/Step.stories.tsx, govtool/frontend/src/stories/TextArea.stories.tsx, govtool/frontend/src/stories/TopNav.stories.ts, govtool/frontend/src/stories/modals/LoadingModal.stories.tsx, govtool/frontend/src/stories/modals/VotingPowerModal.stories.tsx
- Fixed/Refactored storybook tests
- Added missing tests
=> Enhance Storybook Testing with Additional and Refactored Tests

tests/govtool-frontend/playwright/lib/services/kuberService.ts, tests/govtool-frontend/playwright/lib/types.ts, tests/govtool-frontend/playwright/tests/dRep.setup.ts, tests/govtool-frontend/playwright/tests/faucet.setup.ts
- Replaced hardcoded value for dRep registration with protocol params
=> chore: Replace hardcoded dRep registration amount with protocol params

tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.spec.ts, tests/govtool-frontend/playwright/tests/6-miscellaneous/miscellaneous.dRep.spec.ts, tests/govtool-frontend/playwright/tests/6-miscellaneous/miscellaneous.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/6-miscellaneous/miscellaneous.spec.ts
- Added test for dashboard learn more button action
- Added test for abstain and signal-no-confidence info button action
- Added test for  DRep registration and edit dRep registration page restriction
=> Extended Test Coverage for Dashboard and DRep directory

tests/govtool-backend/models/TestData.py
- Fix proposal format in backend test
=> Update proposal format for test

govtool/frontend/src/components/molecules/GovernanceActionCard.tsx, govtool/frontend/src/components/molecules/GovernanceActionCardElement.tsx
- Fix styling of the markdowns on the slider cards
- [related issue](https://github.com/IntersectMBO/govtool/issues/1244)
=> fix(#1244): Fix styling of the markdowns on the slider cards

CHANGELOG.md, govtool/frontend/src/components/molecules/WalletOption.tsx
- fix blank screen on GAs voting when wallet is not initially connected
- [related issue](https://github.com/IntersectMBO/govtool/issues/1313)
=> fix(#1313): fix blank screen on GAs voting when wallet is not initially connected

tests/test-infrastructure/docker-compose-govtool.yml, tests/test-infrastructure/playbook.yml
- pass GTM_ID env variable to frontend build.
- [related issue](https://github.com/IntersectMBO/govtool/issues/1335)
=> Configure Google tag manager in test stack

tests/test-infrastructure/docker-compose-govtool.yml
- On test stack compose file, add storybook service to frontend network
- [related issue](https://github.com/IntersectMBO/govtool/issues/660)
=> Test-infra: Expose storybook deployment publicly

scripts/govtool/config/templates/docker-compose.yml.tpl
The purpose of these changes is to resolve a Content Security Policy (CSP) issue in the Traefik configuration that was blocking Sentry requests. The existing CSP settings did not allow communication with Sentry endpoints, specifically POST requests to the Sentry API, which was hindering error tracking and monitoring. This update addresses the problem by modifying the `connect-src` directive to include permissions for requests to any instance of Sentry under the `*.ingest.sentry.io` domain. By making this adjustment, the system ensures that Sentry can receive error data, aligning with the user story's requirement for effective error monitoring. The outcome of these changes is a functional error logging and monitoring system through Sentry, as the requests are no longer blocked. Testing has …
=> [#1218] Resolve CSP issue blocking Sentry requests in Traefik configuration

docs/GOVERNANCE_ACTION_SUBMISSION.md, govtool/frontend/src/components/organisms/PDFWrapper.tsx, govtool/frontend/src/types/@intersect.mbo.d.ts
- pass govtool metadata validator to pdf pillar
This PR resolves partially the problem raised in this issue: https://github.com/IntersectMBO/govtool/issues/1372
=> feat: pass govtool metadata validator to pdf pillar

.github/workflows/test_storybook.yml, govtool/frontend/package-lock.json, govtool/frontend/package.json, govtool/frontend/src/components/organisms/RegisterAsDRepSteps/WhatRetirementMeans.tsx, govtool/frontend/src/components/organisms/RegisterAsDirectVoterBox.tsx, govtool/frontend/src/context/getUtxos.ts, govtool/frontend/src/context/governanceAction.tsx, govtool/frontend/src/context/wallet.tsx, govtool/frontend/src/hooks/forms/useCreateGovernanceActionForm.ts, govtool/frontend/src/hooks/forms/useDelegateTodRepForm.tsx, govtool/frontend/src/hooks/forms/useEditDRepInfoForm.ts, govtool/frontend/src/hooks/forms/useRegisterAsdRepForm.tsx, govtool/frontend/src/hooks/forms/useVoteActionForm.tsx, govtool/frontend/src/hooks/forms/useVoteContextForm.tsx, govtool/frontend/src/hooks/useDelegateToDrep.ts, govtool/frontend/src/main.tsx, govtool/frontend/src/types/global.d.ts, govtool/frontend/storybook.Dockerfile
- provide tags to sentry events
- [related issue](https://github.com/IntersectMBO/govtool/issues/1326)
=> chore: provide tags to sentry events

CHANGELOG.md, govtool/frontend/src/i18n/locales/en.ts
- Change label of Proposal Discussion nav item
- [related issue](https://github.com/IntersectMBO/govtool/issues/1349)
=> fix(#1349): Change label of Proposal Discussion nav item

CHANGELOG.md, govtool/frontend/src/App.tsx, govtool/frontend/src/components/atoms/DrawerLink.tsx, govtool/frontend/src/components/organisms/DashboardCards/ProposeGovActionDashboardCard.tsx, govtool/frontend/src/consts/navItems.tsx, govtool/frontend/src/consts/paths.ts
- Fix the navigation to Home from Proposal pillar on disconnected wallet
- [related issue](https://github.com/IntersectMBO/govtool/issues/1355)
=> fix(#1355): fix the navigation to Home from Proposal pillar on disconnected wallet

CHANGELOG.md, govtool/backend/vva-be.cabal
Change
- backend is now compiled with -threaded flag
- [related issue](https://github.com/IntersectMBO/govtool/issues/1148)
=> [#1148] add -threaded flag to backend

CHANGELOG.md, govtool/backend/app/Main.hs
Fix
- silence timeout errors before request could be parsed
- [related issue](https://github.com/IntersectMBO/govtool/issues/1417)
=> [#1417] silence timeout errors

CHANGELOG.md, govtool/backend/app/Main.hs
Fix
- silence connection closed error
- [related issue](https://github.com/IntersectMBO/govtool/issues/1422)
=> [#1422] silence closed connection error

.github/workflows/build-and-deploy-beta.yml, .github/workflows/build-and-deploy-dev.yml, .github/workflows/build-and-deploy-staging.yml, .github/workflows/build-and-deploy-test.yml, CHANGELOG.md, govtool/backend/app/Main.hs, govtool/backend/example-config.json, govtool/backend/sql/get-voting-anchors.sql, govtool/backend/src/VVA/Config.hs, govtool/backend/src/VVA/Metadata.hs, govtool/backend/src/VVA/Types.hs, govtool/backend/vva-be.cabal, scripts/govtool/config.mk, scripts/govtool/config/templates/backend-config.json.tpl, scripts/govtool/config/templates/docker-compose.yml.tpl
Add
- Reddis port, and host in backend config
- Async process that fetches and processes metadata
- querying Metadata returns result from Redis cache if available
- [related issue](https://github.com/IntersectMBO/govtool/issues/1234)
=> [#1234] Add reddis support for storing metadata validation results

CHANGELOG.md, govtool/backend/app/Main.hs, govtool/backend/example-config.json, govtool/backend/src/VVA/API.hs, govtool/backend/src/VVA/Config.hs, govtool/backend/src/VVA/Metadata.hs, govtool/backend/src/VVA/Transaction.hs, govtool/backend/src/VVA/Types.hs, govtool/backend/vva-be.cabal, scripts/govtool/config/templates/backend-config.json.tpl
Added
- /transaction/watch/<TX-HASH> websocket endpoint
- background transaction status process, that looks for watched transactions and sends {"status": "confirmed"} via websocket when transaction is found. This process works in iterations, once per 20 seconds.
IMPORTANT!!!
each /transaction/watch request stores a UUID in Redis in database number 1 (not 0)
this redis store, together with in-memory uuid to WebSocket.Connection map is used to notify user, that transaction of interest is confirmed.
- [related issue](https://github.com/IntersectMBO/govtool/issues/1235)
=> [#1235] add /transaction/watch endpoint & background tx status process

tests/govtool-frontend/playwright/tests/auth.setup.ts
- Temporarily disabled pdf auth
=> Comment auth setup for proposal wallet

CHANGELOG.md, govtool/backend/app/Main.hs, govtool/backend/example-config.json, govtool/backend/src/VVA/API.hs, govtool/backend/src/VVA/Config.hs, govtool/backend/src/VVA/Metadata.hs, govtool/backend/src/VVA/Transaction.hs, govtool/backend/src/VVA/Types.hs, govtool/backend/vva-be.cabal, scripts/govtool/config/templates/backend-config.json.tpl
Due to the wrong redis configuration this PR needs to be reverted.
=> Revert "Merge pull request #1304 from IntersectMBO/1235-tech-debt-provide-event-based-functionality-for-confirmation-of-the-transactions"

.github/workflows/build-and-deploy-beta.yml, .github/workflows/build-and-deploy-dev.yml, .github/workflows/build-and-deploy-staging.yml, .github/workflows/build-and-deploy-test.yml, CHANGELOG.md, govtool/backend/app/Main.hs, govtool/backend/example-config.json, govtool/backend/sql/get-voting-anchors.sql, govtool/backend/src/VVA/Config.hs, govtool/backend/src/VVA/Metadata.hs, govtool/backend/src/VVA/Types.hs, govtool/backend/vva-be.cabal, scripts/govtool/config.mk, scripts/govtool/config/templates/backend-config.json.tpl, scripts/govtool/config/templates/docker-compose.yml.tpl
This reverts commit 3db9567591b6b4177a19b9154e1d72012e6c7104, reversing changes made to e582b5d7d6635dd7e7485f2a28589179d4cf8ff9.
=> Revert "Merge pull request #1256 from IntersectMBO/1234-provide-workers-to-fetch-and-validate-proposals-and-drep"

tests/govtool-frontend/playwright/lib/fixtures/createWallet.ts, tests/govtool-frontend/playwright/lib/fixtures/importWallet.ts, tests/govtool-frontend/playwright/lib/fixtures/loadExtension.ts, tests/govtool-frontend/playwright/lib/fixtures/walletExtension.ts, tests/govtool-frontend/playwright/lib/helpers/page.ts, tests/govtool-frontend/playwright/lib/types.ts, tests/govtool-frontend/playwright/package-lock.json, tests/govtool-frontend/playwright/package.json, tests/govtool-frontend/playwright/tests/1-wallet-connect/walletConnect.spec.ts
- Updated version of cardano-test-wallet to 2.0.0
- Updated wallet (fixtures, helper) to support cardano-test-wallet version 2.0.0
- Fixed test for  incompatible wallets
=> Fix test 1E: Incompatible wallets

tests/govtool-frontend/playwright/lib/pages/proposalDiscussionPage.ts, tests/govtool-frontend/playwright/lib/types.ts, tests/govtool-frontend/playwright/tests/auth.setup.ts
- Enabled setup for proposal auth
- Add type for proposal-create-request
=> Enable proposal auth setup

tests/govtool-frontend/playwright/lib/helpers/extractExpiryDateFromText.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/dRepRegistration.dRep.spec.ts, tests/govtool-frontend/playwright/tests/6-miscellaneous/miscellaneous.spec.ts
- Add `st` , `nd`, `rd` on the date regex of `extractExpiryDateFromText` function.
- Remove the "learn more" assertion on disconnect state as "learn more" for proposing a governance action is no longer on dashboard.
- Add an exact match for "In Progress" on the assertion for dRep registration, as "In Progress" is also taken from "DRep registration in progress"
=> Fix failing test 3I 6D and 4H

govtool/frontend/package-lock.json, govtool/frontend/package.json, govtool/frontend/yarn.lock
- Change @intersect.mbo/pdf-ui version to 0.2.7
=> chore: bump pdf-ui version to 0.2.7

tests/govtool-frontend/playwright/lib/pages/proposalSubmissionPage.ts, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.loggedin.spec.ts
=> Fix: proposal draft test blocked by verify identity button

gov-action-loader/backend/Dockerfile, gov-action-loader/backend/app/main.py, gov-action-loader/backend/app/transaction.py
- Remove `cardano-cli` from gov-action-loader backend
- Use tx-hash from kuber's transaction response
=> Fix: gov-action-loader: remove old cardano-cli dependency

govtool/backend/example-config.json, govtool/backend/src/VVA/API.hs, govtool/backend/src/VVA/Config.hs, govtool/backend/src/VVA/Metadata.hs, govtool/backend/src/VVA/Types.hs
The PR introduces a flag in the configuration to disable metadata validation from querying a server and rather trusts the metadata is valid from db-sync itself.
Usage:
add `"metadatavalidationenabled": false,` to config file
It also fixes some typos in types.hs that weren't used anywhere else in the code.
=> backend: allow using metadata directly from db-sync

govtool/backend/sql/list-proposals.sql
=> list-proposals: fix SQL

CHANGELOG.md, govtool/frontend/Dockerfile, govtool/frontend/package-lock.json, govtool/frontend/package.json, govtool/frontend/vite.config.ts, govtool/frontend/yarn.lock
- Fix building the frontend image.
- [related issue](https://github.com/IntersectMBO/govtool/issues/1583)
=> [#1583] fix: fix frontend build

.github/workflows/resync-cardano-node-and-db-sync.yml, scripts/govtool/Makefile, scripts/govtool/docker-compose.node+dbsync.yml
The purpose of these changes is to update the versions of the Cardano Node and Cardano DB Sync used in our GovTool application to ensure compatibility with version 9.0.0 of the node and version sancho-5.1.0 of DB Sync. This aligns our development and staging environments with the latest network protocols and includes recent fixes and features. By doing this, we aim to maintain synchronization with the updated Cardano protocol, which is crucial for supporting upcoming governance functionalities on the Preview network.
The outcome of these changes is reflected in two main updates: - The `scripts/govtool/Makefile` was modified to upgrade Cardano Node to version 9.0.0-sancho and Cardano DB Sync to sancho-5.1.0. This ensures our application is compatible with the latest network protocols. - …
=> [#1538] Chore: Bump DB-Sync to version `sancho-5-1-0`

govtool/backend/app/Main.hs, govtool/backend/src/VVA/API.hs, govtool/backend/src/VVA/API/Types.hs, govtool/backend/src/VVA/API/Utils.hs, govtool/backend/src/VVA/AdaHolder.hs, govtool/backend/src/VVA/CommandLine.hs, govtool/backend/src/VVA/Config.hs, govtool/backend/src/VVA/DRep.hs, govtool/backend/src/VVA/Metadata.hs, govtool/backend/src/VVA/Pool.hs, govtool/backend/src/VVA/Transaction.hs, govtool/backend/src/VVA/Types.hs, govtool/backend/vva-be.cabal
The purpose of these changes is to address the issue reported by Sentry, where threads on the Haskell backend are being killed by the timeout manager, resulting in unnecessary error reports. The objective is to improve the exception handling logic so that specific exceptions, such as `TimeoutThread` and `ConnectionClosedByPeer`, are recognized and skipped. This aims to prevent these known exceptions from cluttering error reports, thus ensuring that only actionable errors are brought to attention. The user story highlights the need to investigate and fix these timeouts, and the change is a step toward that goal. The outcome of these changes is a more refined error-handling mechanism within the Haskell backend. By updating the dependencies in the `vva-be.cabal` file to include the …
=> [#1417] [Sentry] Exception before request could be parsed: Thread killed by timeout manager

CHANGELOG.md, govtool/backend/src/VVA/Metadata.hs, govtool/backend/src/VVA/Types.hs
* fix(#1417): handle thread killed by timeout manager exception
* fix(#1612): Fix connection to the metadata-validation service
Response from metadata-validation fails on parsing.
=> fix(#1612): Fix connection to the metadata-validation service

CHANGELOG.md, govtool/frontend/src/App.tsx, govtool/frontend/src/pages/CreateGovernanceAction.tsx, govtool/frontend/src/pages/DRepDirectory.tsx, govtool/frontend/src/pages/Dashboard.tsx, govtool/frontend/src/pages/EditDRepMetadata.tsx, govtool/frontend/src/pages/PublicRoute.tsx, govtool/frontend/src/pages/RegisterAsDirectVoter.tsx, govtool/frontend/src/pages/RegisterAsdRep.tsx, govtool/frontend/src/pages/RetireAsDirectVoter.tsx, govtool/frontend/src/pages/RetireAsDrep.tsx, govtool/frontend/src/utils/checkIsWalletConnected.ts, govtool/frontend/src/utils/tests/checkIsWalletConnected.test.ts
- Add redirect to the connected DRep Directory page if a connected user enters a non-connected DRep Directory url
- [related issue](https://github.com/IntersectMBO/govtool/issues/1117)
=> [#1117] redirect to private drep directory url 

CHANGELOG.md, govtool/frontend/src/components/organisms/HomeCards.tsx
- Add redirect to dashboard cards after user successfully connects
- [related issue](https://github.com/IntersectMBO/govtool/issues/1442)
=> [#1442] Add redirect to dashboard cards after connect

.github/workflows/resync-cardano-node-and-db-sync.yml, CHANGELOG.md
- Fix the following error:
```
sed -e "s|<DBSYNC_POSTGRES_DB>|${DBSYNC_POSTGRES_DB}|" \
-e "s|<DBSYNC_POSTGRES_USER>|${DBSYNC_POSTGRES_USER}|" \
-e "s|<DBSYNC_POSTGRES_PASSWORD>|${DBSYNC_POSTGRES_PASSWORD}|" \
-e "s|<DBSYNC_POSTGRES_HOST>|${DBSYNC_POSTGRES_HOST}|" \
-e "s|<DBSYNC_POSTGRES_PORT>|${DBSYNC_POSTGRES_PORT}|" \
-e "s|<SENTRY_DSN>|${SENTRY_DSN_BACKEND}|" \
-e "s|<SENTRY_ENV>|test|" \
/home/runner/work/govtool/govtool/scripts/govtool/config/templates/backend-config.json.tpl > /home/runner/work/govtool/govtool/scripts/govtool/config/target/backend-config.json
bash: line 1: DBSYNC_POSTGRES_HOST: unbound variable
make: *** [config.mk:85: /home/runner/work/govtool/govtool/scripts/govtool/config/target/backend-config.json] Error 1
```
- [related …
=> fix(#1624): fix unbound variable in resync cardano node workflow

CHANGELOG.md, govtool/frontend/src/components/organisms/DashboardCards/ListGovActionsDashboardCard.tsx
- change link to view governance action docs
- [related issue](https://github.com/IntersectMBO/govtool/issues/1131)
=> fix(#1131): change link to view governance action docs

CHANGELOG.md, govtool/backend/sql/get-network-metrics.sql, govtool/backend/src/VVA/API.hs, govtool/backend/src/VVA/API/Types.hs, govtool/backend/src/VVA/Network.hs, govtool/backend/src/VVA/Types.hs
- provide network name to network metrics endpoint
- [related issue](https://github.com/IntersectMBO/govtool/issues/1644)
=> feat(#1644): provide network name to network metrics endpoint

CHANGELOG.md, govtool/frontend/Dockerfile
- make all the frontend build arguments mandatory
- [related issue](https://github.com/IntersectMBO/govtool/issues/1642)
- [related issue](https://github.com/IntersectMBO/govtool/issues/1643)
(Still the Envs have to be set on the infrastructure)
=> chore: make all the frontend build arguments mandatory

CHANGELOG.md, govtool/frontend/src/components/organisms/HomeCards.tsx
- Change link to delegate voting power docs
- [related issue](https://github.com/IntersectMBO/govtool/issues/1654)
=> [#1654] Use consistent link for Learn more button on delegate card

CHANGELOG.md, govtool/frontend/src/i18n/locales/en.ts
- Fixed incorrect copy around vote tallies
- Fixed other minor spelling mistakes in copy
=> fix: frontend votes info copy and other minor spelling in copy

tests/govtool-frontend/playwright/lib/_mock/index.ts, tests/govtool-frontend/playwright/lib/helpers/metadata.ts, tests/govtool-frontend/playwright/lib/helpers/transaction.ts, tests/govtool-frontend/playwright/lib/services/kuberService.ts, tests/govtool-frontend/playwright/lib/types.ts, tests/govtool-frontend/playwright/tests/dRep.setup.ts
- Upload randomly generated metadata to metadata-govtool and obtain the URL and its actual hash instead of using a hardcoded anchor URL and dataHash during dRep registration with kuber api.
=> Bug Fix: Incorrect dRep anchor URL and dataHash on dRep registration

tests/govtool-frontend/playwright/lib/_mock/index.ts, tests/govtool-frontend/playwright/tests/6-miscellaneous/miscellaneous.loggedin.spec.ts
- Append a timestamp to a valid username to ensure uniqueness.
=> Ensure Username Uniqueness by Appending Timestamp

.github/workflows/build-and-deploy-staging.yml, .github/workflows/build-and-deploy-test.yml, CHANGELOG.md
- fix pdf not enabled in default deployments
=> fix: fix pdf not enabled in default deployments

tests/govtool-backend/test_cases/test_proposal.py
- Fix error log when proposal schema validation fails
=> Fix: typo  replace proposal to drepInfo

CHANGELOG.md, govtool/frontend/src/context/wallet.tsx
Draft because I don't have proper local setup to be able to test properly
We should use the newer type of stake key registration certificate
because the one we currently are using will be deprecated in a future ledger era.
=> change: to use new type of stake registration certificate

CHANGELOG.md, govtool/backend/sql/list-proposals.sql, govtool/backend/src/VVA/API.hs, govtool/backend/src/VVA/API/Types.hs, govtool/backend/src/VVA/Types.hs
- Add support for previous governance action data
- [related issue](https://github.com/IntersectMBO/govtool/issues/1600)
=> feat(#1600): add support for previous governance action data

govtool/frontend/src/i18n/locales/en.ts
- Fix incorrect abbreviation copy for CC votes
=> chore: adjust copy for cc votes

CHANGELOG.md, govtool/frontend/src/context/wallet.tsx, scripts/govtool/Makefile, scripts/govtool/custom-cardano-db-sync.Dockerfile, scripts/govtool/docker-compose.node+dbsync.yml
- bump infra to use cardano-db-sync@13.3.0.0
- [related issue](https://github.com/IntersectMBO/govtool/issues/1809)
=> chore(#1809): bump infra to use cardano-db-sync@13.3.0.0

CHANGELOG.md, govtool/frontend/src/components/organisms/DRepCard.tsx, govtool/frontend/src/components/organisms/DashboardCards/DelegateDashboardCard.tsx, govtool/frontend/src/components/organisms/EditDRepInfoSteps/EditDRepForm.tsx, govtool/frontend/src/components/organisms/EditDRepInfoSteps/EditDRepStorageInformation.tsx, govtool/frontend/src/components/organisms/RegisterAsDRepSteps/DRepStorageInformation.tsx, govtool/frontend/src/components/organisms/RegisterAsDRepSteps/RegisterAsDRepForm.tsx, govtool/frontend/src/consts/dRepActions/fields.ts, govtool/frontend/src/consts/dRepActions/jsonContext.ts, govtool/frontend/src/hooks/forms/useEditDRepInfoForm.ts, govtool/frontend/src/hooks/forms/useRegisterAsdRepForm.tsx, govtool/frontend/src/i18n/locales/en.ts, govtool/frontend/src/models/api.ts, govtool/frontend/src/models/metadataValidation.ts, govtool/frontend/src/pages/DRepDetails.tsx, govtool/frontend/src/utils/generateMetadataBody.ts, govtool/frontend/src/utils/isValidFormat.ts, govtool/frontend/src/utils/mapDtoToDrep.ts, govtool/frontend/src/utils/tests/dRep.test.ts
- Add support for CIP-119 on the frontend
- [related issue](https://github.com/IntersectMBO/govtool/issues/1760)
=> [#1760] add CIP-119 support on frontend

CHANGELOG.md, govtool/frontend/src/components/organisms/RegisterAsDRepSteps/RolesAndResponsibilities.tsx, govtool/frontend/src/context/wallet.tsx, govtool/frontend/src/pages/RegisterAsDirectVoter.tsx
- fix accessing DRep deposit from possibly empty epoch params
- [related issue](https://github.com/IntersectMBO/govtool/issues/1733)
=> fix(#1733): fix accessing drep deposit from possibly empty epoch params

CHANGELOG.md, govtool/frontend/src/components/molecules/DataMissingInfoBox.tsx, govtool/frontend/src/components/organisms/AutomatedVotingOptions.tsx, govtool/frontend/src/components/organisms/CreateGovernanceActionSteps/StoreDataInfo.tsx, govtool/frontend/src/components/organisms/DashboardCards/DRepDashboardCard.tsx, govtool/frontend/src/components/organisms/DashboardCards/DirectVoterDashboardCard.tsx, govtool/frontend/src/components/organisms/DashboardCards/ListGovActionsDashboardCard.tsx, govtool/frontend/src/components/organisms/DashboardCards/ProposeGovActionDashboardCard.tsx, govtool/frontend/src/components/organisms/EditDRepInfoSteps/EditDRepStoreDataInfo.tsx, govtool/frontend/src/components/organisms/Footer.tsx, govtool/frontend/src/components/organisms/HomeCards.tsx, govtool/frontend/src/components/organisms/RegisterAsDRepSteps/DRepStorageInformation.tsx, govtool/frontend/src/components/organisms/RegisterAsDRepSteps/DRepStoreDataInfo.tsx, govtool/frontend/src/components/organisms/RegisterAsDRepSteps/RolesAndResponsibilities.tsx, govtool/frontend/src/components/organisms/VoteContext/VoteContextTerms.tsx, govtool/frontend/src/consts/navItems.tsx, govtool/frontend/src/i18n/locales/en.ts
- update gitbook links
- [related issue](https://github.com/IntersectMBO/govtool/issues/1774)
=> fix(#1774): fix & update gitbook links

govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx
- Fix displaying duplicate hardfork initiation details
=> [#1600] hide hardfork initiation details outside details tab

govtool/backend/Dockerfile.base
- add postgresql@14 to the backend base dockerfile
=> fix: fix backend build providing postgresql@14 in the base Dockerfile

.github/workflows/merge.yaml, .github/workflows/pr.yaml
=> switch to tar images

CHANGELOG.md, govtool/frontend/src/components/organisms/RegisterAsDRepSteps/RegisterAsDRepForm.tsx
- Delete duplicate text on DRep registration form
- [related issue](https://github.com/IntersectMBO/govtool/issues/1847)
=> [#1847] delete duplicate text on DRep registration form

CHANGELOG.md, govtool/frontend/src/components/atoms/modal/ModalWrapper.tsx
- Fix invisible modal content on ios
- [related issue](https://github.com/IntersectMBO/govtool/issues/1842)
=> [#1842] fix invisible modal content on ios

CHANGELOG.md, govtool/backend/sql/list-proposals.sql, govtool/frontend/src/components/molecules/VotesSubmitted.tsx
- fix counting CC and SPO votes
Screenshot for the updated gov action from the issue:
@Ryun1 Does it look legit now? :thinking: 
- [related issue](https://github.com/IntersectMBO/govtool/issues/1838)
=> fix(#1838): fix counting CC and SPO votes

CHANGELOG.md, govtool/frontend/src/context/featureFlag.tsx
- fix voting on info actions in bootstrapping phase
- [related issue](https://github.com/IntersectMBO/govtool/issues/1876)
=> fix(#1876): fix voting on info actions in bootstrapping phase

CHANGELOG.md, govtool/frontend/src/consts/dRepActions/fields.ts, govtool/frontend/src/i18n/locales/en.ts
-  fix missing DRep name whitespace validation
- [related issue](https://github.com/IntersectMBO/govtool/issues/1873)
=> fix(#1873): fix missing DRep name whitespace validation

CHANGELOG.md, govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx, govtool/frontend/src/stories/GovernanceActionDetailsCard.stories.ts
- fix formatting governance action id
- [related issue](https://github.com/IntersectMBO/govtool/issues/1866)
=> fix(#1866): fix formatting governance action id

CHANGELOG.md, govtool/frontend/src/pages/DRepDetails.tsx
- add missing DRep Details test IDs
- [related issue](https://github.com/IntersectMBO/govtool/issues/1863)
=> fix(#1863): add missing DRep Details test IDs

CHANGELOG.md, govtool/frontend/src/hooks/forms/useEditDRepInfoForm.ts, govtool/frontend/src/hooks/forms/useRegisterAsdRepForm.tsx, govtool/frontend/src/utils/isValidFormat.ts
- make payment address validation optional
- [related issue](https://github.com/IntersectMBO/govtool/issues/1871)
=> fix(#1871): make payment address validation optional

CHANGELOG.md, govtool/frontend/src/components/molecules/GovernanceActionDetailsCardVotes.tsx, govtool/frontend/src/components/molecules/VoteActionForm.tsx, govtool/frontend/src/components/organisms/DashboardGovernanceActionDetails.tsx, govtool/frontend/src/components/organisms/GovernanceActionDetailsCard.tsx, govtool/frontend/src/hooks/forms/useVoteActionForm.tsx
- Fix runtime error when navigating to GA details from Voted on by me tab
- [related issue](https://github.com/IntersectMBO/govtool/issues/1910)
=> [#1910] fix error when navigating to GA details from Voted on by me tab

govtool/frontend/src/components/organisms/DashboardCards/DRepDashboardCard.tsx, govtool/frontend/src/context/governanceAction.test.tsx, govtool/frontend/src/context/governanceAction.tsx, govtool/frontend/src/hooks/forms/useCreateGovernanceActionForm.ts, govtool/frontend/src/hooks/forms/useEditDRepInfoForm.ts, govtool/frontend/src/hooks/forms/useRegisterAsdRepForm.tsx, govtool/frontend/src/hooks/forms/useVoteContextForm.tsx, govtool/frontend/src/i18n/locales/en.ts, govtool/metadata-validation/src/app.service.ts, govtool/metadata-validation/src/utils/validateCIP108body.ts
- Make response of the metadata restricted to be raw text.
- Enforce format of the stringified metadata to match the resulting content on the pre-validation step.
- [related issue](https://github.com/IntersectMBO/govtool/issues/1894)
=> fix(#1894): make response of the metadata restricted to be raw text

CHANGELOG.md, govtool/frontend/src/components/organisms/DashboardCards/ProposeGovActionDashboardCard.tsx
- Fix incorrect documentation link on proposal learn more button
- [related issue](https://github.com/IntersectMBO/govtool/issues/1877)
=> [#1877] fix: incorrect documentation link on proposal learn more button

CHANGELOG.md, govtool/backend/sql/get-votes.sql
- Fix getVotes sql to query time from vote tx instead of govAaction tx
- [related issue](https://github.com/IntersectMBO/govtool/issues/1925)
=> [#1925] query time from vote tx instead of gov action tx

CHANGELOG.md, govtool/frontend/src/models/metadataValidation.ts, govtool/frontend/src/utils/mapDtoToProposal.ts
- Fix runtime error in GA details with links by mapping references from validation service to format expected by FE
- [related issue](https://github.com/IntersectMBO/govtool/issues/1924)
=> [#1924] map references from validation service to format expected by FE

CHANGELOG.md, govtool/frontend/src/pages/DRepDirectoryContent.tsx
- make displaying own DRep in DRep directory available
- [related issue](https://github.com/IntersectMBO/govtool/issues/1934)
=> fix(#1934): make displaying own DRep in DRep directory available

CHANGELOG.md, govtool/frontend/src/hooks/forms/useRegisterAsdRepForm.tsx
- Fix saving the Do Not List checkbox value on DRep registration
- [related issue](https://github.com/IntersectMBO/govtool/issues/1940)
=> [#1940] add doNotList as accepted key on DRep registration

CHANGELOG.md, govtool/frontend/src/components/organisms/DRepCard.tsx, govtool/frontend/src/components/organisms/DRepDetailsCard.tsx, govtool/frontend/src/components/organisms/DRepDetailsCardHeader.tsx, govtool/frontend/src/i18n/locales/en.ts, govtool/frontend/src/pages/DRepDetails.tsx, govtool/frontend/src/pages/DRepDirectoryContent.tsx, govtool/frontend/src/stories/DRepDetailsCard.stories.ts
- Hide Delegate button in DRep list and details if user has already delegated to this DRep
- [related issue](https://github.com/IntersectMBO/govtool/issues/1982)
=> [#1982] hide Delegate button if already delegated to this DRep

CHANGELOG.md, govtool/frontend/src/i18n/locales/en.ts, govtool/frontend/src/stories/Step.stories.tsx
- Fix incorrect (ex. github) to (e.g. github)
- [related issue](https://github.com/IntersectMBO/govtool/issues/1748)
=> [#1748] Fix incorrect copy

CHANGELOG.md, govtool/frontend/src/i18n/locales/en.ts
- Change the direct voter registration message;
- fix incorrect deposit info
- generally improve clarity and distinction from DReps
=> [1976] New description for direct voter registration

CHANGELOG.md, scripts/govtool/Makefile, scripts/govtool/custom-cardano-db-sync.Dockerfile, scripts/govtool/docker-compose.node+dbsync.yml
The purpose of these changes is to upgrade the Cardano DB Sync version from 13.5.0.1 to 13.5.0.2 across various parts of the project. This upgrade is a proactive step to align with the latest node hotfix 9.1.1, ensuring that the app remains healthy and performs optimally after the hotfix is applied. The updates have been specifically made to address Issue 1945, underscoring the project's commitment to staying current with the latest version enhancements and bug fixes.
The outcome of these changes involves modifications to several files including `CHANGELOG.md`, `scripts/govtool/Makefile`, `scripts/govtool/custom-cardano-db-sync.Dockerfile`, and `scripts/govtool/docker-compose.node+dbsync.yml`. These changes ensure compatibility with the new features and fixes in version 13.5.0.2, …
=> [#1945] 💡 Bump DBSync versions to 13.5.0.2

govtool/backend/src/VVA/API.hs, govtool/backend/src/VVA/API/Types.hs, govtool/backend/vva-be.cabal, govtool/frontend/src/components/molecules/DataActionsBar.tsx, govtool/frontend/src/components/molecules/OrderActionsChip.tsx, govtool/frontend/src/components/organisms/DRepCard.tsx, govtool/frontend/src/consts/dRepDirectory/sorting.ts, govtool/frontend/src/context/dataActionsBar.tsx, govtool/frontend/src/models/api.ts, govtool/frontend/src/pages/DRepDirectoryContent.tsx, govtool/frontend/src/stories/ActionsBar.stories.ts
- Add default sorting as default sorting for DRep list
- [related issue](https://github.com/IntersectMBO/govtool/issues/2013)
=> Feat/2013 randomize DRep list

CHANGELOG.md, govtool/frontend/src/context/wallet.tsx
- Removed explicit UTxO output which caused poor selection
- [related issue](https://github.com/IntersectMBO/govtool/issues/2059)
=> [2059] Fix poor UTxO management

tests/govtool-frontend/playwright/tests/3-drep-registration/dRepRegistration.dRep.spec.ts
- Add assertion to wait for info governance actions loaded properly before assertion the voting behaviour.
- Update test 3A title to match the test behaviour
=> Fix test 3A

CHANGELOG.md, govtool/frontend/src/components/molecules/VotesSubmitted.tsx
- Add missing testIds for submitted votes
- [related issue](https://github.com/IntersectMBO/govtool/issues/1875)
=> [#1875] add missing testIds for submitted votes

tests/govtool-frontend/playwright/lib/pages/dRepDirectoryPage.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegation.spec.ts
- Fix test 2K_2 by adding status ranking for validation
- Add test 2K_3 to sort dRep randomly
=> Add random dRep test and fix test 2K_2 due to status

tests/govtool-frontend/playwright/tests/6-miscellaneous/miscellaneous.spec.ts
- Update the assertion of network name test to align with latest update
=> fix: update network name assertion in test 6T to improve accuracy

CHANGELOG.md, govtool/frontend/src/utils/jsonUtils.ts, govtool/frontend/src/utils/tests/jsonUtils.test.ts
- provide a workaround for downloading the metadata file on iOS.
Reason for the workaround is the limitation on iOS.
Safari browser on iOS blocks programmatically generated file downloads for security reasons.
Because of that, if the interaction is triggered on mobile safari, I made that open a new tab with the json content - allowing user to manually download this data and meet the security requirements on iOS.
- [related issue](https://github.com/IntersectMBO/govtool/issues/1989)
=> fix(#1989): workaround for downloading metadata on iOS Safari

CHANGELOG.md, govtool/frontend/src/hooks/queries/useGetDRepListQuery.ts, govtool/frontend/src/pages/DRepDirectoryContent.tsx
- Fix infinite loading in DRep Directory
- [related issue](https://github.com/IntersectMBO/govtool/issues/2090)
=> [#2090] fix infinite loading in DRep Directory

scripts/govtool/Makefile, scripts/govtool/docker-compose.node+dbsync.yml
The purpose of these changes is to update the Cardano Node version on the sanchonet environment as part of the Proposal Pillar. This involves upgrading the cardano-node from version 9.1.1 to the newer version 9.2.1. The update caters to the requirement specified in the user story to ensure that sanchonet is compatible with the latest releases and benefits from any improvements or bug fixes contained within this specific version.
The outcome of these changes is that the Makefile and docker-compose.node+dbsync.yml configurations have been updated to reflect the use of cardano-node version 9.2.1. This brings the sanchonet environment in line with the latest updates, potentially enhancing functionality or performance, and addressing any issues present in the previous version. This alignment …
=> [#2118] 💡 Bump cardano-node on sanchonet to 9.2.1

govtool/backend/Dockerfile.base
The purpose of this change is to resolve the deployment failure of the GovTool backend application caused by a missing PostgreSQL repository for the previously used Debian Buster base image. The deployment was encountering a 404 error, indicating that the required PostgreSQL repository 'buster-pgdg' could not be found, possibly due to deprecation or an incorrect URL. To mitigate this issue, the base image in the deployment setup has been switched from Debian Buster to Ubuntu 24.04. This change was necessary because the Ubuntu 24.04 environment maintains compatibility with the required PostgreSQL repository, ensuring that the specific version of PostgreSQL and its development dependencies can be successfully installed without encountering repository-related errors.
As a result of updating …
=> [#2120] Deployment failure of GovTool backend due to missing PostgreSQL repository

CHANGELOG.md, govtool/backend/sql/list-proposals.sql
- fix counting governance action expiration
- [related issue](https://github.com/IntersectMBO/govtool/issues/2125)
=> fix(#2125): fix counting governance action expiration

tests/govtool-backend/requirements.txt, tests/govtool-frontend/yarn.lock, tests/load-testing/pom.xml, tests/test-metadata-api/yarn.lock, tests/test-metrics-api/yarn.lock
- Update dependencies in govtool tests to address security vulnerabilities identified by Dependabot.
=> Update govtool tests dependencies

tests/govtool-frontend/playwright/lib/pages/governanceActionDetailsPage.ts
- Update cc committee yes votes test id
=> fix: correct testId for CC committee yes votes

CHANGELOG.md, govtool/frontend/src/components/organisms/GovernanceActionsToVote.tsx
- Fix unwanted horizontal page scroll on Governance Actions page
- [related issue](https://github.com/IntersectMBO/govtool/issues/1897)
=> [#1897] fix unwanted horizontal page scroll on Governance Actions page

CHANGELOG.md, govtool/frontend/src/components/atoms/FormErrorMessage.tsx, govtool/frontend/src/components/atoms/FormHelpfulText.tsx, govtool/frontend/src/components/atoms/types.ts, govtool/frontend/src/components/molecules/DRepDataForm.tsx, govtool/frontend/src/components/molecules/Field/Input.tsx, govtool/frontend/src/components/molecules/Field/types.ts
- Fix duplicate testIds for reference errors and hints in DRep metadata form
=> [#1965] fix duplicate testIds for reference errors and hints

tests/govtool-backend/lib/kuber_api.py, tests/govtool-backend/test_cases/test_proposal.py
- Add kuber service to get genesis-param
- Add epoch boundary test to validate expiry epoch and date
=> Backend epoch boundary test

CHANGELOG.md, scripts/govtool/Makefile, scripts/govtool/docker-compose.node+dbsync.yml
- Change bump to use Node 10.0.0-pre
=> chore: bump Cardano node to 10.0.0-pre

tests/govtool-frontend/playwright/lib/helpers/transaction.ts, tests/govtool-frontend/playwright/lib/services/kuberService.ts
- use logger import from playwright helper instead of cypress
=> fix: use logger import from helper instead of cypress logger

CHANGELOG.md, govtool/backend/sql/get-current-epoch-params.sql, govtool/backend/sql/list-proposals.sql, govtool/frontend/src/components/atoms/VotePill.tsx, govtool/frontend/src/components/molecules/DataMissingHeader.tsx, govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx, govtool/frontend/src/main.tsx, govtool/frontend/src/theme.ts, govtool/frontend/src/utils/filterOutNullParams.ts, govtool/frontend/src/utils/filterUpdatableProtocolParams.ts, govtool/frontend/src/utils/index.ts, govtool/frontend/src/utils/mapArrayToObjectByKeys.ts
- protocol parameter change ga is not displayed correctly
- [related issue](https://github.com/IntersectMBO/govtool/issues/2191)
=> fix(#2191): protocol parameter change ga is not displayed correctly

tests/govtool-frontend/playwright/lib/_mock/index.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/dRepRegistration.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/editDRep.dRep.spec.ts, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.loggedin.spec.ts
- Add validation to restrict URLs containing more than 128 words, applicable only for unsupported URLs.
- Update validation assertions for invalid metadata anchor to enforce the 128-word limit.
=> Reject metadata anchor with a limit of 128 words.

tests/govtool-frontend/playwright/lib/pages/governanceActionDetailsPage.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts
- Update test id of vote context metadata anchor URL and metadata download
- Add test 4N Should accept valid metadata anchor on vote context
- Add test 4O Should reject invalid metadata anchor on vote context
=> test for vote context anchor validation

CHANGELOG.md, govtool/frontend/src/i18n/locales/en.ts
- Change copy for no DRep found via directory
=> change: no DRep found copy text

tests/govtool-frontend/playwright/lib/forms/dRepForm.ts
- Update dRep form references url and link error testId
=> chore: update dRep form references url and link error testId

govtool/backend/src/VVA/DRep.hs
- handle no results on get votes query
=> fix: handle no results on get votes query

CHANGELOG.md, govtool/frontend/src/context/dataActionsBar.tsx, govtool/frontend/src/hooks/queries/useGetDRepListQuery.ts
- fix infinite DRep list loading
- [related issue](https://github.com/IntersectMBO/govtool/issues/2285)
=> fix(#2285): fix infinite DRep list loading

tests/govtool-frontend/playwright/tests/8-proposal-discussion/proposalDiscussion.loggedin.spec.ts
- Add test to navigation edit proposal page on metadata anchor url error modal 'go to data edit screen' button click
=> test: proposal data edit screen navigation

tests/govtool-frontend/playwright/lib/_mock/index.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/dRepRegistration.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/editDRep.dRep.spec.ts
- Update dRep for data validation test to support dRep name with space
=> tests/support space on dRep name

CHANGELOG.md, govtool/frontend/src/components/molecules/GovernanceActionCard.tsx, govtool/frontend/src/components/molecules/GovernanceVotedOnCard.tsx, govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx, govtool/frontend/src/i18n/locales/en.json, govtool/frontend/src/services/requests/getProposal.ts, govtool/frontend/src/services/requests/getProposals.ts, govtool/frontend/src/stories/GovernanceAction.stories.ts, govtool/frontend/src/stories/GovernanceActionDetailsCard.stories.ts, govtool/frontend/src/utils/cip129identifier.ts, govtool/frontend/src/utils/getGovActionId.ts, govtool/frontend/src/utils/index.ts, govtool/frontend/src/utils/tests/cip129identifier.test.ts
- add support for CIP-129 governance identifiers
- [related issue](https://github.com/IntersectMBO/govtool/issues/2183)
=> feat(#2183): add support for CIP-129 governance identifiers

CHANGELOG.md, govtool/frontend/src/components/molecules/VotesSubmitted.tsx, govtool/frontend/src/utils/adaFormat.ts, govtool/frontend/src/utils/tests/adaFormat.test.ts
- change displaying ada to en-US format in votes 
- [related issue](https://github.com/IntersectMBO/govtool/issues/2305)
=> fix(#2305): change displaying ada to en-US format in votes

CHANGELOG.md, govtool/frontend/src/components/molecules/GovernanceActionDetailsCardLinks.tsx, govtool/frontend/src/models/api.ts, govtool/frontend/src/stories/GovernanceActionDetailsCard.stories.ts, govtool/frontend/src/utils/mapDtoToProposal.ts
- add labels to supporting links in governance action details
- [related issue](https://github.com/IntersectMBO/govtool/issues/2070)
=> feat(#2070): add labels to supporting links in governance action details

CHANGELOG.md, scripts/govtool/Makefile, scripts/govtool/docker-compose.node+dbsync.yml
- Bump Node version to 10.1.0-pre
- Bump DB-Sync version to 13.6.0.0
=> chore: bump node version to 10.1.0-pre

.github/workflows/add-issue-to-project.yml, CHANGELOG.md
- Overhaul action to use github personal access token and premade workflow template
- [related issue](https://github.com/IntersectMBO/govtool/issues/2277)
=> [2277] fix: remove unneeded login step on workflow action

.github/workflows/add-issue-to-project.yml
- fix: incorrect org labelling for action
=> fix: incorrect org labelling for action

CHANGELOG.md, govtool/backend/sql/get-voting-power.sql
- make calculation of the DRep voting power on the backend
- [related issue](https://github.com/IntersectMBO/govtool/issues/1960)
=> fix(#1960): make calculation of the DRep voting power on the backend

CHANGELOG.md, scripts/govtool/Makefile, scripts/govtool/docker-compose.node+dbsync.yml
[SanchoNet]
- Bump cardano-node to v10.1.2
- Bump cardano-db-sync to v13.6.0.1
- [related issue](https://github.com/IntersectMBO/govtool/issues/2310)
=> chore(#2310): bump cardano node (10.1.2) and cardano-db-sync (13.6.0.1)

flake.lock, flake.nix, govtool/backend/default.nix, govtool/frontend/default.nix, govtool/frontend/yarn.lock
- Fixes nix builds for `frontend` and `backend` components
- Required node_nixpkgs pin update and regeneration of yarn.lock
-  Fixes impure nix builds required by some deployers by adding an optional `returnShellEnv` bool to the `backend` package
=> Nix build fixes

gov-action-loader/backend/app/transaction.py
- Change
- Anchor for bulk gov-actions: 
- url: https://metadata-govtool.cardanoapi.io/data/gov-action-loader
- hash: `bcb2fadedbe928519ff000051d8e78ffcabadba0f92b91334cee3e8786491462`
- This was done so that goveranace actions can be viewed as having correctly formatted data
- Example: [a003201b997db0777751c1f8f3f1d5ca761248ce5fd683e886a647dca53c2039#0](https://preview.gov.tools/governance_actions/a003201b997db0777751c1f8f3f1d5ca761248ce5fd683e886a647dca53c2039#0)
- Stake address for update committee and treasury withdrawal
- change stake address to `e02fe0d8c1b1c600249e8b9663e18790425e9589ac17cb5ee952d54bee`
- This had to be done since stake addresses were randomly generated and not yet initialized, which was resulting in error while submitting the transaction
=> Use valid anchor url, hash and return address in bulk loader

CHANGELOG.md, govtool/frontend/src/utils/adaFormat.ts, govtool/frontend/src/utils/tests/adaFormat.test.ts
- fix ada quantities format
- [related issue](https://github.com/IntersectMBO/govtool/issues/2372)
=> fix(#2372): fix ada quantities format

CHANGELOG.md, govtool/frontend/src/hooks/index.ts, govtool/frontend/src/hooks/usePrevious.test.ts, govtool/frontend/src/hooks/usePrevious.ts, govtool/frontend/src/pages/DRepDirectoryContent.tsx
- fix inconsistent display of pending delegation DRep card
- add usePrevious hook
- [related issue](https://github.com/IntersectMBO/govtool/issues/2332)
=> fix(#2332): fix inconsisten display of pending delegation DRep card

tests/govtool-frontend/playwright/tests/2-delegation/delegation.drep.spec.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/dRepRegistration.dRep.spec.ts
- Update test case **2J** to include the ability to search dReps by name.
- Assert that the dRep ID card is displayed before clicking the "View Your dRep Details" button to ensure the button's action reflects its expected behavior.
=> test: add ability to search dReps by name

tests/govtool-frontend/playwright/lib/constants/index.ts, tests/govtool-frontend/playwright/lib/helpers/adaFormat.ts, tests/govtool-frontend/playwright/lib/helpers/featureFlag.ts, tests/govtool-frontend/playwright/lib/types.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.spec.ts
- Update governance action total vote visibility assertion according to the protocol version for dRep and wallet disconnect user
=> test: update governance action total vote visibility assertion according to the protocol version

CHANGELOG.md, govtool/backend/sql/get-drep-info.sql
- fix wrong status of past DRep information
=> fix: fix wrong status of past DRep information

tests/govtool-frontend/playwright/lib/helpers/cborEncodeDecode.ts, tests/govtool-frontend/playwright/lib/helpers/computeTxHash.ts, tests/govtool-frontend/playwright/lib/helpers/encodeDecode.ts, tests/govtool-frontend/playwright/lib/services/kuberService.ts, tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.dRep.spec.ts
- Rename file cborEncodeDecode to encodeDecode
- Add function to encode CIP129 Identifier
- Add assertion of CIP129 govActionId and default govActionId on govAction details page
=> Assert CIP129 and govActionId on governance action details page

CHANGELOG.md, govtool/backend/sql/get-voting-power.sql
- fix fetching voting power for newly registered DRep
- [related issue](https://github.com/IntersectMBO/govtool/issues/2407)
=> fix(#2407): fix fetching voting power for newly registered DRep

.github/workflows/test_backend.yml, tests/govtool-backend/.env.example, tests/govtool-backend/config.py, tests/govtool-backend/lib/faucet_api.py, tests/govtool-backend/lib/kuber_api.py, tests/govtool-backend/models/TestData.py
- update proposal.details type 
- Add additional types on proposal
- Add missing kuber api key and network on workflow env
- use faucet api key based on network
=> Update proposal.details type and add additional proposal field types

.github/workflows/test_integration_playwright.yml, tests/govtool-frontend/playwright/.env.example, tests/govtool-frontend/playwright/lib/constants/environments.ts
- Remove unwanted env and get faucet and blockfrost api keys based on network
=> Remove unwanted env and get faucet and blockfrost api keys based on network

CHANGELOG.md, govtool/frontend/src/utils/jsonUtils.ts
- fix unnecessary node remove in metadata actions
- [related issue](https://github.com/IntersectMBO/govtool/issues/2398)
=> fix(#2398): fix unnecessary node remove in metadata actions

govtool/backend/app/Main.hs
The purpose of this change is to optimize the initialization of the Sentry service in the application. Previously, the Sentry service was initialized whenever an exception occurred, which could lead to resource inefficiencies and potential performance bottlenecks. By shifting the initialization to the start of the app lifecycle, rather than initializing repeatedly during exceptions, the application ensures that the Sentry service is consistently ready to handle exceptions right from the start and throughout the entire operation of the application. This adjustment aims to align with the user story's goal of improving exception handling efficiency through centralized initialization.
The outcome of this change is an improvement in the application's performance and resource management. By …
=> [#2450] Initialize Sentry service at application start

CHANGELOG.md, govtool/frontend/src/hooks/useDelegateToDrep.ts
- Fix app crash on delegation
- [related issue](https://github.com/IntersectMBO/govtool/issues/2408)
=> fix(#2408): fix app crash on delegation

CHANGELOG.md, scripts/govtool/Makefile, scripts/govtool/docker-compose.node+dbsync.yml
- bump cardano db-sync to 13.6.0.4
- [related issue](https://github.com/IntersectMBO/govtool/issues/2411)
=> chore(#2411): bump cardano db-sync to 13.6.0.4

CHANGELOG.md, README.md, docs/architecture/README.md, govtool/frontend/src/components/molecules/DataMissingInfoBox.tsx, govtool/frontend/src/components/organisms/AutomatedVotingOptions.tsx, govtool/frontend/src/components/organisms/CreateGovernanceActionSteps/StorageInformation.tsx, govtool/frontend/src/components/organisms/CreateGovernanceActionSteps/StoreDataInfo.tsx, govtool/frontend/src/components/organisms/DashboardCards/DRepDashboardCard.tsx, govtool/frontend/src/components/organisms/DashboardCards/DelegateDashboardCard.tsx, govtool/frontend/src/components/organisms/DashboardCards/DirectVoterDashboardCard.tsx, govtool/frontend/src/components/organisms/DashboardCards/ListGovActionsDashboardCard.tsx, govtool/frontend/src/components/organisms/DashboardCards/ProposeGovActionDashboardCard.tsx, govtool/frontend/src/components/organisms/DrawerMobile.tsx, govtool/frontend/src/components/organisms/EditDRepInfoSteps/EditDRepStorageInformation.tsx, govtool/frontend/src/components/organisms/EditDRepInfoSteps/EditDRepStoreDataInfo.tsx, govtool/frontend/src/components/organisms/Footer.tsx, govtool/frontend/src/components/organisms/HomeCards.tsx, govtool/frontend/src/components/organisms/Modal/ChooseWalletModal.tsx, govtool/frontend/src/components/organisms/RegisterAsDRepSteps/DRepStorageInformation.tsx, govtool/frontend/src/components/organisms/RegisterAsDRepSteps/DRepStoreDataInfo.tsx, govtool/frontend/src/components/organisms/RegisterAsDRepSteps/RolesAndResponsibilities.tsx, govtool/frontend/src/components/organisms/TopBanners.tsx, govtool/frontend/src/components/organisms/VoteContext/VoteContextStoringInformation.tsx, govtool/frontend/src/components/organisms/VoteContext/VoteContextTerms.tsx, govtool/frontend/src/consts/links.ts, govtool/frontend/src/consts/navItems.tsx
- fix broken guides links
- [related issue](https://github.com/IntersectMBO/govtool/issues/2417)
=> fix(#2417): fix broken guides links

tests/govtool-frontend/playwright/lib/helpers/featureFlag.ts, tests/govtool-frontend/playwright/lib/pages/governanceActionsPage.ts, tests/govtool-frontend/playwright/lib/types.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/dRepRegistration.dRep.spec.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.spec.ts, tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.dRep.spec.ts, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.loggedin.spec.ts
- Navigate to first dRep vote eligible governance action instead of any governance action on full governance action to fix dRep vote dependent test
- Parallize the bootstrap dRep vote test and improve the visibility checks for proper assertion
- Fix governance action type typo
- Add "vote-tab" assert to wait until the proposal is not visible
=> Bugfix/governance dRep vote dependent test

CHANGELOG.md, govtool/frontend/src/context/wallet.tsx
- fix double signing of transaction
- [related issue](https://github.com/IntersectMBO/govtool/issues/2478)
=> fix(#2478): fix double signing of transaction

tests/govtool-frontend/playwright/lib/types.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts, tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.dRep.spec.ts
- Use only bootstrap goverance actions to check dRep vote dependent test on bootstrap phase
=> Use only bootstrap goverance actions to check dRep vote dependent test on bootstrap phase

tests/govtool-frontend/playwright/lib/pages/proposalSubmissionPage.ts, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.loggedin.spec.ts
- Update testId of receiving address and amount Input and error message 
- Add assertion on valid proposal form to test the add withdrawal address button visibility
=> Update Test IDs and Validate Add Withdrawal Address Button Visibility in Proposal Form

CHANGELOG.md, govtool/frontend/src/context/wallet.tsx
- add registration cert when stake key is not registered
- [related issue](https://github.com/IntersectMBO/govtool/issues/2490)
=> fix(#2490): add registration cert when stake key is not registered

tests/govtool-frontend/playwright/lib/pages/proposalSubmissionPage.ts, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.loggedin.spec.ts
- Add extra assertion on save proposal as a draft (save treasury proposal as a draft and validate the input value field of saved the draft)
- Refactor proposal info content and update test Ids of receiving address content and amount content
=> Proposal Draft Input Validation and Content Test Refactor

CHANGELOG.md, govtool/backend/src/VVA/API/Types.hs, govtool/backend/src/VVA/Proposal.hs, govtool/backend/src/VVA/Types.hs
- fix mzero parsing error on /proposal/list
- [related issue](https://github.com/IntersectMBO/govtool/issues/2446)
=> fix(#2446): fix mzero parsing error on /proposal/list

CHANGELOG.md, govtool/frontend/src/components/organisms/VoteContext/VoteContextStoringInformation.tsx
- fix missing validation for url length
- [related issue](https://github.com/IntersectMBO/govtool/issues/2044)
=> fix(#2044): fix missing validation for url length

tests/govtool-frontend/playwright/lib/fixtures/proposal.ts, tests/govtool-frontend/playwright/lib/pages/proposalDiscussionPage.ts, tests/govtool-frontend/playwright/lib/pages/proposalSubmissionPage.ts, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.ga.spec.ts
- Use wallet stake address while creating proposal instead of random address
- remove unused create proposal function
=> Fix the treasury proposal submission test by using the same wallet's reward address

CHANGELOG.md, govtool/frontend/src/pages/DRepDirectoryContent.tsx, govtool/frontend/src/utils/index.ts, govtool/frontend/src/utils/mapDtoToDrep.ts, govtool/frontend/src/utils/tests/uniqBy.test.ts, govtool/frontend/src/utils/uniqBy.ts
- handle errors on fetching drep images
- [related issue](https://github.com/IntersectMBO/govtool/issues/2546)
=> fix(#2546): handle errors on fetching drep images

.github/workflows/test_integration_playwright.yml, tests/govtool-frontend/playwright/lib/constants/environments.ts, tests/govtool-frontend/playwright/lib/fixtures/loadExtension.ts, tests/govtool-frontend/playwright/lib/helpers/auth.ts, tests/govtool-frontend/playwright/lib/helpers/cardano.ts, tests/govtool-frontend/playwright/lib/helpers/dRep.ts, tests/govtool-frontend/playwright/lib/pages/dRepDirectoryPage.ts, tests/govtool-frontend/playwright/lib/pages/proposalDiscussionPage.ts, tests/govtool-frontend/playwright/lib/pages/proposalSubmissionPage.ts, tests/govtool-frontend/playwright/tests/1-wallet-connect/walletConnect.spec.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegation.drep.spec.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegation.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegation.spec.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegationFunctionality.delegation.spec.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/dRepRegistration.dRep.spec.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/editDRep.dRep.spec.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.dRep.spec.ts, tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.spec.ts, tests/govtool-frontend/playwright/tests/6-miscellaneous/miscellaneous.dRep.spec.ts, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.ga.spec.ts, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/8-proposal-discussion/proposalDiscussion.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/dRep.setup.ts, tests/govtool-frontend/playwright/tests/dRep.teardown.ts, tests/govtool-frontend/playwright/tests/delegation.teardown.ts, tests/govtool-frontend/playwright/tests/faucet.setup.ts, tests/govtool-frontend/playwright/tests/faucet.teardown.ts, tests/govtool-frontend/playwright/tests/wallet.bootstrap.ts
- Separate ADA-independent tests into a different file for better organization
- Skipped ADA-spending tests and added Allure descriptions for improved reporting.
- Configured networkId to dynamically switch and use a mainnet wallet for mainnet tests.
- Modified test 1D to validate across different networks instead of being mainnet-specific.
- Implemented a workflow dispatch mechanism to trigger Playwright automated tests on gov.tools.
- Added logic to clean up proposals created during tests to avoid clutter and maintain test integrity.
- [related issue](https://github.com/cardanoapi/govtool-test-reports/issues/8)
=> Refactor test suite: Automated Testing Strategy for Mainnet with ADA-Free Scenarios

govtool/frontend/Dockerfile, govtool/frontend/Dockerfile.qovery
This solution is temporary as we shouldn't exceed the default heap memory limit.
- increase the heap memory limit
- [related issue](https://github.com/IntersectMBO/govtool/issues/2553)
=> fix: increase heap memory limit

CHANGELOG.md, govtool/frontend/src/components/molecules/DRepDataForm.tsx, govtool/frontend/src/components/organisms/EditDRepInfoSteps/EditDRepForm.tsx, govtool/frontend/src/components/organisms/RegisterAsDRepSteps/RegisterAsDRepForm.tsx
- fix DRep link and description validation
- [related issue](https://github.com/IntersectMBO/govtool/issues/2403)
=> fix(#2403): fix DRep link and description validation

CHANGELOG.md, govtool/backend/sql/get-stake-key-voting-power.sql, govtool/backend/sql/get-voting-power.sql
- revert fetching the voting power from drep_distr table
- add rewards to ada holder voting power
=> fix: drep and ada holder voting power adjustments

govtool/frontend/storybook.Dockerfile
This solution is temporary as we shouldn't exceed the default heap memory limit.
- increase the heap memory limit to 4GB in the storybook 
- [related issue](https://github.com/IntersectMBO/govtool/issues/2553)
=> Increase Node.js memory limit to 4GB in storybook dockerfile

tests/govtool-frontend/playwright/lib/helpers/featureFlag.ts, tests/govtool-frontend/playwright/lib/pages/governanceActionsPage.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts, tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.dRep.spec.ts
**Note: This PR is ready to be merged once [Issue #2527](https://github.com/IntersectMBO/govtool/issues/2527) is resolved.**
- Removed unnecessary "view first dRep vote enabled" function
- Enabled vote display for all governance actions in full governance.  
- Removed restrictions and ensured all governance actions are checked for dRep-dependent tests.
- [related issue](https://github.com/IntersectMBO/govtool/issues/2527)
=> Enable and Display dRep Voting for All Governance Actions in Testing

govtool/frontend/src/components/organisms/Footer.tsx, govtool/frontend/src/i18n/locales/en.json
- fix failed storybook footer test
=> fix: fix failed storybook footer test

CHANGELOG.md, govtool/backend/sql/list-dreps.sql
- Introduced changes to list-dreps SQL, including the epoch from the newest vote, making the DRep activity also depend on the recent DRep action and not only on the registrations or updates.
=> fix: wrong drep activity conditions

CHANGELOG.md, govtool/metadata-validation/src/app.service.ts
-  fetching metadata from ipfs.io gateway
* ipfs.io appears to block requests from bots. As a result, the GovTool metadata validation service was blocked because it used the default axios user-agent.
=> fix: fetching metadata from ipfs.io gateway

CHANGELOG.md, govtool/backend/sql/get-network-metrics.sql, govtool/backend/sql/list-proposals.sql, govtool/backend/src/VVA/API.hs, govtool/backend/src/VVA/API/Types.hs, govtool/backend/src/VVA/Network.hs, govtool/backend/src/VVA/Types.hs, govtool/frontend/src/components/molecules/VotesSubmitted.tsx, govtool/frontend/src/models/api.ts
- Fix wrong SPO vote totals
- Add total stake controlled by SPOs to network metrics
- Fix wrong DRep total stake by filtering the epoch
- Fix DRep and CC votes percentage on votes submitted section
- [related issue](https://github.com/IntersectMBO/govtool/issues/2609)
=> fix(#2609): fix wrong SPO vote totals

tests/govtool-frontend/playwright/lib/helpers/dRep.ts, tests/govtool-frontend/playwright/lib/pages/dRepDirectoryPage.ts, tests/govtool-frontend/playwright/lib/types.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegation.spec.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.loggedin.spec.ts
- Check both CIP129 and CIP105 dRep on search dRep test
- Update governance action search to use IDs instead of titles and validate using IDs, as some governance action might be data not verifiable
- Add CIP129 DRep conversion service to convert dRep hash to CIP129 based on script
=> Improve dRep Search Test and Governance Action Validation Using IDs

CHANGELOG.md, govtool/frontend/src/context/dataActionsBar.tsx
- trim whitespace from search input
- [related issue](https://github.com/IntersectMBO/govtool/issues/2472)
=> fix(#2472): trim whitespace from search input

CHANGELOG.md, govtool/frontend/src/components/organisms/DRepCard.tsx, govtool/frontend/src/components/organisms/DRepDetailsCard.tsx
- allow delegation to inactive DReps
- [related issue](https://github.com/IntersectMBO/govtool/issues/2589)
=> feat(#2589): allow delegation to inactive DReps

CHANGELOG.md, govtool/backend/sql/get-stake-key-voting-power.sql
- fix stake key voting power calculation
- [related issue](https://github.com/IntersectMBO/govtool/issues/2653)
=> fix(#2653): stake key voting power calculation

CHANGELOG.md, govtool/frontend/src/utils/testIdFromLabel.ts
- Fix usage of trim on missing label
- [related issue](https://github.com/IntersectMBO/govtool/issues/2669)
=> fix: usage of trim on missing label

govtool/backend/sql/list-dreps.sql
- Cleanup drep list sql
- Wrap whole data within CTE for the matter of moving the pagination into the SQL
- Remove duplicated joins
- Fix fetching latest existing voting anchor
- [related issue](https://github.com/IntersectMBO/govtool/issues/2671)
=> fix(#2671): searching for drep off_chain data

CHANGELOG.md, govtool/frontend/src/components/molecules/DataMissingHeader.tsx, govtool/frontend/src/components/organisms/DRepDetailsCardHeader.tsx
- Previously `share DRep` button was visible only for our own registered DRep, this PR introduces this button for every DRep detail page
- [related issue](https://github.com/IntersectMBO/govtool/issues/2686)
=> feat(#2686): add share button to every DRep

CHANGELOG.md, govtool/frontend/src/hooks/forms/useRegisterAsdRepForm.tsx
- remove logging to sentry on failed drep registration tx
- [related issue](https://github.com/IntersectMBO/govtool/issues/2681)
=> chore(#2681): remove logging to sentry on failed drep registration tx

CHANGELOG.md, govtool/frontend/src/hooks/useDelegateToDrep.ts
- remove logging to sentry on failed delegation
- [related issue](https://github.com/IntersectMBO/govtool/issues/2682)
=> chore(#2682): remove logging to sentry on failed delegation

CHANGELOG.md, govtool/frontend/src/components/molecules/GovernanceActionCardElement.tsx, govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx, govtool/frontend/src/i18n/locales/en.json, govtool/frontend/src/stories/GovernanceActionDetailsCard.stories.ts
- show metadata anchor in governance action details
- [related issue](https://github.com/IntersectMBO/govtool/issues/2178)
=> feat(#2178): show metadata anchor in governance action details

CHANGELOG.md, govtool/backend/src/VVA/DRep.hs
- handle unexpected drep-info query result
- [related issue](https://github.com/IntersectMBO/govtool/issues/2676)
=> fix(#2676): handle unexpected drep-info query result

CHANGELOG.md, govtool/frontend/src/utils/openInNewTab.ts
- fix opening ipfs links
- [related issue](https://github.com/IntersectMBO/govtool/issues/2711)
=> fix(#2711): fix opening ipfs links

CHANGELOG.md, govtool/backend/src/VVA/AdaHolder.hs
- add exception handler on voting power query execution
- [related issue](https://github.com/IntersectMBO/govtool/issues/2757)
=> chore(#2757): add exception handler on voting power query execution

.github/workflows/test_backend.yml, .github/workflows/test_integration_playwright.yml
- Update workflow triggers for backend and integration tests to depend on the test stack deployment.
- update test workflow to run only on test stack deployment success
- [related issue](https://github.com/intersectMBO/govtool/issues/2775)
=> Update deployment order

CHANGELOG.md, govtool/frontend/src/pages/DRepDirectoryContent.tsx, govtool/frontend/src/utils/index.ts, govtool/frontend/src/utils/parseBoolean.ts, govtool/frontend/src/utils/tests/parseBoolean.test.ts, govtool/frontend/yarn.lock
- displaying DReps with doNotList as string
=> fix: displaying DReps with doNotList as string

tests/govtool-frontend/playwright/generate_wallets.ts, tests/govtool-frontend/playwright/lib/helpers/dRep.ts, tests/govtool-frontend/playwright/lib/helpers/metadata.ts, tests/govtool-frontend/playwright/lib/pages/governanceActionsPage.ts, tests/govtool-frontend/playwright/lib/pages/proposalSubmissionPage.ts, tests/govtool-frontend/playwright/lib/types.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegation.drep.spec.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegationFunctionality.delegation.spec.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/dRepRegistration.dRep.spec.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/dRepRegistration.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/editDRep.dRep.spec.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts, tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.dRep.spec.ts, tests/govtool-frontend/playwright/tests/6-miscellaneous/miscellaneous.spec.ts, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.loggedin.spec.ts
- Update the fetch logic for the first dRep filter to exclude script-based dReps, as they cause issues displaying the dRep ID on the dRep card.  
- Update dRep assertions to include the CIP-105 prefix.  
- Use the wallet address to generate the payment address for dReps.  
- Update the proposal discussion link.  
- Fix the issue with user snap URL interception.  
- Increase the timeout for assertions.
- Use env networkId instead of hardcoded zero to get the address from wallet
-  fix crypto not found issue
- generate wallet address according to environment network
- use stake address on proposal creation form instead of wallet address
- [related report](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/275/)
=> Fix : Report 275 failing test

CHANGELOG.md, govtool/backend/src/VVA/API/Types.hs
- fix unhandled missing index exception
- [related issue](https://github.com/IntersectMBO/govtool/issues/1841)
=> fix(#1841): fix unhandled missing index exception

CHANGELOG.md, govtool/frontend/src/components/organisms/VoteContext/VoteContextText.tsx, govtool/frontend/src/i18n/locales/en.json
- change vote rationale character limit to 10000
- [related issue](https://github.com/IntersectMBO/govtool/issues/2891)
=> fix(#2891): change vote rationale character limit to 10000

CHANGELOG.md, govtool/frontend/src/components/molecules/VotesSubmitted.tsx
- move ratification threshold label below voters title
- [related issue](https://github.com/IntersectMBO/govtool/issues/2893)
=> feat(#2893): move ratification threshold label below voters title

CHANGELOG.md, govtool/frontend/src/pages/RegisterAsDirectVoter.tsx, govtool/frontend/src/pages/RetireAsDirectVoter.tsx
- Fix incorrect link to docs for direct voters
- [related issue](https://github.com/IntersectMBO/govtool/issues/2647)
=> fix(2647): incorrect link to docs for direct voters

CHANGELOG.md, govtool/frontend/src/pages/DRepDirectoryContent.tsx
- missing "No DRep found" on DRep directory
- [related issue](https://github.com/IntersectMBO/govtool/issues/2889)
=> fix(#2889): missing "No DRep found" on DRep directory

CHANGELOG.md, govtool/frontend/src/components/organisms/DashboardCards/DRepDashboardCard.tsx
- fix displaying givenName placeholder instead of value
- [related issue](https://github.com/IntersectMBO/govtool/issues/2888)
=> fix(#2888): fix displaying givenName placeholder instead of value

CHANGELOG.md, govtool/frontend/src/context/usersnapContext.tsx
- handle missing usersnap api key exception
- [related issue](https://github.com/IntersectMBO/govtool/issues/2683)
=> fix(#2683): handle missing usersnap api key exception

tests/govtool-frontend/playwright/lib/helpers/adaFormat.ts, tests/govtool-frontend/playwright/lib/pages/governanceActionDetailsPage.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.spec.ts, tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.dRep.spec.ts, tests/govtool-frontend/playwright/tests/8-proposal-discussion/proposalDiscussion.loggedin.spec.ts
- Update governance action ada format
- Add not voted assertion for dRep
- Update vote context char limit validation 
- fix change poll vote flaky test issue
- increase timeout for reply and poll vote assertion
=> Fix: governance action ada format , vote context char limit and change poll vote

CHANGELOG.md, govtool/backend/sql/get-network-metrics.sql, govtool/frontend/src/components/molecules/GovernanceActionDetailsCardVotes.tsx, govtool/frontend/src/components/molecules/VotesSubmitted.tsx, govtool/frontend/src/components/organisms/Modal/SubmittedVotesModal.tsx
Compared to cardanoscan.io
Calculations:
Total DRep stake: Total Voting Power coming from Active DReps and pre-defined no-confidence
Yes votes: All yes votes coming from Active DReps
No votes: All no votes coming from Active DReps and pre-defined no confidence
Abstain: All abstain votes coming from Active DReps and pre-defined abstain
Not voted: Total DRep stake - Yes votes - No votes - Abstain votes (with slight adjustments for No confidence Governance Action
Yes votes percentage: **Yes votes** / **Total DRep stake**
No votes percentage: **No votes** / **Total DRep stake**
Not Voted percentage: 100 - yes votes percentage - no votes percentage.
=> chore: remove abstain from total drep votes calculation

CHANGELOG.md, govtool/frontend/src/components/organisms/DRepDetailsCard.tsx, govtool/frontend/src/i18n/locales/en.json
- show drep metadata url and hash on detailed profile view
- [related issue](https://github.com/IntersectMBO/govtool/issues/2911)
=> feat(#2911): show drep metadata url and hash on detailed profile view

CHANGELOG.md, govtool/backend/sql/list-proposals.sql, govtool/frontend/src/components/molecules/VotesSubmitted.tsx
- remove abstain governance action votes from total stake
Which results in:
Summary of equation:
Network metrics:
**Total active DRep stake**: Voting power coming from all **active** DReps
**Auto abstain**: Voting power coming from pre-defined always abstain DRep
**No confidence**: Voting power coming from pre-defined always no-confidence DRep
List proposals:
**Yes votes**: Sum of Voting power coming from DReps who voted **Yes** (+ no confidence when Governance Action Type === No confidence)
**No votes**: Sum of Voting power coming from DReps who voted **No** (+ no confidence when Governance Action Type !== No confidence)
**Abstain votes**: Sum of Voting power coming from DReps who voted **Abstain** and **Auto-abstain**
_IMPORTANT_
As DReps who voted `Abstain` because of making a vote …
=> fix: remove abstain governance action votes from total stake

.github/scripts/set_commit_status.sh, .github/workflows/test_backend.yml, .github/workflows/test_integration_playwright.yml
- Add commit status indicators for backend and Playwright tests: pending, interrupted, failure, and passed.
- Click the details link to the detailed test report if the test has failed or passed.
- Implement a similar workflow in the queue for the same branch if a similar test workflow is already running.
=> Feat: test commit status and queue management

.github/scripts/set_commit_status.sh
- fix typos of intersectMBO gh-pages casing
- set default allure report link to intersectMBO 
=> Fix: commit status report link

tests/test-infrastructure/docker-compose-govtool.yml
-  enable VITE_IS_GOVERNANCE_OUTCOMES_PILLAR_ENABLED flag in govtool stack
=> Enable VITE_IS_GOVERNANCE_OUTCOMES_PILLAR_ENABLED flag on test/qa stack

tests/govtool-frontend/playwright/lib/constants/staticWallets.ts, tests/govtool-frontend/playwright/lib/services/kuberService.ts, tests/govtool-frontend/playwright/tests/faucet.teardown.ts
- Add kuber service to merge the utxos with the proposal faucet wallet
- Merge utxos all wallets used during a test on faucet refund
=> Feat: merge utxos on faucet refund

tests/govtool-frontend/playwright/lib/_mock/index.ts, tests/govtool-frontend/playwright/lib/constants/index.ts, tests/govtool-frontend/playwright/lib/constants/staticWallets.ts, tests/govtool-frontend/playwright/lib/helpers/cardano.ts, tests/govtool-frontend/playwright/lib/helpers/metadata.ts, tests/govtool-frontend/playwright/lib/pages/proposalDiscussionPage.ts, tests/govtool-frontend/playwright/lib/pages/proposalSubmissionPage.ts, tests/govtool-frontend/playwright/lib/types.ts, tests/govtool-frontend/playwright/package.json, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.spec.ts, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/8-proposal-discussion/proposalDiscussion.spec.ts, tests/govtool-frontend/playwright/tests/auth.setup.ts
- Fix previous proposal test due to updates on proposal type test ids
- Rename skipIfTreasuryAndBootstrapping to skipIfNotInfoAndBootstrapping and reject all proposal type than info on bootstrap
- Support validation, visibility and submission tests to update the constitutional type proposal
=> Tests: constitution type proposal

.github/workflows/update-intersect-package.yml
- Change body name
- Remove unnecessary step
- Change branch name
=> chore(#2968): workflow adjustments

govtool/backend/sql/list-proposals.sql
- fix unhandled encode on wrong member hash
- additionally correct the parsing of threshold
=> fix: unhandled exception when member hash is not correct

govtool/backend/sql/list-proposals.sql
- gov action votes filtering per drep voter but also **per governance action**
=> fix: gov action votes filtering

tests/test-metadata-api/index.js
- Add dynamic CORS middleware on metadata API to handle cross-origin requests
- [related issue](https://github.com/intersectMBO/govtool/issues/2987)
=> fix: add dynamic CORS middleware to handle cross-origin requests

CHANGELOG.md, govtool/frontend/src/pages/DRepDirectoryContent.tsx
- allow searching for yourself in DRep directory
- [related issue](https://github.com/IntersectMBO/govtool/issues/2993)
=> feat(#2993): allow searching for yourself in DRep directory

CHANGELOG.md, govtool/frontend/src/components/molecules/DataActionsBar.tsx, govtool/frontend/src/components/organisms/DashboardGovernanceActions.tsx, govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx, govtool/frontend/src/hooks/queries/useGetDrepDetailsQuery.ts, govtool/frontend/src/main.tsx, govtool/frontend/yarn.lock
- fix refetching the drep directory
- [related issue](https://github.com/IntersectMBO/govtool/issues/2994)
=> fix(#2994): fix refetching the drep directory

tests/govtool-frontend/playwright/.gitignore, tests/govtool-frontend/playwright/lib/helpers/exceptionHandler.ts, tests/govtool-frontend/playwright/lib/helpers/shellyWallet.ts, tests/govtool-frontend/playwright/lib/helpers/waitedLoop.ts, tests/govtool-frontend/playwright/lib/pages/dRepDirectoryPage.ts, tests/govtool-frontend/playwright/lib/pages/governanceActionsPage.ts, tests/govtool-frontend/playwright/lib/pages/proposalDiscussionPage.ts, tests/govtool-frontend/playwright/lib/pages/proposalSubmissionPage.ts, tests/govtool-frontend/playwright/lib/services/kuberService.ts, tests/govtool-frontend/playwright/lib/walletManager.ts, tests/govtool-frontend/playwright/playwright.config.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegation.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegation.spec.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/editDRep.dRep.spec.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.spec.ts, tests/govtool-frontend/playwright/tests/6-miscellaneous/miscellaneous.dRep.spec.ts, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.ga.spec.ts, tests/govtool-frontend/playwright/tests/8-proposal-discussion/proposalDiscussion.spec.ts, tests/govtool-frontend/playwright/tests/dRep.setup.ts, tests/govtool-frontend/playwright/tests/faucet.teardown.ts, tests/govtool-frontend/playwright/tests/proposal.setup.ts
- Fix timeout / flaky test issue
- Setup 4 temporary proposal wallets for proposal submission
- Show a console message on the playwright log if there is an error on the proposal submission
- Replace timeout and use waitedLoop instead to loop until the required assert is matched
- Fix dRepTotalAbstainVote calculation
- Add intercept logic to used API response title for search proposal
- Fix dRep list test due to updates on CIP-129 and CIP-105 dRep ID display
=> Fix: flaky/timeout issue of report-321

CHANGELOG.md, govtool/frontend/src/context/wallet.tsx
- add `isStakeKeyRegistered` utility method
- [related issue](https://github.com/IntersectMBO/govtool/issues/2384)
=> feat(#2384): add `isStakeKeyRegistered` utility method

govtool/backend/README.md, govtool/frontend/README.md
=> docs: update backend readme to use proper ghc and cabal versions

CHANGELOG.md, govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx
- sync metadata links styles with the other links and hashes on gov action details
- [related issue](https://github.com/IntersectMBO/govtool/issues/3022)
=> fix(#3022): fix displaying helper buttons on governance action card details

tests/govtool-frontend/playwright/lib/helpers/dRep.ts, tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.dRep.spec.ts
- Remove redundant filter in fetchFirstActiveDRepDetails, as the active filter is applied by default
- As it unchecked the active filter and fetch random dRep instead of active dRep
- Add scroll to the page for a proper screenshot for vote status 
- Add proper status message for revote 5E test
=> fix: remove unnecessary filter in fetchFirstActiveDRepDetails ,add scroll to page and show correct message in revote "5E" test

.github/workflows/build-and-deploy-test-stack.yml
- Change secrets OUTCOMES_API_URL to VITE_OUTCOMES_API_URL
- Change env VITE_OUTCOMES_API_URL to OUTCOMES_API_URL
- Add preview-govtool environment
=> fix: outcomes api url env issue

.github/scripts/set_commit_status.sh
- Fix incorrect report number linkage in failure publish reports for both backend and integration tests.
=> fix: handle missing report number in commit status script

tests/govtool-frontend/playwright/tests/10-user-snap/userSnap.spec.ts, tests/govtool-frontend/playwright/tests/6-miscellaneous/miscellaneous.spec.ts
- Separate user snap test from 6. miscellaneous to 10. User Snap
- Update user snap test to align with updates
=> Separate user snap test from 6. miscellaneous to 10. User Snap and align with updates

CHANGELOG.md, govtool/frontend/src/components/molecules/VotesSubmitted.tsx
- hide voting threshold for cc in info type governance action
- [related issue](https://github.com/IntersectMBO/govtool/issues/3108)
=> fix(#3108): hide voting threshold for cc in info type governance action

tests/govtool-frontend/playwright/lib/forms/dRepForm.ts, tests/govtool-frontend/playwright/lib/pages/dRepDirectoryPage.ts, tests/govtool-frontend/playwright/lib/pages/proposalDiscussionPage.ts, tests/govtool-frontend/playwright/lib/types.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegation.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegation.spec.ts, tests/govtool-frontend/playwright/tests/2-delegation/delegationFunctionality.delegation.spec.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/dRepRegistration.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/editDRep.dRep.spec.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts, tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.dRep.spec.ts, tests/govtool-frontend/playwright/tests/6-miscellaneous/miscellaneous.dRep.spec.ts, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.ga.spec.ts, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/8-proposal-discussion/proposalDiscussion.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/8-proposal-discussion/proposalDiscussion.spec.ts, tests/govtool-frontend/playwright/tests/9-outcomes/outcomes.spec.ts
- Increase all wait timeout to 1 mins
- Check proposal visibility before filter and sort validation
- update metadata validation response type
- Increase timeout for outcome wait response and assertion
=> Fix: Report 344 flaky/failing test

tests/govtool-frontend/playwright/lib/_mock/outcome.json, tests/govtool-frontend/playwright/lib/constants/index.ts, tests/govtool-frontend/playwright/lib/types.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.spec.ts, tests/govtool-frontend/playwright/tests/9-outcomes/outcomes.spec.ts
- Add proposal metadata error behaviour test for both live voting and outcomes 
=> Add proposal metadata error behaviour test for both live voting and outcomes 

CHANGELOG.md, govtool/backend/sql/list-proposals.sql
- add pre filtering of active proposals to sql which allows to prefilter also votes and the other joined tables
- [related issue](https://github.com/IntersectMBO/govtool/issues/3190)
=> fix(#3190): add pre filtering of active proposals to sql

CHANGELOG.md, govtool/frontend/src/components/organisms/DRepCard.tsx, govtool/frontend/src/components/organisms/DRepDetailsCard.tsx
- Fix wrong CIP-129 script based DRep prefix
- [related issue](https://github.com/IntersectMBO/govtool/issues/3203)
=> fix(#3203): Fix wrong CIP-129 script based DRep prefix

tests/govtool-frontend/playwright/lib/pages/governanceActionDetailsPage.ts, tests/govtool-frontend/playwright/lib/pages/governanceActionsPage.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts, tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.dRep.spec.ts, tests/govtool-frontend/playwright/tests/dRep.setup.ts
- remove test skip of vote with rationale
- add test to  updated rationale of already voted governance action
=> Tests: re-vote with updated rationale

govtool/frontend/nginx.conf
Get rid of the unneded gzipping strategies that removes support for the svgs
=> chore: add missing icons to the nginx

CHANGELOG.md, govtool/frontend/src/hooks/forms/useVoteActionForm.tsx
- allow casting same vote with updated rationale
- [related issue](https://github.com/IntersectMBO/govtool/issues/3191)
=> fix(#3193): allow casting same vote with updated rationale

CHANGELOG.md, govtool/backend/src/VVA/API.hs, govtool/backend/src/VVA/DRep.hs, govtool/backend/src/VVA/Types.hs, govtool/frontend/src/components/organisms/DashboardGovernanceActions.tsx, govtool/frontend/src/components/organisms/DashboardGovernanceActionsVotedOn.tsx, govtool/frontend/src/hooks/queries/useGetDRepVotesQuery.ts, govtool/frontend/src/hooks/queries/useGetProposalsQuery.ts, govtool/frontend/src/types/global.d.ts
- Fix fetching the drep votes
- Fix filtering the governance action to vote, and voted on actions
- Fix redirection to empty governance action list
- [related issue](https://github.com/IntersectMBO/govtool/issues/3242)
=> fix(#3242): bug incorrect redirect after voting on governance action

CHANGELOG.md, govtool/frontend/src/components/organisms/DashboardGovernanceActionDetails.tsx, govtool/frontend/src/hooks/queries/useGetProposalQuery.ts
- redirect to outcomes from voting pillar
- [related issue](https://github.com/IntersectMBO/govtool/issues/3230)
=> feat(#3230): redirect to outcomes from voting pillar

.github/workflows/test_backend.yml, .github/workflows/test_integration_playwright.yml
- Prevent publishing Github status when test stack deployment failed
=> Prevent github status publish on test-stack deployment failure

CHANGELOG.md, govtool/frontend/src/consts/queryKeys.ts, govtool/frontend/src/hooks/queries/index.ts, govtool/frontend/src/hooks/queries/useGetDRepVotingPowerList.ts, govtool/frontend/src/models/api.ts, govtool/frontend/src/pages/ProposalDiscussion.tsx, govtool/frontend/src/services/index.ts, govtool/frontend/src/services/requests/getDRepVotingPowerList.ts, govtool/frontend/src/services/requests/index.ts, govtool/frontend/src/types/@intersect.mbo.d.ts, govtool/frontend/src/utils/openInNewTab.ts
- handle drep voting power list on frontend
- [related issue](https://github.com/IntersectMBO/govtool/issues/3277)
=> feat(#3277): handle drep voting power list on frontend

tests/govtool-frontend/playwright/.env.example, tests/govtool-frontend/playwright/package.json, tests/govtool-frontend/playwright/tests/9-outcomes/outcomes.spec.ts
- Fix outcome search assertion due to case
- Update env example
- Add outcome test run script on package json
=> Fix Outcome Search Case Sensitivity, Update Env Example, and Add Outcome Test Script

tests/govtool-frontend/playwright/lib/_mock/outcome.json
- Add status_time API response on outcome mock data
=> chore: add status_times to outcome mock data

tests/govtool-frontend/playwright/lib/pages/outcomesPage.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.spec.ts, tests/govtool-frontend/playwright/tests/9-outcomes/outcomes.spec.ts
- Update testId for governance action / outcome title / learnMore button for invalid metadata
- Add proper message with hash and URL for failure in metadata invalid test
=> Fix outcome titles test IDs, and Add metadata test failure message

.github/workflows/build-from-main.yml
- Fix layer caching when workflow is manually triggered
- [ x ] My changes generate no new warnings
=> fixes layer caching when workflow is manually triggered

CHANGELOG.md, govtool/frontend/src/pages/GovernanceActionDetails.tsx
- missing redirect to outcomes on disconnected state
- [related issue](https://github.com/IntersectMBO/govtool/issues/3230)
=> fix: (#3230) missing redirect to outcomes on disconnected state

CHANGELOG.md, govtool/frontend/src/components/molecules/WalletInfoCard.tsx, govtool/frontend/src/components/molecules/WalletOption.tsx
- Fix incorrect budget discussion wallet related routing
=> fix: handle incorrect routing on connecting wallet on budget discussion page

CHANGELOG.md, govtool/frontend/src/pages/ProposalDiscussion.tsx, govtool/frontend/src/types/@intersect.mbo.d.ts
- add epochParams and ada holder balance to Proposal pillar
New properties passed to PDF:
```tsx
<ProposalDiscussion
pdfApiUrl={import.meta.env.VITE_PDF_API_URL}
walletAPI={{
...context,
...walletApi,
createGovernanceActionJsonLD,
createHash,
voter,
}}
pathname={window.location.pathname}
validateMetadata={
validateMetadata as ComponentProps<
typeof ProposalDiscussion
>["validateMetadata"]
}
fetchDRepVotingPowerList={fetchDRepVotingPowerList}
// New properties passed
epochParams={epochParams}
votingPower={votingPower}
/>
```
- [related issue](https://github.com/IntersectMBO/govtool/issues/2243)
=> feat(#2243): add epochParams and ada holder balance to Proposal pillar

tests/govtool-frontend/playwright/lib/services/kuberService.ts, tests/govtool-frontend/playwright/tests/11-proposal-budget/proposalBudget.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/11-proposal-budget/proposalBudget.spec.ts
- Fix the low balance issue 
- Fix comment text ellipse issue
- Add proper message on the comment length validation issue
=> Fix: report 377 issue

tests/govtool-frontend/playwright/lib/pages/budgetDiscussionSubmissionPage.ts, tests/govtool-frontend/playwright/tests/12-proposal-budget-submission/proposalBudgetSubmission.loggedin.spec.ts
- Add validation test for budget proposal further information  section
- Add validation test for budget propsal costing section
=> tests: budget proposal costing and further information validation

govtool/frontend/src/components/organisms/DashboardGovernanceActionDetails.tsx, govtool/frontend/src/components/organisms/ValidatedGovernanceActionCard.tsx, govtool/frontend/src/components/organisms/ValidatedGovernanceVotedOnCard.tsx, govtool/frontend/src/pages/GovernanceActionDetails.tsx, govtool/metadata-validation/src/app.service.ts
Once gov action: `gov_action10ueqgzwenxr39le68n0se9peu92r7gm2846xwehh3u0ahc0qd0uqqyljxu5` expires we need to revert this PR as it provides workaround that is against the CIP-108 standard
=> hotfix: Parse metadata validation metadata when is missing in db-sync

tests/govtool-backend/lib/govtool_api.py, tests/govtool-backend/models/TestData.py, tests/govtool-backend/test_cases/test_misc.py
- Fix network metrics response type
- Add backend test to check the response type of network total stakes and network info
=> Fix network metrics type and add test for network total stakes and info

tests/govtool-frontend/playwright/lib/helpers/adaFormat.ts, tests/govtool-frontend/playwright/lib/helpers/string.ts, tests/govtool-frontend/playwright/lib/pages/budgetDiscussionSubmissionPage.ts, tests/govtool-frontend/playwright/lib/pages/governanceActionsPage.ts, tests/govtool-frontend/playwright/lib/types.ts, tests/govtool-frontend/playwright/tests/12-proposal-budget-submission/proposalBudgetSubmission.loggedin.spec.ts, tests/govtool-frontend/playwright/tests/9-outcomes/outcomes.spec.ts
- Added remaining budget proposal validation:
1. Proposal ownership
2. Problem statements and proposal benefits
3. Proposal details
4. Administration and Auditing
5. Submit
- Refactored the validation tests
=> Tests: Remaining budget proposal validation

tests/govtool-frontend/playwright/lib/pages/outcomeDetailsPage.ts, tests/govtool-frontend/playwright/lib/pages/outcomesPage.ts, tests/govtool-frontend/playwright/tests/9-outcomes/outcomes.loggedin.spec.ts
- Split out the outcome test on pages
- Add similar test cases for both loggedin and logged out in outcomes
- Fix Spos voting power issue and update the CC vote percentage
- Add proper message for voting power checked by providing the outcome URL on voting power test
=> test: add outcome test on loggedIn state

.github/workflows/test_backend.yml, tests/govtool-backend/lib/faucet_api.py
- Add branch restriction to the backend test workflow file
- Add wallet address on error message for missing FAUCET_API_KEY environment variable
=> Fix: backend test security vulnerability

tests/govtool-frontend/playwright/README.md, tests/govtool-frontend/playwright/generate_faucet_wallet.ts, tests/govtool-frontend/playwright/package.json
- Add wallet generation script for faucet wallet
- Updated Readme with instructions for setting up the faucet wallet.
=> Add Faucet Wallet Generation Script and Update README with Setup Instructions

gov-action-loader/README.md
- Add README for Governance Action Loader directory
=> feat: add README for Governance Action Loader

tests/govtool-frontend/playwright/lib/constants/auth.ts, tests/govtool-frontend/playwright/lib/constants/staticWallets.ts, tests/govtool-frontend/playwright/lib/pages/budgetDiscussionDetailsPage.ts, tests/govtool-frontend/playwright/lib/pages/budgetDiscussionPage.ts, tests/govtool-frontend/playwright/package.json, tests/govtool-frontend/playwright/tests/12-proposal-budget-submission/proposalBudgetSubmission.loggedin.pb.spec.ts, tests/govtool-frontend/playwright/tests/proposal-budget.auth.setup.ts
-  Fix: normalise contracting type comparison to lowercase
- Add new budget proposal wallet 
- Add test to verify that the  created proposal appears on the proposal list
=> Tests: filter by my proposal

CHANGELOG.md, govtool/metadata-validation/src/app.service.ts
- Remvoe optional support for the original CIP-108 standard where the canonicalization were required
- [related issue](https://github.com/IntersectMBO/govtool/issues/3591)
=> fix(#3591): remove canonicalization from the governance action metadata

CHANGELOG.md, govtool/frontend/src/components/organisms/Hero.tsx, govtool/frontend/src/components/organisms/HomeCards.tsx, govtool/frontend/src/i18n/locales/en.json
- change Hero card CTA behaviour and link to docs
- [related issue](https://github.com/IntersectMBO/govtool/issues/3467)
- [related issue](https://github.com/IntersectMBO/govtool/issues/3494)
=> feat(#3467, #3494): change Hero card CTA behaviour and docs

.github/scripts/remove_oldest_report.sh, .github/workflows/test_backend.yml, .github/workflows/test_integration_playwright.yml
- Add script to remove oldest report from govtool-test-reports repository to save space
=> feat: add script to remove oldest report  from govtool-test-reports repository

CHANGELOG.md, govtool/frontend/src/components/organisms/Modal/StatusModal.tsx, govtool/frontend/src/hooks/useWalletErrorModal.tsx
- fix blank screen on unhandled wallet error
- [related issue](https://github.com/IntersectMBO/govtool/issues/3123)
=> fix(#3123): fix blank screen on unhandled wallet error

CHANGELOG.md, govtool/frontend/src/components/molecules/tableMarkdown.css
- add scroll to markdown tables
- [related issue](https://github.com/IntersectMBO/govtool/issues/3615)
=> fix(#3615): add scroll to markdown tables

govtool/frontend/src/components/organisms/RegisterAsDRepSteps/WhatRetirementMeans.tsx, govtool/frontend/src/context/appContext.tsx, govtool/frontend/src/context/governanceAction.tsx, govtool/frontend/src/main.tsx
- Add outcomes and pdf-ui version tags to sentry
- [related issue](https://github.com/IntersectMBO/govtool/issues/1613)
=> chore: add outcomes and pdf-ui version tags to sentry

tests/govtool-frontend/playwright/lib/pages/budgetDiscussionSubmissionPage.ts, tests/govtool-frontend/playwright/lib/pages/outcomesPage.ts, tests/govtool-frontend/playwright/lib/walletManager.ts, tests/govtool-frontend/playwright/tests/11-proposal-budget/proposalBudget.dRep.pb.spec.ts, tests/govtool-frontend/playwright/tests/3-drep-registration/dRepRegistration.dRep.spec.ts, tests/govtool-frontend/playwright/tests/8-proposal-discussion/proposalDiscussion.spec.ts, tests/govtool-frontend/playwright/tests/dRep.setup.ts, tests/govtool-frontend/playwright/tests/proposal-budget.dRep.setup.ts
- Add helper function to add dRep given name on the static wallet
- Update dRep comment visibility assert
- Fix costing rejection test by filling in the cost breakdown last, to focus after filling out the currency inputs
- Trim proposal title to fix flaky test on proposal discussion
- [related report](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/410/#behaviors)
=> Fix: report 410 issue

CHANGELOG.md, govtool/backend/.gitignore, govtool/frontend/.gitignore, govtool/frontend/src/components/organisms/DashboardGovernanceActionDetails.tsx, govtool/frontend/src/pages/GovernanceActionDetails.tsx, govtool/frontend/src/services/requests/getProposal.ts, govtool/frontend/src/utils/getGovActionId.ts, govtool/frontend/src/utils/tests/getGovActionId.test.ts, govtool/metadata-validation/.gitignore
- Add CIP-129 support for gov_actions hashes in Live Voting (governance actions)
- [related issue](https://github.com/IntersectMBO/govtool/issues/3619)
=> feat(#3619): CIP-129 support for gov_actions hashes in Live Voting (governance actions)

CHANGELOG.md, govtool/frontend/src/pages/Dashboard.tsx
- Fix missing proposals dashboard title
- [related issue](https://github.com/IntersectMBO/govtool/issues/3192)
=> fix(#3192): fix missing proposals dashboard title

govtool/frontend/src/context/usersnapContext.tsx, govtool/frontend/src/i18n/locales/en.json, tests/govtool-frontend/playwright/tests/10-user-snap/userSnap.spec.ts
This PR adds a third option to the Usersnap feedback modal, allowing users to provide sentiment feedback about their experience with the application. The new option includes a required 1-5 rating scale and an optional freeform text field for additional comments.
- Added a new "Share Your Experience" option in the Usersnap feedback modal
- Implemented a required 1-5 rating scale for sentiment scoring
- Added an optional text field for additional feedback notes
- Added comprehensive test coverage for the new sentiment feedback functionality
- Added test case `10F. Should submit sentiment feedback` to verify:
- Opening the sentiment feedback option
- Selecting a rating
- Adding additional notes
- Submitting the feedback
- Verifying the success message
Closes #3535
=> Added Sentiment Feedback Option to Feedback Modal

govtool/frontend/src/context/usersnapContext.tsx, govtool/frontend/src/i18n/locales/en.json, tests/govtool-frontend/playwright/tests/10-user-snap/userSnap.spec.ts
This reverts commit 1a0ff7e79a99dec2bf595b4bc79bb4bd8d2b4e58.
@olindost 
Unfortunately, we had to revert your changes provided [here](https://github.com/IntersectMBO/govtool/pull/3656).
Reason for that is that these changes broke GovTool due to wrong i18n feedback label on Footer (from string literal to object) that I didn't caught on review as well as no longer supported by configuration parameters that was caught by @Ciabas.
I'll reopen the PR, so we can address this issues together in a proper place
=> Revert "Added Sentiment Feedback Option to Feedback Modal"

tests/govtool-frontend/playwright/lib/pages/budgetDiscussionSubmissionPage.ts, tests/govtool-frontend/playwright/lib/pages/outcomesPage.ts, tests/govtool-frontend/playwright/tests/11-proposal-budget/proposalBudget.dRep.pb.spec.ts, tests/govtool-frontend/playwright/tests/12-proposal-budget-submission/proposalBudgetSubmission.loggedin.pb.spec.ts
- Update missing testIds of the budget proposal form
=> fix: update test IDs for budget discussion form components and related tests

govtool/frontend/src/components/organisms/MaintenanceEndingBanner.tsx, govtool/frontend/src/i18n/locales/en.json
- Change the content of the red banner displayed on GovTool to reflect the latest funding status and link to relevant documentation.
- [related issue](https://github.com/IntersectMBO/govtool/issues/3702)
=> fix: update the content of the red banner displayed on GovTool

CHANGELOG.md, govtool/frontend/src/components/organisms/EditDRepInfoSteps/EditDRepForm.tsx
- Fix blank screen and type error on linkReferences when navigating to edit dRep page that has no links
- [related issue](https://github.com/IntersectMBO/govtool/issues/3714)
=> fix(#3714): type error on linkReferences when editing dRep page

tests/govtool-frontend/playwright/lib/helpers/auth.ts, tests/govtool-frontend/playwright/lib/helpers/crypto.ts, tests/govtool-frontend/playwright/lib/helpers/shellyWallet.ts, tests/govtool-frontend/playwright/package-lock.json, tests/govtool-frontend/playwright/package.json, tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.ga.spec.ts, tests/govtool-frontend/playwright/tests/proposal.setup.ts
- Update stake keys and wallet address on proposal setup with faucet stakes instead of each test
- Check if the username is set or not if already set skip that proceess 
- Bump Cardano test wallets to version 3.3.2
=> Fix: test proposal wallet insufficient

tests/govtool-frontend/playwright/lib/pages/outcomesPage.ts, tests/govtool-frontend/playwright/lib/pages/proposalDiscussionPage.ts, tests/govtool-frontend/playwright/lib/types.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts, tests/govtool-frontend/playwright/tests/8-proposal-discussion/proposalDiscussion.spec.ts
- Add multiple provided sorting order and update the sorting logic
=> feat: enhance sorting functionality for proposed governance actions

CHANGELOG.md, govtool/frontend/src/components/organisms/EditDRepInfoSteps/EditDRepForm.tsx
- Fix adding two link input fields when editing the dRep form when no links are present initially
- [related issue](https://github.com/IntersectMBO/govtool/issues/3709)
=> fix(#3709): edit dRep form adds two link input fields instead of one

tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.spec.ts
- Add a retry mechanism for getting all governance actions  on expiry governance action test
=> Fix: wrap governance action expiry test with function waited assertion

CHANGELOG.md, govtool/backend/sql/list-dreps.sql
- Fix blank page on dRep details when link or identity references contain objects `{ @value: ... }` not strings
- [related issue](https://github.com/IntersectMBO/govtool/issues/3733)
This sql can be used to extract the exact dRep data that was problematic for us and some other one with standard uri/label definitions. 
```SQL
SELECT
dh.view AS drep_view,
off_chain_vote_drep_data.given_name,
jsonb_agg(
jsonb_build_object(
'uri',   COALESCE(
CASE WHEN jsonb_typeof(ref->'uri') = 'string' THEN ref->>'uri' END,
ref->'uri'->>'@value'
),
'@type', ref->>'@type',
'label', COALESCE(
CASE WHEN jsonb_typeof(ref->'label') = 'string' THEN ref->>'label' END,
ref->'label'->>'@value'
)
)
) AS link_references
FROM drep_hash dh
JOIN drep_registration dr ON dr.drep_hash_id = dh.id
JOIN voting_anchor va ON …
```
=> fix(#3733): blank page when dRep have @value in uri or label  references

govtool/backend/sql/list-dreps.sql
Missing changes to https://github.com/IntersectMBO/govtool/pull/3737
=> fix(#3733): missing group_by updates in list-dreps.sql

CHANGELOG.md, govtool/frontend/src/components/atoms/Link.tsx, govtool/frontend/src/components/organisms/DrawerMobile.tsx, govtool/frontend/src/components/organisms/TopNav.tsx, govtool/frontend/src/consts/navItems.tsx, govtool/frontend/src/i18n/locales/en.json
- Change top menu (navbar) layout when wallet is not connected
- [related issue](https://github.com/IntersectMBO/govtool/issues/3682)
=> feat(#3682): adjust top menu layout when wallet is not connected

tests/govtool-frontend/playwright/lib/pages/outcomesPage.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.spec.ts, tests/govtool-frontend/playwright/tests/6-miscellaneous/miscellaneous.spec.ts, tests/govtool-frontend/playwright/tests/9-outcomes/outcomes.loggedin.spec.ts
- Update the navbar navigation test on the disconnect state to expand the governance action drop-down before clicking on proposal/live-voting/outcomes
- Update the governance action counts for the proposal visibility test in the disconnected state
- Fix governance action navigation test through the navbar link for outcomes
=> Fix: navbar governance action dependent test

tests/govtool-frontend/playwright/lib/forms/dRepForm.ts, tests/govtool-frontend/playwright/tests/8-proposal-discussion/proposalDiscussion.spec.ts
- Add wait time for the form after validation to settle the validation message
- Increase timeout for comment count 
=> Fix: flaky test 8F  and 3M_1

CHANGELOG.md, govtool/backend/sql/list-proposals.sql, govtool/backend/src/VVA/API.hs, govtool/backend/src/VVA/API/Types.hs, govtool/backend/src/VVA/Types.hs, govtool/frontend/package-lock.json, govtool/frontend/package.json, govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx, govtool/frontend/src/i18n/locales/en.json, govtool/frontend/src/models/api.ts, govtool/frontend/src/utils/index.ts, govtool/frontend/src/utils/tests/validateSignature.test.ts, govtool/frontend/src/utils/validateSignature.ts
- Add support ed25519 author signature validation on gov actions
- [related issue](https://github.com/IntersectMBO/govtool/issues/3745)
=> (feat#3745): support ed25519 author signature validation on gov actions

govtool/backend/sql/list-proposals.sql
- Fix repetition of authors on gov action details page
=> (fix#3745) Repetition of authors on gov action details page

tests/govtool-frontend/playwright/lib/helpers/file.ts, tests/govtool-frontend/playwright/lib/walletManager.ts
- Fix unnecessary addition characters that are appended to the wallet.json file while updating the file. 
- [related issue](https://intersectmbo.github.io/govtool-test-reports/dev/govtool-frontend/21/)
=> fix: unnecessary  addition character appended on wallet.json

govtool/frontend/src/components/molecules/tableMarkdown.css
It seems that the changes from from https://github.com/IntersectMBO/govtool/pull/3630 never affected the tables.
- [related issue](https://github.com/IntersectMBO/govtool/issues/3615)
=> (fix#3615) fix  invalid css file for markdown tables

CHANGELOG.md, govtool/frontend/src/pages/Dashboard.tsx
- Fix missing page titles on subpages: DRep details  and Gov Actions details
- [related issue](https://github.com/IntersectMBO/govtool/issues/3142)
=> (fix#3142): Fix missing page titles on subpages: DRep details and Gov Actions details

govtool/backend/sql/list-proposals.sql
https://github.com/IntersectMBO/cardano-db-sync/issues/1986
=> (fix) Hotfix for duplicated entries for pools for epoch 568 on mainnet in pool_stat table

govtool/frontend/src/components/molecules/VotesSubmitted.tsx
- add 'not voted' stake for SPO's pool
- fix SPO's pool calculation % based on the whole group (yes/no/abstain/not-voted)
- [related issue](https://github.com/IntersectMBO/govtool/issues/3881)
=> (fix#3881): update how we display SPO votes

govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx, govtool/frontend/src/i18n/locales/en.json
Working only for `3cf29192a0ee1a77985054072edcdb566ac14707730637c4635d8fb6813cb4c9`
=> [hotfix] Add info box to authors section on gov actions explaining the special case of MLabs withdrawal

govtool/backend/sql/get-network-metrics.sql
=> Hotfix: De-duplicate  rows in get-network-metrics sql

govtool/frontend/src/components/organisms/DashboardGovernanceActions.tsx
=> Update DashboardGovernanceActions.tsx - attempt 2

govtool/frontend/src/components/organisms/DashboardGovernanceActionDetails.tsx
- Fix index handling in URL on dashboard component (connected wallet view). It already worked fine for view with disconnected wallet.
- [P0 - GA index in the URL is not considered as a parameter but an html anchor](https://github.com/IntersectMBO/govtool/issues/3923)
=> P0 - GA index in the URL is not considered as a parameter but an html anchor

govtool/frontend/src/components/organisms/DashboardGovernanceActions.tsx
=> Fix search for wallet without dRep

govtool/frontend/src/hooks/queries/useGetVoteContextTextFromFile.ts
Metadata validation service doesn't support `ipfs://...` links. 
- Fix metadata validation url for ipfs links
- https://github.com/IntersectMBO/govtool/issues/3934
=> Fix: handle ipfs link for vote context validation

govtool/frontend/src/components/organisms/DashboardGovernanceActionDetails.tsx, govtool/frontend/src/pages/GovernanceActionDetails.tsx
- Fix Live Voting GA to Outcomes redirect
- [No issue](https://github.com/IntersectMBO/govtool/issues/)
=> Fix Live Voting GA to Outcomes redirect

govtool/frontend/src/context/dataActionsBar.tsx
- Fix Search stops working after entering GA details and going back to Live Voting
- [🐛 Search stops working after entering GA details and going back to Live Voting #4020](https://github.com/IntersectMBO/govtool/issues/4020)
=> Search stops working after entering GA details and going back to Live Voting #4020

govtool/backend/sql/list-dreps.sql, govtool/backend/src/VVA/DRep.hs, govtool/frontend/src/components/molecules/DataActionsBar.tsx, govtool/frontend/src/hooks/queries/useGetDRepListInfiniteQuery.ts, govtool/frontend/src/hooks/queries/useGetDRepListQuery.ts, govtool/frontend/src/hooks/queries/useGetDrepDetailsQuery.ts, govtool/frontend/src/i18n/locales/en.json, govtool/frontend/src/pages/DRepDirectoryContent.tsx
- Search scope: Changed search scope to the DRep name, and both DRep IDs. The hint text in the search box changed to: "Search for a DRep name or ID"
- Search pagination: Replaced "Show more" button with pagination.
- Search results number: Added "Found XXX out of a total of YYY".
- Search input box: Added a little "X" to clear the search query.
- Pagination doesn't really makes sense for "Random" sorting (eg. any page content would be different each time).
- After going to DRep details and back search input is cleared (the issue was already present before the changes).
- After going to DRep details and back page number resets to 1 (it's really the same issue as search input clearing so it should be fixed along with it)
- Pagination may need some visual changes based on the feedback (it's …
=> DRep search improvements #4030

govtool/frontend/src/components/molecules/DRepDataForm.tsx, govtool/frontend/src/components/organisms/UncontrolledImageInput.tsx, tests/govtool-frontend/playwright/lib/forms/dRepForm.ts, tests/govtool-frontend/playwright/lib/pages/outcomeDetailsPage.ts, tests/govtool-frontend/playwright/lib/pages/outcomesPage.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts, tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.spec.ts, tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.dRep.spec.ts, tests/govtool-frontend/playwright/tests/dRep.setup.ts
- Test Fixes / Updates for - 3e_2 , 4M , 9H_1A , 9H_1B
=> Frontend-Test-Updates-Fixes

tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts, tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.dRep.spec.ts
- 4N: Should accept valid metadata anchor on vote context
- 4O: Should reject invalid metadata anchor on vote context
These tests were failing because the voting procedure was outdated. Updated the voting flow to fix these failures.
Additionally, updated the vote context validation logic in 5L to reduce test flakiness.
=> Fix Proposal Visibility Related Tests

govtool/frontend/src/components/molecules/DataActionsBar.tsx, govtool/frontend/src/components/organisms/DashboardDrawerMobile.tsx
=> Issue 4062 Filter ans Sorting Icons goes to new line

govtool/backend/sql/get-network-metrics.sql
- Fix SQL counting the number of active CC members - additional fix for preview
- [🐛 Live Voting: Number of CC members displayed inconsistently across governance actions #4059](https://github.com/IntersectMBO/govtool/issues/4059)
=> Fix SQL counting the number of active CC members - additional fix for preview

govtool/frontend/src/components/molecules/DataActionsBar.tsx, govtool/frontend/src/pages/DRepDirectoryContent.tsx
=> Fix/Issue 4062 Filter ans Sorting Icons goes to new line

govtool/frontend/src/pages/DRepDirectoryContent.tsx
=> Fix/Issue 4094 - Problem with cuting of DrepCard
