IntersectMBO/govtool

- govtool/frontend/src/components/organisms/RegisterAsDRepSteps/WhatRetirementMeans.tsx
- govtool/frontend/src/components/organisms/RegisterAsSoleVoterBox.tsx
- govtool/frontend/src/components/organisms/RetireAsSoleVoterBox.tsx
- govtool/frontend/src/hooks/forms/useCreateGovernanceActionForm.ts
- govtool/frontend/src/hooks/forms/useEditDRepInfoForm.ts
- govtool/frontend/src/hooks/forms/useRegisterAsdRepForm.tsx
- govtool/frontend/src/hooks/forms/useVoteActionForm.tsx
- govtool/frontend/src/hooks/index.ts
- govtool/frontend/src/hooks/useDelegateToDrep.ts
- govtool/frontend/src/hooks/useWalletErrorModal.tsx
- Add wallet transaction errors modals
- [#509](https://github.com/IntersectMBO/govtool/issues/509)
- [#752](https://github.com/IntersectMBO/govtool/issues/752)
> [#509 #752] Wallet transaction errors modals

- .gitignore
- flake.nix
- govtool/frontend/README.md
- govtool/frontend/default.nix
- govtool/frontend/yarn.lock
* adds `js` devshell to fix yarn.lock
* parameterizes build to pass ENV vars
> nix: fix frontend

- CHANGELOG.md
- govtool/frontend/maintenance-page/index.html
- Changed the copy on the maintenance page
- [related issue](https://github.com/IntersectMBO/govtool/issues/753)
> [753] Chore; update copy on maintenance page

- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/yarn.lock
- scripts/govtool/docker-compose.beta.yml
- scripts/govtool/docker-compose.dev.yml
- scripts/govtool/docker-compose.node+dbsync.yml
- scripts/govtool/docker-compose.staging.yml
- scripts/govtool/docker-compose.test.yml
bump:
* cardano-node - v8.10.0-pre
* db-sync - vsancho-4.2.1
* csl - v12.0.0-alpha.29
> bump cardano-node (v8.10.0-pre), db-sync (vsancho-4.2.1), csl (12.0.0-alpha.29)

- govtool/packages/submission-tool/package.json
- govtool/packages/submission-tool/tsup.config.ts
- govtool/packages/submission-tool/yarn.lock
- govtool/packages/wallet-connector/.gitignore
- govtool/packages/wallet-connector/WalletProvider.tsx
- govtool/packages/wallet-connector/package.json
- govtool/packages/wallet-connector/tsconfig.json
- govtool/packages/wallet-connector/tsup.config.ts
- govtool/packages/wallet-connector/yarn.lock
- add tsup for both wallet-connector and submission tool to make them ready to be published and used across non-ts packages.
> chore: configure tsup for building govtool packages

- govtool/frontend/src/components/molecules/AutomatedVotingCard.tsx
- govtool/frontend/src/components/molecules/VoteActionForm.tsx
- govtool/frontend/src/components/organisms/AutomatedVotingOptions.tsx
- govtool/frontend/src/components/organisms/BgCard.tsx
- govtool/frontend/src/components/organisms/DashboardCards/DRepDashboardCard.tsx
- govtool/frontend/src/components/organisms/DashboardCards/DelegateDashboardCard.tsx
- govtool/frontend/src/components/organisms/HomeCards.tsx
- govtool/frontend/src/components/organisms/RegisterAsDRepSteps/DRepStorageInformation.tsx
- govtool/frontend/src/components/organisms/RegisterAsDRepSteps/RegisterAsDRepForm.tsx
- govtool/frontend/src/components/organisms/RegisterAsDRepSteps/WhatRetirementMeans.tsx
- govtool/frontend/src/components/organisms/TopNav.tsx
- govtool/frontend/src/components/organisms/VoteContext/VoteContextText.tsx
- govtool/frontend/src/components/organisms/types.ts
- Missing Test IDs added, according to task description.
> [#937] Missing Test IDs

- tests/test-infrastructure/build-and-deploy.sh
HotFix of metadata service image in Test stack deployment.
> BugFix: Fix image name of metadata service

- tests/test-infrastructure/build-and-deploy.sh
HotFix of gov-action-loader images in deployment
> BugFix: Fix images for gov-action-loader

- tests/test-infrastructure/docker-compose-test.yml
HotFix: rename metadata-api service name in compose file
> BugFix: Rename metadata api service name to metadata-api

- govtool/frontend/src/components/molecules/AutomatedVotingCard.tsx
- govtool/frontend/src/components/molecules/types.ts
- govtool/frontend/src/components/organisms/AutomatedVotingOptions.tsx
- govtool/frontend/src/components/organisms/DashboardCards/DelegateDashboardCard.tsx
- govtool/frontend/src/context/pendingTransaction/utils.tsx
- govtool/frontend/src/context/wallet.tsx
- govtool/frontend/src/i18n/locales/en.ts
- govtool/frontend/src/pages/DRepDirectoryContent.tsx
- govtool/frontend/src/types/automatedVotingOptions.ts
- Automated voting options layout fixes
- [related issue](https://github.com/IntersectMBO/govtool/issues/918)
> [#918] Automated voting options layout fixes

- scripts/govtool/frontend.mk
- Add missing /api to the base url making it correctly pointing to the backend.
> fix: fix frontend makefile

- tests/test-infrastructure/docker-compose-cardano.yml
- Update docker compose file to expose kuber-api publicly
> Expose kuber-api for tests

- govtool/frontend/src/components/organisms/AutomatedVotingOptions.tsx
- govtool/frontend/src/pages/DRepDirectoryContent.tsx
- In Progress DRep cards display fixes
- [related issue](https://github.com/IntersectMBO/govtool/issues/925)
> [#925] In Progress DRep cards display fixes

- tests/govtool-backend/.env.example
- tests/govtool-backend/config.py
- tests/govtool-backend/lib/faucet_api.py
- tests/govtool-backend/lib/govtool_api.py
- tests/govtool-backend/models/TestData.py
- tests/govtool-backend/setup.py
- tests/govtool-backend/test_cases/__init__.py
- tests/govtool-backend/test_cases/conftest.py
- tests/govtool-backend/test_cases/fixtures/__init__.py
- tests/govtool-backend/test_cases/fixtures/ada_holder.py
- tests/govtool-backend/test_cases/test_ada_holder.py
- tests/govtool-backend/test_cases/test_drep.py
- tests/govtool-backend/test_cases/test_misc.py
- tests/govtool-backend/test_cases/test_proposal.py
- tests/govtool-backend/test_data.json
- tests/govtool-backend/test_data.py
- Fix old tests
- Update API response schema
- Add tests for new apis
> Fix/Add tests for missing APIs

- CHANGELOG.md
- govtool/backend/src/VVA/API.hs
- govtool/backend/src/VVA/API/Types.hs
- Fix
fixes proposal/list 500 error
- [related issue](https://github.com/IntersectMBO/govtool/issues/1073)
> [#1073] fix proposal/list 500 error on HardFork proposal

- README.md
- Add SonarCloud metrics on readme
- Related Issue: https://github.com/IntersectMBO/govtool/issues/857
> Add SonarCloud metrics on Readme

- tests/govtool-frontend/playwright/.gitignore
- tests/govtool-frontend/playwright/lib/_mock/invalidInfinityProposals.json
- tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts
- tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.dRep.spec.ts
> fix: External URL checks by mocking proposals

- tests/govtool-frontend/playwright/lib/datafactory/createAuth.ts
- tests/govtool-frontend/playwright/lib/walletManager.ts
- tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.loggedin.spec.ts
- tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmissionFunctionality.tx.spec.ts
- Added remaining tests for proposal submissions (7G, 7H, and 7I)
- [issue](https://github.com/IntersectMBO/govtool/issues/1000)
> Complete proposal submission tests

- tests/govtool-frontend/playwright/lib/_mock/infoTypeProposal.json
- tests/govtool-frontend/playwright/lib/constants/staticWallets.ts
- tests/govtool-frontend/playwright/lib/forms/dRepForm.ts
- tests/govtool-frontend/playwright/lib/pages/dRepDirectoryPage.ts
- tests/govtool-frontend/playwright/lib/pages/dRepRegistrationPage.ts
- tests/govtool-frontend/playwright/lib/pages/editDRepPage.ts
- tests/govtool-frontend/playwright/lib/pages/governanceActionsPage.ts
- tests/govtool-frontend/playwright/lib/pages/proposalSubmissionPage.ts
- tests/govtool-frontend/playwright/package.json
- tests/govtool-frontend/playwright/tests/2-delegation/delegation.loggedin.spec.ts
- tests/govtool-frontend/playwright/tests/2-delegation/delegationFunctionality.delegation.spec.ts
- tests/govtool-frontend/playwright/tests/3-drep-registration/dRepRegistration.dRep.spec.ts
- tests/govtool-frontend/playwright/tests/3-drep-registration/dRepRegistration.loggedin.spec.ts
- tests/govtool-frontend/playwright/tests/3-drep-registration/editDRep.dRep.spec.ts
- tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts
- tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.loggedin.spec.ts
- tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.dRep.spec.ts
- tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.loggedin.spec.ts
- tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmissionFunctionality.tx.spec.ts
- tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmissionVisibility.loggedin.spec.ts
- tests/govtool-frontend/playwright/tests/auth.setup.ts
- Includes extra additional tests
> test: Delegated ADA display to DRep

- govtool/frontend/src/pages/DRepDetails.tsx
- fix missing margin in drep details about section
- [related issue](https://github.com/IntersectMBO/govtool/issues/1142)
> fix: fix missing margin in drep details about section

- .github/workflows/build-and-deploy-dev.yml
- govtool/frontend/src/App.tsx
- govtool/frontend/src/components/organisms/DashboardDrawerMobile.tsx
- govtool/frontend/src/components/organisms/Drawer.tsx
- govtool/frontend/src/consts/navItems.tsx
- govtool/frontend/src/context/contextProviders.tsx
- govtool/frontend/src/context/featureFlag.tsx
- govtool/frontend/src/context/index.ts
- govtool/frontend/src/utils/index.ts
- govtool/frontend/src/utils/isDevEnv.ts
- add proposal discussion forum feature flag allowing to toggle on deployment
> chore: add proposal discussion forum feature flag

- scripts/govtool/frontend.mk
- add missing variable to frontend make file
> chore: add missing variable to frontend make file

- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/yarn.lock
> chore: bump pdf-ui package

- docs/GOVERNANCE_ACTION_SUBMISSION.md
- govtool/frontend/src/components/organisms/PDFWrapper.tsx
- govtool/frontend/src/context/contextProviders.tsx
- govtool/frontend/src/context/governanceAction.tsx
- govtool/frontend/src/context/index.ts
- govtool/frontend/src/utils/generateMetadataBody.ts
- govtool/frontend/yarn.lock
- create governance action shared logic context to be used within pillars
- [related issue](https://github.com/IntersectMBO/govtool/issues/1213)
> feat: create governance actions shared state

- docs/GOVERNANCE_ACTION_SUBMISSION.md
- update buildSignSubmit parameters in gov action creation guide
> docs: update buildSignSubmit parameters in gov action creation guide

- docs/GOVERNANCE_ACTION_SUBMISSION.md
- govtool/frontend/src/components/organisms/CreateGovernanceActionSteps/CreateGovernanceActionForm.tsx
- govtool/frontend/src/components/organisms/CreateGovernanceActionSteps/ReviewCreatedGovernanceAction.tsx
- govtool/frontend/src/components/organisms/EditDRepInfoSteps/EditDRepForm.tsx
- govtool/frontend/src/components/organisms/RegisterAsDRepSteps/RegisterAsDRepForm.tsx
- govtool/frontend/src/context/governanceAction.test.tsx
- govtool/frontend/src/context/governanceAction.tsx
- govtool/frontend/src/hooks/forms/useCreateGovernanceActionForm.ts
- govtool/frontend/src/hooks/forms/useEditDRepInfoForm.ts
- govtool/frontend/src/hooks/forms/useRegisterAsdRepForm.tsx
- govtool/frontend/src/utils/generateMetadataBody.ts
- govtool/frontend/src/utils/tests/generateMetadataBody.test.ts
- Replace `link` with `references` to follow the CIP-100
- Fix typo in reference map
- Provide jsdoc for metadata methods
- Update create GA doc
> fix: fix governance action provider metadata creation

- CHANGELOG.md
- govtool/frontend/src/components/organisms/AutomatedVotingOptions.tsx
- govtool/frontend/src/components/organisms/DashboardCards/DirectVoterDashboardCard.tsx
- govtool/frontend/src/components/organisms/DashboardCards/ListGovActionsDashboardCard.tsx
- govtool/frontend/src/components/organisms/DashboardCards/ProposeGovActionDashboardCard.tsx
- govtool/frontend/src/components/organisms/Footer.tsx
- govtool/frontend/src/components/organisms/HomeCards.tsx
- govtool/frontend/src/i18n/locales/en.ts
- update link to docs
- [related issue](https://github.com/IntersectMBO/govtool/issues/1246)
> feat(#1246): update link to docs

- CHANGELOG.md
- govtool/frontend/src/components/molecules/GovernanceActionCard.tsx
- govtool/frontend/src/components/organisms/GovernanceActionsToVote.tsx
- govtool/frontend/src/i18n/locales/en.ts
- govtool/frontend/src/pages/DashboardGovernanceActionsCategory.tsx
- govtool/frontend/yarn.lock
- fix link to the GA details once in in progress
- [related issue](https://github.com/IntersectMBO/govtool/issues/1252)
> fix(#1252): fix link to the GA details once in in progress

- tests/test-infrastructure/configs_template/backend_config.json
- Update default backend config
> Fix metadata-validation default url

- tests/govtool-backend/lib/kuber_api.py
- tests/govtool-backend/pyproject.toml
- Add Missing files for backend test
> Fix: Add missing file on backend test

- .github/workflows/test_backend.yml
- tests/govtool-backend/setup.py
- tests/test-infrastructure/configs_template/backend_config.json
- tests/test-infrastructure/scripts/envsubst.py
- metadatavalidationmaxconcurrentrequests added on backend config
- Multiple faucet calls when setting up wallet for backend test
- Fix workflow for backend test reporting
- Run black lint on tests/govtool-backend folder
> Fix: backend config and tests

- CHANGELOG.md
- govtool/frontend/src/components/organisms/DashboardCards/ProposeGovActionDashboardCard.tsx
- govtool/frontend/src/components/organisms/PDFWrapper.tsx
- govtool/frontend/yarn.lock
- replace govtool-wrapper GA creation in favor of PDF Pillar
- [related issue](https://github.com/IntersectMBO/govtool/issues/1284)
> feat(#1284): replace govtool-wrapper GA creation in favor of PDF Pillar

- CHANGELOG.md
- govtool/frontend/src/components/molecules/GovernanceActionCardElement.tsx
- fix direction on the governance actions
- [related issue](https://github.com/IntersectMBO/govtool/issues/1244)
> fix(#1244): fix direction on the governance actions

- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/src/components/organisms/DashboardTopNav.tsx
- govtool/frontend/src/components/organisms/Drawer.tsx
- govtool/frontend/src/consts/index.ts
- govtool/frontend/src/consts/paths.ts
- govtool/frontend/src/pages/Dashboard.tsx
- govtool/frontend/yarn.lock
- remove propose a governance action button from wrapper
- bump pdf-ui package to v0.1.8
> chore: bump pdf-ui package to v0.1.8

- scripts/govtool/config/templates/docker-compose.yml.tpl
- remove unsafe-inline for font-src csp directive
- add data: for font-src
> chore: remove unsafe-inline for font-src csp directive

- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/yarn.lock
> chore: bump pdf-ui to v0.1.9

- .github/workflows/build-and-deploy-test-stack.yml
- tests/test-infrastructure/.env.example
- tests/test-infrastructure/docker-compose-govtool.yml
- tests/test-infrastructure/playbook.yml
- Use SENTRY_DNS_FRONTEND and SENTRY_DNS_BACKEND with APP_ENV for 
> Update sentry DNS variable in test stack

- .github/workflows/build-and-deploy-beta.yml
- .github/workflows/build-and-deploy-dev.yml
- .github/workflows/build-and-deploy-staging.yml
- .github/workflows/build-and-deploy-test.yml
- scripts/govtool/common.mk
- add force rebuild images toggle to github actions
> chore: add force rebuild images toggle to github actions

- tests/test-infrastructure/docker-compose-govtool.yml
- tests/test-infrastructure/playbook.yml
- Add USERSNAP_SPACE_API_KEY configuration in test deployment
- https://github.com/IntersectMBO/govtool/issues/1335
> Add USERSNAP_SPACE_API_KEY configuration in test deployment

- tests/govtool-frontend/playwright/lib/helpers/enum.ts
- tests/govtool-frontend/playwright/lib/pages/governanceActionsPage.ts
- Fixed test 4C_2 (Sorting validation)
> chore: Update proposal-id for frontend validation in sorting

- govtool/frontend/src/components/atoms/CopyButton.test.tsx
- govtool/frontend/src/utils/tests/getDRepID.test.ts
- govtool/frontend/vite.config.ts
> chore: fix flaky tests

- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/yarn.lock
- bump @intersect.mbo/pdf-ui@0.2.0
> chore: bump @intersect.mbo/pdf-ui@0.2.0

- CHANGELOG.md
- govtool/backend/app/Main.hs
- govtool/backend/example-config.json
- govtool/backend/src/VVA/Config.hs
- scripts/govtool/config.mk
- scripts/govtool/config/templates/backend-config.json.tpl
Added
- "sentryenv" field in backend config
- [related issue](https://github.com/IntersectMBO/govtool/issues/1401)
> [#1401] add sentryenv field to backend config

- tests/govtool-frontend/playwright/package-lock.json
- tests/govtool-frontend/playwright/package.json
> Bump versin of cardano-test-wallet to 1.2.0

- govtool/frontend/src/main.tsx
> fix: Sentry catch exception details

- scripts/govtool/config/templates/docker-compose.yml.tpl
- Allow unsafe-inline for script-src
- Allow broader sentry.io domain for connect-src
- [related issue](https://github.com/IntersectMBO/govtool/issues/1463)
> chore: update csp

- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/yarn.lock
- scripts/govtool/config/templates/docker-compose.yml.tpl
Add
(No additions in this list)
Fix
(No fixes in this list)
Change
Bump pdf-ui version to 0.2.7
Remove
(No removals in this list)
Merges
#1490 Merge pull request #1490 from IntersectMBO/chore/bump-pdf-ui-version
> Merge PR #1490: Bump pdf-ui version

- tests/govtool-frontend/playwright/package.json
- Fixed test 1D: Reject wallet connection in mainnet
> chore: bump cardano-test-wallet version to 2.0.1

- tests/govtool-frontend/playwright/package-lock.json
- Update cardano test wallet version in package-lock
> Update CTW version

- tests/govtool-frontend/playwright/tests/6-miscellaneous/miscellaneous.loggedin.spec.ts
> fix: verify identity on navigation to proposal discussion page

- govtool/frontend/package.json
- govtool/frontend/yarn.lock
- Add missing dependency @babel/preset-react
- [related issue](https://github.com/IntersectMBO/govtool/issues/1583)
> [#1583] fix: add missing dependency @babel/preset-react

- govtool/frontend/src/components/organisms/DashboardCards.tsx
- govtool/frontend/src/components/organisms/DashboardCards/ProposeGovActionDashboardCard.tsx
- Remove balance check on redirect to GA propose
- [related issue](https://github.com/IntersectMBO/govtool/issues/1413)
> [#1413] remove balance check on redirect to GA propose

- govtool/frontend/src/context/pendingTransaction/utils.tsx
- Fix query data type to be safer
- [related issue](https://github.com/IntersectMBO/govtool/issues/1404)
> [#1404] improve query data type from any

- CHANGELOG.md
- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/yarn.lock
- Updated the pdf-ui dependency to the latest version.
> chore: bump @intersect.mbo/pdf-ui@0.3.0

- tests/govtool-frontend/playwright/lib/helpers/auth.ts
- tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.loggedin.spec.ts
- tests/govtool-frontend/playwright/tests/auth.setup.ts
- Extract out duplicate auth setup into a helper function and use them on auth
> Refactor auth setup

- govtool/frontend/src/context/wallet.tsx
- remove unneeded code
- this is unneeded as the `add_inputs_from_and_change` considers change outputs at input selection time.
> Fix: removed unneeded code

- .github/workflows/build-and-deploy-beta.yml
- .github/workflows/build-and-deploy-dev.yml
- .github/workflows/build-and-deploy-staging.yml
- .github/workflows/build-and-deploy-test.yml
- CHANGELOG.md
- scripts/govtool/config.mk
- scripts/govtool/config/templates/backend-config.json.tpl
- provide more postgres connection options to allow them to be changed on a CI level
> chore: provide more postgres connection options

- govtool/backend/src/VVA/Metadata.hs
- fix indentation syntax error in Metadata.hs
> fix: fix indentation syntax error in Metadata.hs

- CHANGELOG.md
- govtool/frontend/src/context/wallet.tsx
- fix inputs selection with the change config
Based on the @Ryun1 change [here](https://github.com/Ryun1/cip95-cardano-wallet-connector/pull/80/files) :tada:
> fix(wallet): fix inputs selection with the change config

- govtool/backend/vva-be.cabal
- remove changelog from extra source files
- [related issue](https://github.com/IntersectMBO/govtool/issues/1621)
> chore(#1621): remove changelog from extra source files

- CHANGELOG.md
- govtool/frontend/src/components/organisms/DashboardCards/ProposeGovActionDashboardCard.tsx
- govtool/frontend/src/components/organisms/HomeCards.tsx
- change link to propose a governance action docs
- [related issue](https://github.com/IntersectMBO/govtool/issues/1132)
> fix(#1132): change link to propose a governance action docs

- CHANGELOG.md
- govtool/frontend/src/components/organisms/DashboardCards/DRepDashboardCard.tsx
- govtool/frontend/src/components/organisms/DashboardCards/DelegateDashboardCard.tsx
- govtool/frontend/src/components/organisms/DashboardCards/DirectVoterDashboardCard.tsx
- govtool/frontend/src/components/organisms/HomeCards.tsx
- change DRep docs links
- [related issue](https://github.com/IntersectMBO/govtool/issues/1130)
> fix(#1130): change DRep docs links

- CHANGELOG.md
- govtool/frontend/src/consts/CIP100Context.ts
- govtool/frontend/src/consts/dRepActions/jsonContext.ts
- govtool/frontend/src/consts/governanceAction/fields.ts
- govtool/frontend/src/context/governanceAction.test.tsx
- govtool/frontend/src/utils/tests/canonizeJSON.test.ts
- govtool/frontend/yarn.lock
- govtool/metadata-validation/src/schemas/cipStandardSchema.test.ts
- govtool/metadata-validation/src/schemas/cipStandardSchema.ts
- fix building metadata body
- [related issue](https://github.com/IntersectMBO/govtool/issues/1687)
> fix(#1687): fix building metadata body

- CODEOWNERS
> chore: update codeowner

- CHANGELOG.md
- govtool/frontend/src/components/molecules/GovernanceActionCard.tsx
- govtool/frontend/src/components/molecules/GovernanceActionsDatesBox.tsx
- govtool/frontend/src/components/molecules/GovernanceVotedOnCard.tsx
- govtool/frontend/src/components/organisms/DashboardGovernanceActionDetails.tsx
- govtool/frontend/src/hooks/mutations/metadataValidation/useValidateMutation.ts
- govtool/frontend/src/hooks/queries/useGetDRepListQuery.ts
- govtool/frontend/src/models/api.ts
- govtool/frontend/src/models/metadataValidation.ts
- govtool/frontend/src/pages/GovernanceActionDetails.tsx
- govtool/frontend/src/services/requests/getDRepList.ts
- govtool/frontend/src/services/requests/getDRepVotes.ts
- govtool/frontend/src/services/requests/getProposal.ts
- govtool/frontend/src/services/requests/getProposals.ts
- govtool/frontend/src/services/requests/metadataValidation/postValidate.ts
- govtool/frontend/src/stories/GovernanceActionDetailsCard.stories.ts
- govtool/frontend/src/utils/index.ts
- govtool/frontend/src/utils/mapDtoToDrep.ts
- govtool/frontend/src/utils/mapDtoToProposal.ts
- govtool/frontend/src/utils/tests/dRep.test.ts
- Fix runtime error at /edit_drep when metadata incorrect
- [related issue](https://github.com/IntersectMBO/govtool/issues/1675)
> [#1675] blank edit drep when invalid data

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_idea.yml
- Fixed auto linking to projects for issue templates
- added auto Feature label for all feature ideas
> docs: tweak and improve issue templates

- CHANGELOG.md
- govtool/frontend/src/components/molecules/Card.tsx
- govtool/frontend/src/components/molecules/DashboardActionCard.tsx
- govtool/frontend/src/components/organisms/DashboardCards/DRepDashboardCard.tsx
- govtool/frontend/src/components/organisms/DashboardCards/DelegateDashboardCard.tsx
- govtool/frontend/src/components/organisms/DashboardCards/DirectVoterDashboardCard.tsx
- govtool/frontend/src/components/organisms/DashboardCards/ListGovActionsDashboardCard.tsx
- govtool/frontend/src/components/organisms/DashboardCards/ProposeGovActionDashboardCard.tsx
- govtool/frontend/src/components/organisms/EditDRepInfoSteps/EditDRepStorageInformation.tsx
- govtool/frontend/src/components/organisms/HomeCards.tsx
- govtool/frontend/src/components/organisms/VoteContext/VoteContextStoringInformation.tsx
- govtool/frontend/src/stories/DashboardCard.stories.tsx
- Add missing data-testid attributes
- [related issue](https://github.com/IntersectMBO/govtool/issues/1050)
> [#1050] Add missing data-testid attributes

- govtool/metadata-validation/src/app.service.ts
- govtool/metadata-validation/src/utils/parseMetadata.ts
- fix parsing metadata validation
> fix: fix parsing metadata validation

- govtool/frontend/Dockerfile.qovery
> add new dockerfile

- CHANGELOG.md
- govtool/frontend/src/App.tsx
- govtool/frontend/src/components/organisms/TopBanners.tsx
- govtool/frontend/src/components/organisms/TopNav.tsx
- govtool/frontend/src/context/appContext.tsx
- govtool/frontend/src/i18n/locales/en.ts
- govtool/frontend/src/pages/GovernanceActionDetails.tsx
- govtool/frontend/src/pages/GovernanceActions.tsx
- govtool/frontend/src/pages/GovernanceActionsCategory.tsx
- govtool/frontend/src/pages/Home.tsx
- Add top banner informing about network name
- Add top banner informing about bootstrapping phase
- [1702](https://github.com/IntersectMBO/govtool/issues/1702)
- [1708](https://github.com/IntersectMBO/govtool/issues/1708)
> [#1702][#1708] Add warning banners for network name and bootstrap phase

- CHANGELOG.md
- govtool/frontend/src/components/molecules/GovernanceActionDetailsCardVotes.tsx
- govtool/frontend/src/components/molecules/VoteActionForm.tsx
- govtool/frontend/src/components/molecules/VotesSubmitted.tsx
- govtool/frontend/src/components/organisms/DashboardGovernanceActionDetails.tsx
- govtool/frontend/src/components/organisms/GovernanceActionDetailsCard.tsx
- govtool/frontend/src/i18n/locales/en.ts
- govtool/frontend/src/pages/GovernanceActionDetails.tsx
- Show cc committee and spo total gov action votes
- [related issue](https://github.com/IntersectMBO/govtool/issues/1704)
> feat(#1704): show cc committee and spo total gov action votes

- CHANGELOG.md
- govtool/backend/sql/list-proposals.sql
- add support for hard fork initiation governance action details
- [related issue](https://github.com/IntersectMBO/govtool/issues/1600)
> feat(#1600): add support for hard fork initiation governance action details

- README.md
- Fixed broken link in base readme
> docs: fix broken link in base readme

- CHANGELOG.md
- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/yarn.lock
- bump @intersect.mbo/pdf-ui to v0.3.7
> chore: bump @intersect.mbo/pdf-ui to v0.3.7

- CHANGELOG.md
- govtool/frontend/src/context/wallet.tsx
- remove unneeded wallet related sentry reports
- [related issue](https://github.com/IntersectMBO/govtool/issues/1699)
> chore(#1699): remove unneeded wallet related sentry reports

- CHANGELOG.md
- govtool/frontend/src/components/molecules/GovernanceActionDetailsCardVotes.tsx
- govtool/frontend/src/components/molecules/GovernanceVotedOnCard.tsx
- govtool/frontend/src/components/molecules/VoteActionForm.tsx
- govtool/frontend/src/components/organisms/DashboardGovernanceActionDetails.tsx
- govtool/frontend/src/components/organisms/GovernanceActionDetailsCard.tsx
- govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx
- govtool/frontend/src/components/organisms/GovernanceActionsToVote.tsx
- govtool/frontend/src/hooks/queries/useGetProposalQuery.ts
- govtool/frontend/src/models/api.ts
- govtool/frontend/src/pages/DashboardGovernanceActionsCategory.tsx
- govtool/frontend/src/pages/GovernanceActionDetails.tsx
- govtool/frontend/src/pages/GovernanceActionsCategory.tsx
- govtool/frontend/src/stories/GovernanceAction.stories.ts
- govtool/frontend/src/stories/GovernanceActionDetailsCard.stories.ts
- govtool/frontend/src/stories/GovernanceActionVoted.stories.ts
- govtool/frontend/src/utils/getGovActionId.ts
- govtool/frontend/src/utils/tests/removeDuplicatedProposals.test.ts
- Fix typescript bug leading to runtime error when entering Governance Action details page via direct link
- [related issue](https://github.com/IntersectMBO/govtool/issues/1801)
> [#1801] refactor passing props to GA details, fix ts problems

- govtool/frontend/src/stories/Footer.stories.ts
- govtool/frontend/src/stories/GovernanceAction.stories.ts
- govtool/frontend/src/stories/GovernanceActionDetailsCard.stories.ts
- govtool/frontend/src/stories/GovernanceActionVoted.stories.ts
- govtool/frontend/src/stories/modals/StatusWithLink.stories.tsx
- govtool/frontend/src/stories/modals/VotingPowerModal.stories.tsx
> fix: fix storybook tests

- CHANGELOG.md
- govtool/backend/Dockerfile
- govtool/backend/Dockerfile.qovery
- govtool/backend/vva-be.cabal
- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/yarn.lock
- govtool/metadata-validation/package-lock.json
- govtool/metadata-validation/package.json
- govtool/metadata-validation/src/main.ts
- govtool/metadata-validation/yarn.lock
> chore: bump GovTool to v1.0.14

- govtool/frontend/src/consts/dRepActions/fields.ts
- govtool/frontend/src/i18n/locales/en.ts
- govtool/frontend/src/utils/isValidFormat.ts
-  fix payment address validation
> fix: fix payment address validation

- govtool/frontend/src/components/organisms/CreateGovernanceActionSteps/StorageInformation.tsx
- govtool/frontend/src/components/organisms/EditDRepInfoSteps/EditDRepStorageInformation.tsx
- govtool/frontend/src/components/organisms/VoteContext/VoteContextStoringInformation.tsx
- update storing information links
> fix: update storing information links

- .github/workflows/code_check_frontend.yml
- .github/workflows/frontend_sonar_scan.yml
- .github/workflows/test_integration_playwright.yml
- .github/workflows/test_storybook.yml
- CHANGELOG.md
- govtool/frontend/Dockerfile
- govtool/frontend/Dockerfile.qovery
- govtool/frontend/README.md
- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/src/components/molecules/GovernanceActionDetailsDiffView.tsx
- govtool/frontend/src/components/molecules/index.ts
- govtool/frontend/src/components/molecules/react-diff-view.overrides.css
- govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx
- govtool/frontend/src/types/unidiff.d.ts
- govtool/frontend/storybook.Dockerfile
- govtool/frontend/yarn.lock
- replace json diff library to avoid using the force installation
> fix: replace json diff library to avoid using the force installation

- CHANGELOG.md
- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/yarn.lock
- chore: bump @intersect.mbo/pdf-ui to v0.3.8
> chore: bump @intersect.mbo/pdf-ui to v0.3.8

- govtool/metadata-validation/src/app.service.ts
- govtool/metadata-validation/src/dto/validateMetadata.dto.ts
- govtool/metadata-validation/src/main.ts
- govtool/metadata-validation/tsconfig.json
- limit validation request with a timeout and content length
> fix: limit validation request with a timeout and content length

- tests/govtool-backend/models/TestData.py
- Update Proposal to include cc, pool and dRep votes
> Update Proposal to include cc, pool and dRep votes

- CHANGELOG.md
- govtool/frontend/src/components/organisms/DashboardCards/DRepDashboardCard.tsx
- govtool/frontend/src/i18n/locales/en.ts
- govtool/frontend/src/models/api.ts
- replace mocked MrDRep with CIP-119 compliant metadata
- [related issue](https://github.com/IntersectMBO/govtool/issues/1887)
> fix(#1887): replace mocked MrDRep with CIP-119 compliant metadata

- CHANGELOG.md
- govtool/frontend/src/components/molecules/GovernanceActionDetailsDiffView.tsx
- govtool/frontend/src/components/organisms/DashboardGovernanceActions.tsx
- govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx
- govtool/frontend/src/hooks/queries/useGetProposalQuery.ts
- govtool/frontend/src/i18n/locales/en.ts
- fix displaying on-chain governance action details
- fix displaying Governance Action Details while navigating between GAs
- [related issue](https://github.com/IntersectMBO/govtool/issues/1889)
> fix(#1889): fix displaying on-chain governance action details

- CHANGELOG.md
- govtool/frontend/src/components/organisms/Hero.tsx
- govtool/frontend/src/i18n/locales/en.ts
- Change home page hero copy
- [related issue](https://github.com/IntersectMBO/govtool/issues/1903)
> [#1903] change home page hero copy

- CHANGELOG.md
- govtool/frontend/src/components/atoms/FormHelpfulText.tsx
- govtool/frontend/src/components/atoms/types.ts
- govtool/frontend/src/components/molecules/DRepDataForm.tsx
- govtool/frontend/src/components/molecules/Field/Checkbox.tsx
- govtool/frontend/src/components/molecules/Field/TextArea.tsx
- govtool/frontend/src/components/molecules/Field/types.ts
- govtool/frontend/src/components/molecules/index.ts
- govtool/frontend/src/components/organisms/DRepDetailsCard.tsx
- govtool/frontend/src/components/organisms/DRepDetailsCardHeader.tsx
- govtool/frontend/src/components/organisms/EditDRepInfoSteps/EditDRepForm.tsx
- govtool/frontend/src/components/organisms/RegisterAsDRepSteps/RegisterAsDRepForm.tsx
- govtool/frontend/src/components/organisms/index.ts
- govtool/frontend/src/consts/dRepActions/fields.ts
- govtool/frontend/src/consts/dRepActions/jsonContext.ts
- govtool/frontend/src/hooks/forms/useEditDRepInfoForm.ts
- govtool/frontend/src/hooks/forms/useRegisterAsdRepForm.tsx
- govtool/frontend/src/i18n/locales/en.ts
- govtool/frontend/src/models/api.ts
- govtool/frontend/src/models/metadataValidation.ts
- govtool/frontend/src/pages/DRepDetails.tsx
- govtool/frontend/src/pages/DRepDirectoryContent.tsx
- govtool/frontend/src/stories/DRepDetailsCard.stories.ts
- govtool/frontend/src/types/dRep.ts
- govtool/frontend/src/types/global.d.ts
- govtool/frontend/src/utils/generateMetadataBody.ts
- govtool/metadata-validation/src/utils/parseMetadata.ts
- Change displaying DRep details to match final designs
- Change displaying DRep registration form to match final designs
- Change displaying edit DRep metadata form to match final designs
- Add suport for Link and Identity reference types, as well as reference label, for DRep references
- Change references type returned from metadata validation service to include type and label
- Add support for Do Not List
- [related issue](https://github.com/IntersectMBO/govtool/issues/1850)
> feat/(#1850) final designs for CIP-119

- CHANGELOG.md
- govtool/frontend/src/components/atoms/VotingPowerChips.test.tsx
- govtool/frontend/src/context/getUtxos.ts
- govtool/frontend/src/context/wallet.tsx
- govtool/frontend/src/i18n/locales/en.ts
- govtool/frontend/src/utils/tests/adaFormat.test.ts
- Change the spelling of ADA to Ada or ada
- [related issue](https://github.com/IntersectMBO/govtool/issues/1916)
> [#1916] change the spelling of ADA

- CHANGELOG.md
- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/yarn.lock
- Bump @intersect.mbo/pdf-ui to v0.3.9
> chore / bump pdf-ui to v0.3.9

- CHANGELOG.md
- govtool/frontend/index.html
- Add script for Matomo Analytics
- [related issue](https://github.com/IntersectMBO/govtool/issues/1817)
> [#1817] add Matomo Analytics script

- CHANGELOG.md
- govtool/frontend/src/context/featureFlag.tsx
- Fix condition for disabling voting on different GA typesAdd / Fix / Change / Remove
- [related issue](https://github.com/IntersectMBO/govtool/issues/2008)
> [#2008] fix condition for disabling voting on different GA types

- govtool/frontend/Dockerfile.qovey
- Chore add missing commit to develop
> Chore: Add missing commit into develop

- CHANGELOG.md
- govtool/frontend/src/components/organisms/DRepDetailsCardHeader.tsx
- govtool/frontend/src/i18n/locales/en.ts
- Fix broken translation in DRep Details
- [related issue](https://github.com/IntersectMBO/govtool/issues/2036)
> [#2036] fix broken translation in DRep Details

- CHANGELOG.md
- docs/architecture/README.md
- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/src/context/wallet.tsx
- govtool/frontend/yarn.lock
> chore: bump to csl 12.1.0

- .github/workflows/merge.yaml
> add tags to merged pr

- tests/govtool-frontend/playwright/lib/constants/docsUrl.ts
- Update delegation document url
> chore: update delegation doc url

- tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts
- tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.spec.ts
- Update test ids and assertion of test 4G and 4K to check the sPos, ccCommittee and dRep vote
> Fix bug of test 4G and 4K 

- .github/workflows/build-and-deploy-test-stack.yml
- gov-action-loader/frontend/src/views/SpecificLoad.vue
- Update github ssh script to add fail on any error.
> Test deployment: Fail if any service crash when updating

- tests/govtool-frontend/playwright/tests/6-miscellaneous/miscellaneous.spec.ts
> fix: update testid of terms of use

- CHANGELOG.md
- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/yarn.lock
- Bump @intersect.mbo/pdf-ui to v0.4.0
> bump @intersect.mbo/pdf-ui to v0.4.0

- CHANGELOG.md
- govtool/backend/sql/list-proposals.sql
- govtool/frontend/src/components/molecules/VotesSubmitted.tsx
- fix counting the SPO votes
- [related issue](https://github.com/IntersectMBO/govtool/issues/2085)
> fix(#2085): fix counting the SPO votes

- govtool/frontend/src/components/molecules/VotesSubmitted.tsx
- correct DRep votes ada symbol
> fix: correct DRep votes ada symbol

- CHANGELOG.md
- govtool/backend/sql/get-stake-key-voting-power.sql
- fix counting ada holder voting power
- [related issue](https://github.com/IntersectMBO/govtool/issues/2000)
> fix(#2000): fix counting ada holder voting power

- CHANGELOG.md
- govtool/backend/sql/list-dreps.sql
- Fix duplicate DReps returned from list-dreps
- [related issue](https://github.com/IntersectMBO/govtool/issues/2171)
> [#2171] eliminate duplicate DReps

- govtool/backend/sql/list-proposals.sql
- fix ga epoch boundary for preprod
> fix: ga epoch boundary for preprod

- govtool/backend/sql/list-dreps.sql
- govtool/backend/sql/list-proposals.sql
- govtool/backend/src/VVA/API.hs
- govtool/backend/src/VVA/DRep.hs
- govtool/backend/src/VVA/Proposal.hs
- add search for metadatas in the DRep list
- add search for metadatas in the Proposal list
- [related issue](https://github.com/IntersectMBO/govtool/issues/1893)
> fix(#1893): add searching for metadatas in DRep and Proposal lists

- CHANGELOG.md
- govtool/backend/src/VVA/API.hs
- govtool/backend/src/VVA/Types.hs
- govtool/frontend/src/context/dataActionsBar.tsx
-  fix searching by drep name
- fix: displaying the wallet connected snackbar
> fix: fix searching by drep name

- CHANGELOG.md
- govtool/backend/sql/list-dreps.sql
- govtool/backend/src/VVA/DRep.hs
- govtool/frontend/src/components/organisms/DashboardCards/DRepDashboardCard.tsx
- govtool/frontend/src/hooks/queries/useGetDrepDetailsQuery.ts
- govtool/frontend/src/pages/RegisterAsdRep.tsx
- govtool/frontend/src/services/requests/getDRepList.ts
- govtool/frontend/src/stories/GovernanceActionDetailsCard.stories.ts
- fix viewing DRep details
- [related issue](https://github.com/IntersectMBO/govtool/issues/2307)
> fix(#2307): fix viewing DRep details

- CHANGELOG.md
- govtool/frontend/src/components/organisms/EditDRepInfoSteps/EditDRepStorageInformation.tsx
- govtool/frontend/src/components/organisms/RegisterAsDRepSteps/DRepStorageInformation.tsx
- govtool/frontend/src/consts/dRepActions/fields.ts
- add support for space in given name
- [related issue](https://github.com/IntersectMBO/govtool/issues/2276)
> feat(#2276): add support for space in given name

- .github/workflows/test_integration_playwright.yml
- tests/govtool-frontend/playwright/lib/constants/environments.ts
- tests/govtool-frontend/playwright/playwright.config.ts
- update configuration to support running tests on different network
- Add preview.gov.tools on workflow dispatch
> Support run playwright test on different network

- .github/workflows/build-and-deploy-beta.yml
- .github/workflows/build-and-deploy-dev.yml
- .github/workflows/build-and-deploy-staging.yml
- .github/workflows/build-and-deploy-test.yml
- CHANGELOG.md
- govtool/metadata-validation/.env.example
- govtool/metadata-validation/Dockerfile
- govtool/metadata-validation/docker-compose.yml
- govtool/metadata-validation/src/app.service.ts
- scripts/govtool/config/templates/docker-compose.yml.tpl
- scripts/govtool/metadata-validation.mk
- add support for ipfs in metadata validation service
- [related issue](https://github.com/IntersectMBO/govtool/issues/1616)
> feat(#1616): add support for ipfs in metadata validation service

- CHANGELOG.md
- docs/GOVERNANCE_ACTION_SUBMISSION.md
- govtool/backend/sql/list-proposals.sql
- govtool/frontend/src/components/molecules/GovernanceActionCardTreasuryWithdrawalElement.tsx
- govtool/frontend/src/components/molecules/index.ts
- govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx
- govtool/frontend/src/context/wallet.tsx
- govtool/frontend/src/hooks/forms/useCreateGovernanceActionForm.ts
- govtool/frontend/src/i18n/locales/en.json
- govtool/frontend/src/theme.ts
- govtool/frontend/src/types/@mui.d.ts
- add support for a list of withdrawals in treasury gov action
- [related issue](https://github.com/IntersectMBO/govtool/issues/1600)
> feat(#1600): add support for list of withdrawals in treasury gov action

- tests/govtool-frontend/playwright/.gitignore
- tests/govtool-frontend/playwright/lib/helpers/adaFormat.ts
- tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts
- tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.spec.ts
- Update governance action vote ada format
> Update governance action vote ada format

- CHANGELOG.md
- govtool/backend/src/VVA/DRep.hs
- fix listing voted-on governance actions
- [related issue](https://github.com/IntersectMBO/govtool/issues/2379)
> fix(#2379): fix listing voted-on governance actions

- CHANGELOG.md
- govtool/backend/sql/get-stake-key-voting-power.sql
- fix ada holder voting power calculation
> fix: fix ada holder voting power calculation

- govtool/frontend/src/utils/isValidFormat.ts
> feat: extend IPFS url regex

- CHANGELOG.md
- govtool/frontend/src/components/organisms/DrawerMobile.tsx
- govtool/frontend/src/components/organisms/Footer.tsx
- change link to support page
- [related issue](https://github.com/IntersectMBO/govtool/issues/2292)
> chore(#2292): change link to support page

- CHANGELOG.md
- govtool/backend/sql/get-network-metrics.sql
- govtool/backend/sql/get-transaction-status.sql
- govtool/backend/src/VVA/API.hs
- govtool/backend/src/VVA/API/Types.hs
- govtool/backend/src/VVA/Transaction.hs
- govtool/backend/src/VVA/Types.hs
- govtool/frontend/package-lock.json
- govtool/frontend/src/context/pendingTransaction/usePendingTransaction.ts
- govtool/frontend/src/context/pendingTransaction/utils.tsx
- govtool/frontend/src/models/api.ts
- govtool/frontend/src/pages/Dashboard.tsx
- govtool/frontend/src/services/requests/getTransactionStatus.ts
- govtool/frontend/tsconfig.json
- govtool/frontend/yarn.lock
- fix inconsistent voting status
- [related issue](https://github.com/IntersectMBO/govtool/issues/1713)
> fix(#1713): fix inconsistent voting status

- tests/govtool-frontend/playwright/lib/constants/docsUrl.ts
- tests/govtool-frontend/playwright/lib/constants/environments.ts
- Update test documentation URLs to reflect the actual specific URLs
> Update docs url on test according to ticket #2417

- .github/workflows/test_backend.yml
- .github/workflows/test_integration_playwright.yml
- fix backend and integration test github workflow faucet and blockfrost env 
> Fix Backend & Integration Test GitHub Workflow: Update Faucet & Blockfrost API Key Env Order

- CHANGELOG.md
- govtool/backend/app/Main.hs
- govtool/backend/sql/list-proposals.sql
- govtool/backend/src/VVA/API.hs
- govtool/backend/src/VVA/Proposal.hs
- fix mzero on multiple reloads of Governance Actions
- [related issue](https://github.com/IntersectMBO/govtool/issues/2446)
> fix(#2446): fix mzero on multiple reloads of Governance Actions

- CHANGELOG.md
- govtool/frontend/src/App.tsx
- govtool/frontend/src/hooks/useMatomo.ts
> feat: integrate matomo analytics

- CHANGELOG.md
- govtool/frontend/src/components/molecules/GovernanceActionDetailsCardLinks.tsx
- govtool/frontend/src/components/molecules/GovernanceActionDetailsCardVotes.tsx
- govtool/frontend/src/components/molecules/GovernanceVotedOnCard.tsx
- govtool/frontend/src/components/molecules/VoteActionForm.tsx
- govtool/frontend/src/components/organisms/DashboardGovernanceActionsVotedOn.tsx
- govtool/frontend/src/components/organisms/GovernanceActionDetailsCard.tsx
- govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx
- govtool/frontend/src/components/organisms/GovernanceActionsToVote.tsx
- govtool/frontend/src/hooks/forms/useVoteActionForm.tsx
- govtool/frontend/src/models/api.ts
- fix app crash on governance action details page
- [related issue](https://github.com/IntersectMBO/govtool/issues/2511)
> fix(#2511): fix app crash on governance action details page

- CHANGELOG.md
- govtool/frontend/src/components/molecules/DataActionsFilters.tsx
- govtool/frontend/src/components/molecules/DataActionsSorting.tsx
- govtool/frontend/src/components/molecules/DataMissingHeader.tsx
- govtool/frontend/src/components/molecules/DataMissingInfoBox.tsx
- govtool/frontend/src/components/organisms/DRepCard.tsx
- govtool/frontend/src/components/organisms/DRepDetailsCard.tsx
- govtool/frontend/src/components/organisms/DashboardDrawerMobile.tsx
- govtool/frontend/src/components/organisms/DrawerMobile.tsx
-  fix mobile responsiveness issue
- [related issue](https://github.com/IntersectMBO/govtool/issues/2493)
> fix(#2493): fix mobile responsiveness issue

- CHANGELOG.md
- govtool/frontend/package-lock.json
- govtool/frontend/src/components/molecules/GovernanceActionNewConstitutionDetailsTabContent.tsx
- govtool/frontend/src/components/molecules/index.ts
- govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx
- split new committee on-chain details into parameters tab
> feat: split new constitution on-chain details into tabs

- CHANGELOG.md
- govtool/backend/sql/list-dreps.sql
- govtool/frontend/src/components/molecules/GovernanceActionNewCommitteeDetailsTabContent.tsx
- govtool/frontend/src/components/organisms/DRepCard.tsx
- govtool/frontend/src/components/organisms/DRepDetailsCard.tsx
- govtool/frontend/src/i18n/locales/en.json
- govtool/frontend/src/services/requests/getDRepList.ts
- govtool/frontend/src/services/requests/getProposals.ts
- govtool/metadata-validation/package-lock.json
- add support for searching by cip-129 identifiers
- [related issue](https://github.com/IntersectMBO/govtool/issues/2571)
> fix(#2571): add support for searching by cip-129 identifiers

- CHANGELOG.md
- govtool/backend/sql/get-voting-power.sql
Fix candidate as this query is not so efficient
> fix(#2460): fix calculating live voting power

- CHANGELOG.md
- govtool/frontend/src/consts/governanceAction/fields.ts
- govtool/frontend/src/context/featureFlag.tsx
- govtool/frontend/src/context/governanceAction.test.tsx
- govtool/frontend/src/context/governanceAction.tsx
- govtool/frontend/src/hooks/forms/useCreateGovernanceActionForm.ts
- govtool/frontend/src/hooks/forms/useEditDRepInfoForm.ts
- govtool/frontend/src/hooks/forms/useRegisterAsdRepForm.tsx
- govtool/frontend/src/hooks/forms/useVoteContextForm.tsx
- govtool/frontend/src/utils/generateJsonld.ts
- govtool/frontend/src/utils/generateMetadataBody.ts
- govtool/frontend/src/utils/tests/generateMetadataBody.test.ts
- fix nested @value in metadatas
- [related issue](https://github.com/IntersectMBO/govtool/issues/2509)
> fix(#2509): fix nested @value in metadatas

- CHANGELOG.md
- govtool/backend/sql/list-dreps.sql
- govtool/frontend/src/services/requests/getDRepList.ts
- Fix fetching latest drep voting anchor
> hotfix: fetching latest drep voting anchor

- tests/govtool-frontend/playwright/lib/_mock/index.ts
- tests/govtool-frontend/playwright/lib/helpers/dRep.ts
- tests/govtool-frontend/playwright/lib/helpers/metadata.ts
- tests/govtool-frontend/playwright/lib/types.ts
- Add language and image support on the test dRep register
> feat: enhance dRep metadata handling with image and language support

- CHANGELOG.md
- govtool/frontend/src/components/organisms/DashboardGovernanceActions.tsx
- govtool/frontend/src/context/dataActionsBar.tsx
- govtool/frontend/src/hooks/queries/useGetProposalsQuery.ts
- govtool/frontend/src/services/requests/getProposals.ts
- Fix bad request on ga list
- [related issue](https://github.com/IntersectMBO/govtool/issues/2535)
> fix(#2535): fix bad request on ga list

- CHANGELOG.md
- govtool/frontend/src/context/dataActionsBar.tsx
> fix: fetching governance actions

- CHANGELOG.md
- govtool/frontend/src/components/organisms/RegisterAsDRepSteps/WhatRetirementMeans.tsx
- govtool/frontend/src/hooks/forms/useEditDRepInfoForm.ts
- govtool/frontend/src/hooks/forms/useRegisterAsdRepForm.tsx
- govtool/frontend/src/hooks/forms/useVoteActionForm.tsx
- govtool/frontend/src/hooks/useDelegateToDrep.ts
- govtool/frontend/src/pages/RegisterAsDirectVoter.tsx
- govtool/frontend/src/pages/RetireAsDirectVoter.tsx
- fix blank screen on registering as a DRep
- remove unnecessary sentry reporting on vote action
- [related issue](https://github.com/IntersectMBO/govtool/issues/2408)
> fix(#2408): fix blank screen on registering as a DRep

- govtool/backend/src/VVA/AdaHolder.hs
- [related issue](https://github.com/IntersectMBO/govtool/issues/2778)
> fix(#2778): exception when there is no voting power for given stake key

- CHANGELOG.md
- govtool/backend/sql/list-proposals.sql
- govtool/frontend/src/components/molecules/DataMissingHeader.tsx
- govtool/frontend/src/components/molecules/GovernanceActionNewConstitutionDetailsTabContent.tsx
- govtool/frontend/src/components/organisms/GovernanceActionDetailsCard.tsx
- govtool/frontend/src/components/organisms/GovernanceActionDetailsCardData.tsx
- govtool/frontend/src/i18n/locales/en.json
- add script hash to new constitution governance action
- [related issue](https://github.com/IntersectMBO/govtool/issues/2745)
> feat(#2745): add script hash to new constitution governance action

- .github/workflows/test_backend.yml
- .github/workflows/test_integration_playwright.yml
- tests/govtool-backend/config.py
- Add network on manual trigger for both frontend and backend
- set default deployment to preview.gov.tools on both frontend and backend
- Add mainnet, dev, preview host on backend
> Support network, add more host URLs, and set default tests to preview.gov.tools

- govtool/backend/sql/list-proposals.sql
- govtool/frontend/src/components/atoms/VotePill.tsx
- govtool/frontend/src/components/molecules/VotesSubmitted.tsx
- govtool/frontend/src/i18n/locales/en.json
- govtool/frontend/src/types/global.d.ts
- remove any number past the decimal point
- add `not voted` votes to DRep submitted votes section'
> feat: display not voted in drep submitted votes

- CHANGELOG.md
- govtool/frontend/src/components/molecules/VotesSubmitted.tsx
- govtool/frontend/src/components/organisms/GovernanceActionDetailsCard.tsx
- govtool/frontend/src/i18n/locales/en.json
- govtool/frontend/src/utils/adaFormat.ts
- govtool/frontend/src/utils/tests/adaFormat.test.ts
- govtool/frontend/yarn.lock
- [related issue](https://github.com/IntersectMBO/govtool/issues/2880)
> feat(#2880): add suffixes to governance actions votes

- CHANGELOG.md
- govtool/frontend/src/hooks/forms/useCreateGovernanceActionForm.ts
- govtool/frontend/src/hooks/forms/useEditDRepInfoForm.ts
- govtool/frontend/src/hooks/forms/useVoteContextForm.tsx
- remove redundant sentry reports an handled wallet exceptions
- [related issue](https://github.com/IntersectMBO/govtool/issues/2680)
> fix(#2680): remove redundant sentry reports an handled wallet exceptions

- CHANGELOG.md
- govtool/frontend/index.html
- Fix executing insert on undefined node
- [related issue](https://github.com/IntersectMBO/govtool/issues/2878)
> fix(#2878): Fix executing insert on undefined node

- .github/workflows/test_backend.yml
- .github/workflows/test_integration_playwright.yml
- tests/govtool-frontend/playwright/lib/_mock/treasuryProposedGAs.json
- tests/govtool-frontend/playwright/lib/pages/dRepDirectoryPage.ts
- tests/govtool-frontend/playwright/lib/pages/proposalDiscussionPage.ts
- tests/govtool-frontend/playwright/tests/8-proposal-discussion/proposalDiscussion.spec.ts
- Fix proposal category filter logic
- fix the proposal to show all logic
- Update upload artifact version to v
> Fix: proposal category validation logic

- CHANGELOG.md
- govtool/backend/sql/get-network-metrics.sql
- govtool/backend/src/VVA/API.hs
- govtool/backend/src/VVA/API/Types.hs
- govtool/backend/src/VVA/Network.hs
- govtool/backend/src/VVA/Types.hs
- govtool/frontend/src/components/atoms/VotePill.tsx
- govtool/frontend/src/components/molecules/VotesSubmitted.tsx
- govtool/frontend/src/models/api.ts
- govtool/frontend/src/stories/GovernanceActionDetailsCard.stories.ts
> feat: add CC ratification threshold,  not voted and votes percentages

- govtool/frontend/package.json
- govtool/frontend/src/App.tsx
- govtool/frontend/src/components/molecules/WalletInfoCard.tsx
- govtool/frontend/src/components/molecules/WalletOption.tsx
- govtool/frontend/src/components/organisms/DrawerMobile.tsx
- govtool/frontend/src/components/organisms/TopNav.tsx
- govtool/frontend/src/consts/navItems.tsx
- govtool/frontend/src/i18n/locales/en.json
- Upgraded outcomes UI package version.
- Rename Governance actions to Live Voting.
- Ensured proper navigation for the outcomes URLs when a wallet is connected and not.
> chore: upgrade outcomes package version and setup access urls

- CHANGELOG.md
- docs/GOVERNANCE_ACTION_SUBMISSION.md
- govtool/frontend/src/components/organisms/CreateGovernanceActionSteps/CreateGovernanceActionForm.tsx
- govtool/frontend/src/consts/governanceAction/fields.ts
- govtool/frontend/src/context/wallet.tsx
- govtool/frontend/src/hooks/forms/useCreateGovernanceActionForm.ts
- govtool/frontend/src/i18n/locales/en.json
- govtool/frontend/src/pages/GovernanceActionOutComes.tsx
- govtool/frontend/src/types/governanceAction.ts
- add support for submitting all governance action types
- [related issue](https://github.com/IntersectMBO/govtool/issues/2258)
> feat(#2258): add support for submitting all governance action types

- .github/workflows/update-intersect-package.yml
- CHANGELOG.md
-  add workflow to update any of the @intersect.mbo package
- [related issue](https://github.com/IntersectMBO/govtool/issues/2968)
> feat(#2968): add workflow to update any of the @intersect.mbo package

- CHANGELOG.md
- govtool/frontend/src/components/organisms/DashboardGovernanceActions.tsx
- govtool/frontend/src/i18n/locales/en.json
- govtool/frontend/src/pages/GovernanceActions.tsx
- Add button to submit a governance action
- [related issue](https://github.com/IntersectMBO/govtool/issues/1188)
> feat(#1188): add button to submit a governance action

- tests/govtool-frontend/playwright/lib/constants/index.ts
- tests/govtool-frontend/playwright/lib/pages/proposalDiscussionPage.ts
- tests/govtool-frontend/playwright/lib/pages/proposalSubmissionPage.ts
- tests/govtool-frontend/playwright/lib/types.ts
- tests/govtool-frontend/playwright/tests/8-proposal-discussion/proposalDiscussion.spec.ts
- Update test to support "motion of no confidence" type proposal
> Tests: motion of no confidence

- .github/workflows/update-govtool-version.yml
- CHANGELOG.md
- add script that automatically updates GovTool version across files
> chore: add script to update GovTool version

- CHANGELOG.md
- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/vite.config.ts
- govtool/frontend/yarn.lock
- add server side compression for large assets
> chore: add server side compression for large assets

- CHANGELOG.md
- govtool/frontend/src/components/atoms/StakeRadio.tsx
- govtool/frontend/src/components/atoms/VotingPowerChips.test.tsx
- govtool/frontend/src/components/atoms/VotingPowerChips.tsx
- govtool/frontend/src/components/molecules/GovernanceActionCardTreasuryWithdrawalElement.tsx
- govtool/frontend/src/components/organisms/AutomatedVotingOptions.tsx
- govtool/frontend/src/components/organisms/CreateGovernanceActionSteps/WhatGovernanceActionIsAbout.tsx
- govtool/frontend/src/components/organisms/DRepCard.tsx
- govtool/frontend/src/components/organisms/DRepDetailsCard.tsx
- govtool/frontend/src/components/organisms/DRepDetailsCardHeader.tsx
- govtool/frontend/src/components/organisms/DashboardCards/DRepDashboardCard.tsx
- govtool/frontend/src/components/organisms/DashboardCards/DelegateDashboardCard.tsx
- govtool/frontend/src/components/organisms/DashboardCards/DirectVoterDashboardCard.tsx
- govtool/frontend/src/components/organisms/RegisterAsDRepSteps/RolesAndResponsibilities.tsx
- govtool/frontend/src/hooks/forms/useCreateGovernanceActionForm.ts
- govtool/frontend/src/pages/DRepDirectoryContent.tsx
- govtool/frontend/src/pages/RegisterAsDirectVoter.tsx
- govtool/frontend/src/pages/RetireAsDirectVoter.tsx
- govtool/frontend/src/stories/modals/SubmittedVotesModal.stories.tsx
- use location specific ada mount formatting
- [related issue](https://github.com/IntersectMBO/govtool/issues/3031)
> feat(#3031): use location specific ada mount formatting

- CHANGELOG.md
- govtool/frontend/src/pages/DRepDirectoryContent.tsx
- improve default filtering of DRep directory
- [related issue](https://github.com/IntersectMBO/govtool/issues/3035)
> feat(#3035): improve default filtering of DRep directory

- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/src/pages/GovernanceActionOutComes.tsx
- govtool/frontend/src/types/@intersect.mbo.d.ts
- govtool/frontend/yarn.lock
- Upgrade the outcomes package to the latest version
> chore(outcomes): upgrade outcomes package to latest version

- CHANGELOG.md
- govtool/frontend/src/components/molecules/DataMissingHeader.tsx
- govtool/frontend/src/components/molecules/GovernanceActionCardElement.tsx
- govtool/frontend/src/components/organisms/DRepDetailsCard.tsx
- improve accessibility by changing header components in delegation and voting cards
- [related issue](https://github.com/IntersectMBO/govtool/issues/3065)
> chore(#3065): improve accessibility by changing header components in delegation and voting cards

- CHANGELOG.md
- govtool/frontend/src/components/organisms/DashboardCards.tsx
- govtool/frontend/src/components/organisms/DashboardCards/DirectVoterDashboardCard.tsx
- govtool/frontend/src/i18n/locales/en.json
- govtool/frontend/src/pages/RegisterAsDirectVoter.tsx
- displaying the proper voting power on direct voter card
> fix: displaying the proper voting power on direct voter card

- CHANGELOG.md
- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/src/components/molecules/DRepDataForm.tsx
- govtool/frontend/src/components/organisms/EditDRepInfoSteps/EditDRepForm.tsx
- govtool/frontend/src/consts/dRepActions/fields.ts
- govtool/frontend/src/consts/dRepActions/jsonContext.ts
- govtool/frontend/src/context/governanceAction.tsx
- govtool/frontend/src/hooks/forms/useCreateGovernanceActionForm.ts
- govtool/frontend/src/hooks/forms/useEditDRepInfoForm.ts
- govtool/frontend/src/hooks/forms/useRegisterAsdRepForm.tsx
- govtool/frontend/src/hooks/forms/useVoteContextForm.tsx
- govtool/frontend/src/i18n/locales/en.json
- govtool/frontend/src/types/dRep.ts
- govtool/frontend/src/utils/generateMetadataBody.ts
- govtool/frontend/src/utils/getImageSha.ts
- govtool/frontend/src/utils/isValidFormat.ts
- govtool/frontend/src/utils/tests/generateMetadataBody.test.ts
- govtool/frontend/vite.config.ts
- govtool/frontend/yarn.lock
- [related issue](https://github.com/IntersectMBO/govtool/issues/3137)
> feat(#3137): add image tag feature for dreps in govtool metadata

- tests/govtool-frontend/playwright/lib/helpers/transaction.ts
- tests/govtool-frontend/playwright/lib/pages/dRepDetailsPage.ts
- tests/govtool-frontend/playwright/lib/pages/dRepDirectoryPage.ts
- tests/govtool-frontend/playwright/lib/pages/governanceActionsPage.ts
- tests/govtool-frontend/playwright/lib/pages/outcomesPage.ts
- tests/govtool-frontend/playwright/tests/3-drep-registration/dRepRegistration.dRep.spec.ts
- tests/govtool-frontend/playwright/tests/5-proposal-functionality/proposalFunctionality.dRep.spec.ts
- tests/govtool-frontend/playwright/tests/8-proposal-discussion/proposalDiscussion.spec.ts
- tests/govtool-frontend/playwright/tests/9-outcomes/outcomes.spec.ts
- Fix the flaky test issue in the filter caused by the locator disappearing.
- Increase timeout on assertion
- Check visibility before clicking the show all button and share button
> Check locator visibility before validate

- CHANGELOG.md
- govtool/frontend/src/components/organisms/AutomatedVotingOptions.tsx
- govtool/frontend/src/components/organisms/DRepCard.tsx
- govtool/frontend/src/components/organisms/DRepDetailsCard.tsx
- govtool/frontend/src/pages/DRepDirectoryContent.tsx
- improve numerical data formatting in drep directory
- [related issue](https://github.com/IntersectMBO/govtool/issues/3148)
> feat(#3148): improve numerical data formatting in drep directory

- govtool/frontend/index.html
- add support for preprod matomo analyics
- [related issue](https://github.com/IntersectMBO/govtool/issues/3173)
> feat(#3173): add support for preprod matomo analyics

- tests/govtool-frontend/playwright/lib/pages/governanceActionDetailsPage.ts
- tests/govtool-frontend/playwright/lib/pages/outcomeDetailsPage.ts
- tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.dRep.spec.ts
- tests/govtool-frontend/playwright/tests/4-proposal-visibility/proposalVisibility.spec.ts
- tests/govtool-frontend/playwright/tests/6-miscellaneous/miscellaneous.spec.ts
- tests/govtool-frontend/playwright/tests/9-outcomes/outcomes.spec.ts
- Change **metrics intercept** to **info** for the network name.  
- Change **metrics intercept** to **total-stake** for **alwaysAbstainVotingPower** in live voting.  
- Fix the parsing issue on **alwaysAbstainVotingPower** for the outcome.  
> Fix: broken/failing test due to update on metrics api

- CHANGELOG.md
- govtool/frontend/src/components/organisms/Drawer.tsx
- govtool/frontend/src/i18n/locales/en.json
- Fix scroll on a drawer
- Change budget proposal nav item label
> fix: scroll on a drawer; change budget proposal nav item label

- tests/govtool-frontend/playwright/lib/_mock/proposalComments.json
- tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.loggedin.spec.ts
- tests/govtool-frontend/playwright/tests/8-proposal-discussion/proposalDiscussion.spec.ts
- fix: test 8E due to mock data
- fix: update mock proposal comments to include bd_proposal_id and comments_report
> Fix: test 8E and 8F

- govtool/frontend/src/hooks/queries/useGetDRepVotingPowerList.ts
- Add identifiers to drep voting power query keys
> fix: add identifiers to drep voting power query keys

- .github/ISSUE_TEMPLATE/feature_idea.yml
- .github/ISSUE_TEMPLATE/feature_idea_2.yml
> init new feature request template per @m-i-k-e's suggestion

- tests/govtool-frontend/playwright/lib/_mock/budgetProposal.json
- tests/govtool-frontend/playwright/lib/_mock/budgetProposalComments.json
- tests/govtool-frontend/playwright/lib/_mock/budgetProposalPoll.json
- tests/govtool-frontend/playwright/lib/_mock/index.ts
- tests/govtool-frontend/playwright/lib/constants/staticWallets.ts
- tests/govtool-frontend/playwright/lib/fixtures/budgetProposal.ts
- tests/govtool-frontend/playwright/lib/helpers/cardano.ts
- tests/govtool-frontend/playwright/lib/helpers/metadata.ts
- tests/govtool-frontend/playwright/lib/pages/budgetDiscussionDetailsPage.ts
- tests/govtool-frontend/playwright/lib/pages/budgetDiscussionPage.ts
- tests/govtool-frontend/playwright/lib/pages/budgetDiscussionSubmissionPage.ts
- tests/govtool-frontend/playwright/lib/types.ts
- tests/govtool-frontend/playwright/package.json
- tests/govtool-frontend/playwright/tests/11-proposal-budget/proposalBudget.dRep.spec.ts
- tests/govtool-frontend/playwright/tests/11-proposal-budget/proposalBudget.loggedin.spec.ts
- tests/govtool-frontend/playwright/tests/11-proposal-budget/proposalBudget.spec.ts
- tests/govtool-frontend/playwright/tests/12-proposal-budget-submission/proposalBudgetSubmission.loggedin.spec.ts
- tests/govtool-frontend/playwright/tests/12-proposal-budget-submission/proposalBudgetSubmission.spec.ts
- tests/govtool-frontend/playwright/tests/auth.setup.ts
- tests/govtool-frontend/playwright/tests/dRep.setup.ts
- tests/govtool-frontend/playwright/tests/faucet.setup.ts
- Add tests for the proposal budget discussion
> Tests: proposal budget

- tests/govtool-frontend/playwright/lib/pages/budgetDiscussionDetailsPage.ts
- tests/govtool-frontend/playwright/lib/pages/budgetDiscussionSubmissionPage.ts
- tests/govtool-frontend/playwright/lib/types.ts
- tests/govtool-frontend/playwright/tests/11-proposal-budget/proposalBudget.dRep.spec.ts
- tests/govtool-frontend/playwright/tests/12-proposal-budget-submission/proposalBudgetSubmission.loggedin.spec.ts
- tests/govtool-frontend/playwright/tests/dRep.setup.ts
- Fix: No more wallets available
- Add test for budget proposal review your submission content validation
- Skip pending implementation test with proper allure description
> tests: validate budget propsal review your submission

- CHANGELOG.md
- govtool/frontend/src/context/contextProviders.tsx
- govtool/frontend/src/context/index.ts
- govtool/frontend/src/context/proposalDiscussion.tsx
- govtool/frontend/src/pages/ProposalDiscussion.tsx
- govtool/frontend/src/types/@intersect.mbo.d.ts
- add Proposal Discussion context
- [related issue](https://github.com/IntersectMBO/govtool/issues/3341)
> feat(#3341): add Proposal Discussion context

- govtool/frontend/package-lock.json
- govtool/frontend/package.json
- govtool/frontend/src/components/molecules/GovernanceActionCardElement.tsx
- govtool/frontend/yarn.lock
> fix(#2712): allow multiple new lines in governance action metadata markdown

- tests/govtool-frontend/playwright/lib/forms/dRepForm.ts
- tests/govtool-frontend/playwright/lib/pages/budgetDiscussionDetailsPage.ts
- tests/govtool-frontend/playwright/lib/pages/budgetDiscussionSubmissionPage.ts
- tests/govtool-frontend/playwright/tests/3-drep-registration/editDRep.dRep.spec.ts
- tests/govtool-frontend/playwright/tests/9-outcomes/outcomes.spec.ts
- Fix costing typo issue
- And retry mechanism for download event if event is not triggered
- Check "other" contracting content for review submission and proposal details page
- Refactor metadata anchor validation test to use random invalid URL and URL greater than 128 characters
> Fix: report 400 test issue

- .github/workflows/test_integration_playwright.yml
- Add branch restriction to the integration test workflow file
> Add branch restriction to integration test workflow

- tests/govtool-frontend/playwright/.env.example
- tests/govtool-frontend/playwright/README.md
- tests/govtool-frontend/playwright/generate_faucet_wallet.ts
-  Add network on the host URL
-  Add additional details for the testnet faucet fund on readme
- update the wrong value and the env on the env.example
> Feat: add network and wallet funding details on readme

- tests/govtool-frontend/playwright/lib/forms/dRepForm.ts
- tests/govtool-frontend/playwright/lib/helpers/dRep.ts
- tests/govtool-frontend/playwright/lib/types.ts
- Add image field on IDRepInfo
- Add image validation on dRep / edit dRep form
> feat: add image validation for dRep form

- .github/scripts/register_report.sh
- .github/scripts/remove_oldest_report.sh
- .github/workflows/test_backend.yml
- .github/workflows/test_integration_playwright.yml
- tests/govtool-frontend/playwright/lib/constants/environments.ts
- tests/govtool-frontend/playwright/lib/helpers/cardano.ts
- tests/govtool-frontend/playwright/tests/7-proposal-submission/proposalSubmission.ga.spec.ts
- tests/govtool-frontend/playwright/tests/proposal.setup.ts
- Add a schedule to run nightly tests on the preview for both integration and backend tests
- Skip the proposal submission test for the schedule workflow trigger
- Remove the old report only if the report history is more than 10
- Append nightly- for the report name when the workflow is triggered by schedule
- Add new report name on new line
- 
> Feat: nightly preview test run

- .github/workflows/test_backend.yml
- .github/workflows/test_integration_playwright.yml
- Add missing deployment env on integration test
- Set the preview deployment environment on the schedule workflow
> Fix: deployment env issue on schedule workflow

- govtool/frontend/src/components/molecules/HomeCard.tsx
- govtool/frontend/src/i18n/locales/en.json
- [related issue](https://github.com/IntersectMBO/govtool/issues/3669)
> fix(#3669): missing testIds on home page cards

- govtool/frontend/package-lock.json
- govtool/frontend/package.json
This reverts commit 8aa3e5e0ff2581cede1da48237e235926577dd1a.
> Revert "chore: update @intersect.mbo/pdf-ui to 1.0.0-alfa"

- .github/workflows/build-from-test.yml
> updates image name in curl command

- govtool/frontend/src/components/molecules/VotesSubmitted.tsx
- Add SPO's not voted percentage value to gov actions
- [related issue](https://github.com/IntersectMBO/govtool/issues/3881)
> (fix#3881) Add SPOs not voted percentage value to gov actions

- govtool/backend/sql/get-network-metrics.sql
> Fix CommitteeThreshold query in network-metrics

- govtool/backend/sql/list-proposals.sql
- govtool/backend/src/VVA/Proposal.hs
> Update Proposal.hs - making sure it does exact txhash match

- govtool/frontend/src/components/organisms/DashboardGovernanceActions.tsx
- govtool/frontend/src/hooks/queries/useGetProposalsQuery.ts
> issue:3918 disappearing data ToVote

- govtool/frontend/src/components/organisms/DashboardGovernanceActions.tsx
> 3918 race condition fix

- govtool/frontend/src/App.tsx
- govtool/frontend/src/components/atoms/types.ts
- govtool/frontend/src/components/molecules/GovernanceActionCard.tsx
- govtool/frontend/src/components/organisms/GovernanceActionsToVote.tsx
- govtool/frontend/src/components/organisms/Slider.tsx
- govtool/frontend/src/components/organisms/ValidatedGovernanceActionCard.tsx
- govtool/frontend/src/pages/DashboardGovernanceActionsCategory.tsx
- govtool/frontend/src/pages/GovernanceActionsCategory.tsx
- govtool/frontend/src/stories/Slider.stories.tsx
- Add: Allow Opening Governance Actions in New Tab from Live Voting Page
- [related issue](https://github.com/IntersectMBO/govtool/issues/3924)
> Allow Opening Governance Actions in New Tab from Live Voting Page

- govtool/backend/src/VVA/API.hs
> Issue 3918 temporary bypass

- govtool/frontend/src/App.tsx
- govtool/frontend/src/components/atoms/types.ts
- govtool/frontend/src/components/molecules/GovernanceActionCard.tsx
- govtool/frontend/src/components/organisms/GovernanceActionsToVote.tsx
- govtool/frontend/src/components/organisms/Slider.tsx
- govtool/frontend/src/components/organisms/ValidatedGovernanceActionCard.tsx
- govtool/frontend/src/pages/DashboardGovernanceActionsCategory.tsx
- govtool/frontend/src/pages/GovernanceActionsCategory.tsx
- govtool/frontend/src/stories/Slider.stories.tsx
- Add: Allow Opening Governance Actions in New Tab from Live Voting Page - Fixed
- [related issue](https://github.com/IntersectMBO/govtool/issues/3924)
> Allow Opening Governance Actions in New Tab from Live Voting Page - Fixed

- govtool/frontend/src/components/organisms/DashboardGovernanceActionsVotedOn.tsx
> Vote On By Me serach fix

- govtool/frontend/src/pages/DRepDirectoryContent.tsx
> Clening search input on start dRepDirectory

- govtool/frontend/src/context/dataActionsBar.tsx
> Update dataActionsBar.tsx - empty list of GAs on back after idle time

- govtool/frontend/src/hooks/queries/useGetProposalsQuery.ts
> Update useGetProposalsQuery.ts - 3978 - voterReady logic added

- govtool/frontend/src/pages/GovernanceActionDetails.tsx
- Fix Governance Action Page Fails When Index Is Missing in URL and wallet not connected 
- [🐛 Governance Action Page Fails When Index Is Missing in URL and wallet not connected #4058](https://github.com/IntersectMBO/govtool/issues/4058)
> 🐛 Governance Action Page Fails When Index Is Missing in URL and wallet not connected #4058

- govtool/frontend/src/components/molecules/DataActionsBar.tsx
> Fix/Issue 4062 Filter ans Sorting Icons goes to new line

- govtool/frontend/src/consts/dRepDirectory/sorting.ts
> fix Activity Voting instead of Voting Activity

- govtool/frontend/src/utils/validateSignature.ts
- Fix invalid signature display on GA details authors
- [no issue] (https://github.com/IntersectMBO/govtool/issues/)
> Fix invalid signature display on GA details authors

- govtool/frontend/src/pages/DRepDirectoryContent.tsx
> Fix/Issue 4094 - Problem with cuting of DrepCard
